### ISSUE TITLE
[bug]: abs和square三阶导的问题

### ISSUE THREAD

**Issue by Yang-lin-09** [Oneflow-Inc/oneflow#10243]
## Summary

在测试文件test_global_math_op_higher_derivative.py和test_math_op_higher_derivative.py中，添加了对于三阶导数的测试会导致abs和square发生不同程度报错。

```bash
❯ python test_math_op_higher_derivative.py       
E.......................F..
======================================================================
ERROR: test_abs_grad_grad (__main__.TestMathOpHigherDerivative)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/home/zhangyanglin/Code/oneflow-master/python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 668, in get_pytorch_oneflow_res
    pytorch_res = pytorch(*pytorch_args, **pytorch_kwargs)
  File "/data/home/zhangyanglin/miniconda3/envs/oneflow-compile/lib/python3.9/site-packages/torch/autograd/__init__.py", line 300, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/zhangyanglin/Code/oneflow-master/python/oneflow/test/modules/test_math_op_higher_derivative.py", line 156, in test_abs_grad_grad
    _test_math_op_grad_grad_impl(test_case, "abs")
  File "/data/home/zhangyanglin/Code/oneflow-master/python/oneflow/test/modules/test_math_op_higher_derivative.py", line 52, in _test_math_op_grad_grad_impl
    x_grad_grad_grad = torch.autograd.grad(x_grad_grad, x, init_grad, retain_graph=True)[0]
  File "/data/home/zhangyanglin/Code/oneflow-master/python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 830, in dual_method
    pytorch_res, oneflow_res = get_pytorch_oneflow_res(
  File "/data/home/zhangyanglin/Code/oneflow-master/python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 733, in get_pytorch_oneflow_res
    raise PyTorchDoesNotSupportError(e)
oneflow.test_utils.automated_test_util.torch_flow_dual_object.PyTorchDoesNotSupportError: PyTorch error: element 0 of tensors does not require grad and does not have a grad_fn

======================================================================
FAIL: test_square_grad_grad (__main__.TestMathOpHigherDerivative)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/home/zhangyanglin/Code/oneflow-master/python/oneflow/test/modules/test_math_op_higher_derivative.py", line 150, in test_square_grad_grad
    _test_math_op_grad_grad_impl(test_case, "square")
  File "/data/home/zhangyanglin/Code/oneflow-master/python/oneflow/test/modules/test_math_op_higher_derivative.py", line 53, in _test_math_op_grad_grad_impl
    test_case.assertTrue(
AssertionError: False is not true
```

```bash
❯ python test_global_math_op_higher_derivative.py
F.......................F..
======================================================================
FAIL: test_global_abs_grad_grad (__main__.TestGlobalMathOpHigherDerivative)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/home/zhangyanglin/Code/oneflow-master/python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 1370, in new_f
    return f(*args, **kwargs)
  File "/data/home/zhangyanglin/Code/oneflow-master/python/oneflow/test/modules/test_global_math_op_higher_derivative.py", line 242, in test_global_abs_grad_grad
    _global_math_op_grad_grad_impl(test_case, "abs", placement, sbp)
  File "/data/home/zhangyanglin/Code/oneflow-master/python/oneflow/test/modules/test_global_math_op_higher_derivative.py", line 45, in _global_math_op_grad_grad_impl
    test_case.assertTrue(
AssertionError: False is not true

======================================================================
FAIL: test_global_square_grad_grad (__main__.TestGlobalMathOpHigherDerivative)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/home/zhangyanglin/Code/oneflow-master/python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 1370, in new_f
    return f(*args, **kwargs)
  File "/data/home/zhangyanglin/Code/oneflow-master/python/oneflow/test/modules/test_global_math_op_higher_derivative.py", line 230, in test_global_square_grad_grad
    _global_math_op_grad_grad_impl(test_case, "square", placement, sbp)
  File "/data/home/zhangyanglin/Code/oneflow-master/python/oneflow/test/modules/test_global_math_op_higher_derivative.py", line 56, in _global_math_op_grad_grad_impl
    test_case.assertTrue(
AssertionError: False is not true
```

在两个文件的三阶导测试中，oneflow的square算子三阶导会跑出来nan，torch的square算子三阶导全是0；在非global测试中，pytorch的abs算子三阶导会报上面的错误，global的测试中，pytorch的abs二阶导是错的，不是0，oneflow的是0，三阶导会报上面的错误。

## Code to reproduce bug

(https://github.com/Yang-lin-09/oneflow/commit/1e1a36e54365292e0289d73abcef9672084e5f43)

## System Information

oneflow-27

```bash
path: ['/data/home/zhangyanglin/Code/oneflow-master/python/oneflow']
version: 0.9.1+cu117.git.ab952a9
git_commit: ab952a9
cmake_build_type: Release
rdma: False
mlir: False

torch version: 1.13.0
```

**Comment by reygu** [comment]
abs 一阶导和 squre 的二阶导都是常数了，所以不支持对输入 x 进行更高阶的求导

**Comment by Yang-lin-09** [comment]
感觉常数求导应该输出是0，就像torch的square那样。不过这个square的三阶导在实际中应该不会使用这个。

**Comment by hjchen2** [comment]
pytorch的square用的是pow实现的，因此square可以一直求导下去，但如果是y = x * x这种更一般的写法，pytorch也是不能求导的，如果要让求导进行下去需要指定allow_unused=True，这样计算的导数是None，不是0。如果要对齐pytorch这里的行为的话，也可以在oneflow里把square的实现改成pow。

**Comment by hjchen2** [comment]
pytorch abs二阶导的问题，应该是和他的一阶导的计算有关。如果要让Abs二阶导的行为和pytorch对齐，就要在oneflow的ODS里把AbsGrad这个op设置为NoGrad

**Comment by reygu** [comment]
补充一个 abs 的测试结果，非global abs 的二阶导 pytorch 和 oneflow 报错是对齐的，提示 `element 0 of tensors does not require grad and does not have a grad_fn`。 

global 情况下不一致可能是 autotest 框架的问题导致的，打印结果 x_grad.pytorch.detach().cpu().numpy() 实际获取到的是 init_grad，在最新的 nightly 版本 ( 0.9.1.dev20230507+cu117) 存在这个问题，0.9.0 的正式版没这个问题
测试代码：
```python
import unittest

import numpy as np
import oneflow as flow
import oneflow.unittest
from oneflow.test_utils.automated_test_util import *


def _global_math_op_grad_grad_impl(test_case, op_name, placement, sbp):
    x = (
        random_tensor(2, dim0=8, dim1=8, low=-2, high=2)
        .to_global(placement=placement, sbp=sbp)
        .requires_grad_(True)
    )
    y = eval(f"torch.{op_name}")(x)
    init_grad = random_tensor(2, 8, 8).to_global(placement, sbp).requires_grad_()

    x_grad = torch.autograd.grad(y, x, init_grad, create_graph=True)[0]
    test_case.assertTrue(
        np.allclose(
            x_grad.pytorch.detach().cpu().numpy(),
            x_grad.oneflow.detach().numpy(),
            atol=1e-4,
            rtol=1e-4,
            equal_nan=True,
        )
    )

    x_grad_grad = torch.autograd.grad(x_grad, x, init_grad, create_graph=True, retain_graph=True)[0]
    print(">>>>>>>>>>>>>>>>>>>>>>>>>>>>>>")
    print('init_grad: ', init_grad)
    print('x_grad_grad: ', x_grad_grad)
    a = x_grad_grad.pytorch.detach().cpu().numpy()
    b = x_grad_grad.oneflow.detach().numpy()
    print('a, b: ', a, b)
    print('a == b:\n', a == b)
    print("<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<")
    test_case.assertTrue(
        np.allclose(
            a,
            b,
            atol=1e-4,
            rtol=1e-4,
            equal_nan=True,
        )
    )


class TestGlobalMathOpHigherDerivative(flow.unittest.TestCase):
    @globaltest
    def test_global_abs_grad_grad(test_case):
        for placement in all_placement():
            for sbp in all_sbp(placement, max_dim=2):
                _global_math_op_grad_grad_impl(test_case, "abs", placement, sbp)


if __name__ == "__main__":
    unittest.main()
```
输出结果：
```
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
init_grad:  PyTorch object:
tensor([[-0.4591,  0.1589,  0.2908, -0.5346,  0.2565, -0.6477, -0.8773, -0.9141],
        [ 0.6931, -0.1636, -0.1198,  0.5688,  0.1801,  0.0741,  0.0803, -0.5777],
        [-0.7507, -0.0264,  0.3259, -0.1801, -0.8944, -0.9336,  0.2037,  0.3753],
        [-0.8404, -0.9517, -0.9404, -0.4479, -0.0940, -0.4449, -0.8404,  0.0420],
        [ 0.1863, -0.9388, -0.8799,  0.7095, -0.8673, -0.8624,  0.9618, -0.5762],
        [ 0.5291, -0.9700, -0.6071,  0.7937, -0.7352, -0.8822,  0.8850, -0.4777],
        [-0.6890,  0.7802,  0.1011,  0.8624, -0.6084, -0.6416,  0.2736, -0.0636],
        [-0.2290, -0.0440, -0.1354, -0.2320, -0.6103, -0.6183, -0.3365,  0.7675]],
       grad_fn=<CloneBackward0>)

OneFlow object:
tensor([[-0.4591,  0.1589,  0.2908, -0.5346,  0.2565, -0.6477, -0.8773, -0.9141],
        [ 0.6931, -0.1636, -0.1198,  0.5688,  0.1801,  0.0741,  0.0803, -0.5777],
        [-0.7507, -0.0264,  0.3259, -0.1801, -0.8944, -0.9336,  0.2037,  0.3753],
        [-0.8404, -0.9517, -0.9404, -0.4479, -0.0940, -0.4449, -0.8404,  0.0420],
        [ 0.1863, -0.9388, -0.8799,  0.7095, -0.8673, -0.8624,  0.9618, -0.5762],
        [ 0.5291, -0.9700, -0.6071,  0.7937, -0.7352, -0.8822,  0.8850, -0.4777],
        [-0.6890,  0.7802,  0.1011,  0.8624, -0.6084, -0.6416,  0.2736, -0.0636],
        [-0.2290, -0.0440, -0.1354, -0.2320, -0.6103, -0.6183, -0.3365,  0.7675]],
       placement=oneflow.placement(type="cuda", ranks=[0]), sbp=(oneflow.sbp.split(dim=0),), dtype=oneflow.float32,
       grad_fn=<global_to_globalBackward>)
x_grad_grad:  PyTorch object:
tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

OneFlow object:
tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]], placement=oneflow.placement(type="cuda", ranks=[0]),
       sbp=(oneflow.sbp.split(dim=0),), dtype=oneflow.float32)
a, b:  [[-0.45911002  0.15888597  0.2907834  -0.5346309   0.25648016 -0.64774513
  -0.87727606 -0.91410935]
 [ 0.69309586 -0.16355811 -0.11979527  0.56881493  0.18005928  0.07407247
   0.08031242 -0.57773775]
 [-0.7506873  -0.02643984  0.32594967 -0.18008515 -0.8944475  -0.9335514
   0.20374328  0.37531447]
 [-0.8404324  -0.9517107  -0.94036055 -0.44789162 -0.09402066 -0.4448897
  -0.84044284  0.04202585]
 [ 0.18632603 -0.93879086 -0.8799472   0.7095398  -0.8672569  -0.8624001
   0.9618454  -0.5761889 ]
 [ 0.5291246  -0.97004354 -0.6070794   0.79365736 -0.7351978  -0.8822104
   0.88496727 -0.4776723 ]
 [-0.68899536  0.7801616   0.10107978  0.8623855  -0.60841334 -0.64156395
   0.27363318 -0.06357118]
 [-0.22904609 -0.04404515 -0.13544384 -0.2319766  -0.6102632  -0.6183444
  -0.33653113  0.76746124]] [[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
a == b:
 [[False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]]
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
F
======================================================================
FAIL: test_global_abs_grad_grad (__main__.TestGlobalMathOpHigherDerivative)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/home/zhuping/miniconda3/envs/nightly/lib/python3.10/site-packages/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 1370, in new_f
    return f(*args, **kwargs)
  File "/data/home/zhuping/oneflow-dev/python/oneflow/test/modules/test_global_math_op_higher_derivative.py", line 69, in test_global_abs_grad_grad
    _global_math_op_grad_grad_impl(test_case, "abs", placement, sbp)
  File "/data/home/zhuping/oneflow-dev/python/oneflow/test/modules/test_global_math_op_higher_derivative.py", line 53, in _global_math_op_grad_grad_impl
    test_case.assertTrue(
AssertionError: False is not true

----------------------------------------------------------------------
Ran 1 test in 1.614s
```

**Comment by levi131** [comment]
问题已解决
