### ISSUE TITLE
[Question]: liboneflow.so: undefined symbol: cudaConfigureCall

### ISSUE THREAD

**Issue by jinghere11** [Oneflow-Inc/oneflow#10418]
### Description

Traceback (most recent call last):
  File "/data/***/anaconda3/envs/oneflow-dev-gcc9/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/data/***/anaconda3/envs/oneflow-dev-gcc9/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/data/***/anaconda3/envs/oneflow-dev-gcc9/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/***/users/***/app/conda-env/python/oneflow/__init__.py", line 21, in <module>
    import oneflow._oneflow_internal
ImportError: /***/users/***/app/conda-env/build/liboneflow.so: undefined symbol: cudaConfigureCall

**Comment by jinghere11** [comment]
this is caused by two cuda versions conflicting
