### ISSUE TITLE
ERROR: Skipping '//tensorflow/compiler/jit/xla_lib:libxla_core.so': error loading package 'tensorflow/compiler/jit/xla_lib': 

### ISSUE THREAD

**Issue by qianzhang613** [Oneflow-Inc/oneflow#3370]
i am follow build the  xrt with  : https://github.com/Oneflow-Inc/oneflow/blob/master/oneflow/xrt/README.md
```
    git submodule update --init --recursive && \
    cd build && \
    cmake .. -DWITH_XLA=ON -DWITH_TENSORRT=ON -DTHIRD_PARTY=ON -DCMAKE_BUILD_TYPE=Release && \
    make -j$(nproc) && \
    cmake .. -DWITH_XLA=ON  -DWITH_TENSORRT=ON -DTHIRD_PARTY=OFF -DCMAKE_BUILD_TYPE=Release && \
    make -j$(nproc) && \
    make pip_install

```
and there is error occur: 

```
ERROR: Skipping '//tensorflow/compiler/jit/xla_lib:libxla_core.so': error loading package 'tensorflow/compiler/jit/xla_lib': Label '//tensorflow/core:platform/default/build_config.bzl' crosses boundary of subpackage 'tensorflow/core/platform' (perhaps you meant to put the colon here: '//tensorflow/core/platform:default/build_config.bzl'?)WARNING: Target pattern parsing failed.ERROR: error loading package 'tensorflow/compiler/jit/xla_lib': Label '//tensorflow/core:platform/default/build_config.bzl' crosses boundary of subpackage 'tensorflow/core/platform' (perhaps you meant to put the colon here: '//tensorflow/core/platform:default/build_config.bzl'?)
```

so how to fix

**Comment by jackalcooper** [comment]
Could your checkout branch `refine_xrt_build` and build again? We have succeeded in compiling OneFlow with XLA on this branch.

As for the error log your posted. Could you confirm that bazel is installed in your system? If not,  you might download it from here: https://github.com/bazelbuild/bazel/releases/download/0.24.0/bazel-0.24.0-linux-x86_64

**Comment by jackalcooper** [comment]
Also, please compile OneFlow with XLA on a system with good network condition. It will download a lot of dependencies. Sometimes it emits some mysterious error messages but it is due to broken internet.

**Comment by qianzhang613** [comment]
@jackalcooper  thanks your reply.

i swith to `refine_xrt_build` branch, then the error change:
```
In file included from /oneflow/build/tensorflow/src/tensorflow/tensorflow/core/platform/logging.h:35:0,                 from /oneflow/build/tensorflow/src/tensorflow/tensorflow/core/lib/core/status.h:25,                 from /oneflow/build/tensorflow/src/tensorflow/tensorflow/compiler/xla/status.h:19,                 from /oneflow/build/tensorflow/src/tensorflow/tensorflow/compiler/xla/statusor.h:18,                 from /oneflow/build/tensorflow/src/tensorflow/tensorflow/compiler/xla/client/padding.h:23,                 from /oneflow/build/tensorflow/src/tensorflow/tensorflow/compiler/xla/client/xla_builder.h:28,                 from /oneflow/oneflow/xrt/xla/ops/op_context.h:28,                 from /oneflow/oneflow/xrt/xla/ops/fc_op.cpp:16:/oneflow/build/tensorflow/src/tensorflow/tensorflow/core/platform/default/logging.h:320:0: warning: "DCHECK_GT" redefined #define DCHECK_GT(x, y) _TF_DCHECK_NOP(x, y) In file included from /oneflow/oneflow/core/common/util.h:22:0,                 from /oneflow/oneflow/core/common/data_type.h:26,                 from /oneflow/oneflow/xrt/xla/ops/op_context.h:19,                 from /oneflow/oneflow/xrt/xla/ops/fc_op.cpp:16:/oneflow/third_party/glog/include/glog/logging.h:1061:0: note: this is the location of the previous definition #define DCHECK_GT(val1, val2) \ In file included from /oneflow/build/tensorflow/src/tensorflow/tensorflow/stream_executor/lib/status.h:24:0,                 from /oneflow/build/tensorflow/src/tensorflow/tensorflow/stream_executor/lib/statusor.h:72,                 from /oneflow/build/tensorflow/src/tensorflow/tensorflow/compiler/xla/statusor.h:19,                 from /oneflow/build/tensorflow/src/tensorflow/tensorflow/compiler/xla/client/padding.h:23,                 from /oneflow/build/tensorflow/src/tensorflow/tensorflow/compiler/xla/client/xla_builder.h:28,                 from /oneflow/oneflow/xrt/xla/ops/op_context.h:28,                 from /oneflow/oneflow/xrt/xla/ops/fc_op.cpp:16:/oneflow/build/tensorflow/src/tensorflow/tensorflow/stream_executor/platform/logging.h:24:0: warning: "PCHECK" redefined #define PCHECK(invocation) CHECK(invocation) In file included from /oneflow/oneflow/core/common/util.h:22:0,                 from /oneflow/oneflow/core/common/data_type.h:26,                 from /oneflow/oneflow/xrt/xla/ops/op_context.h:19,                 from /oneflow/oneflow/xrt/xla/ops/fc_op.cpp:16:/oneflow/third_party/glog/include/glog/logging.h:867:0: note: this is the location of the previous definition #define PCHECK(condition)  \ In file included from /oneflow/oneflow/xrt/tensorrt/ops/op_context.h:26:0,                 from /oneflow/oneflow/xrt/tensorrt/ops/batch_norm_op.cpp:16:/oneflow/oneflow/xrt/tensorrt/trt_builder.h:147:34: error: ���addInput��� function uses ���auto��� type specifier without trailing return type   auto add##Layer(Args &&... args) {                          \                                  ^/oneflow/oneflow/xrt/tensorrt/trt_builder.h:45:3: note: in expansion of macro ���TRT_BUILDER_ADD_LAYER���   __macro(Input);                       \   ^~~~~~~/oneflow/oneflow/xrt/tensorrt/trt_builder.h:151:3: note: in expansion of macro ���FOREACH_TENSORRT_LAYER���   FOREACH_TENSORRT_LAYER(TRT_BUILDER_ADD_LAYER);   ^/oneflow/oneflow/xrt/tensorrt/trt_builder.h:147:34: note: deduced return type only available with -std=c++14 or -std=gnu++14
```

my env:
os: centos 7.7
gcc : 7.5
cuda:10.1
tensorrt: 6.0.1

please let me know if you want other information. 
thanks again

**Comment by jackalcooper** [comment]
This is from OneFlow's [troubleshooting](https://github.com/Oneflow-Inc/oneflow/blob/develop/docs/source/troubleshooting.md)

> - Failed to compile because C++ 17 is enabled
    - In some cases, environment variable `CXXFLAGS` is not empty and contains `--std c++17`.
    - Check if it is empty by running `echo $CXXFLAGS` and clear it with `unset CXXFLAGS`.

Could you confirm newer version C++ is not enabled?

**Comment by jackalcooper** [comment]
I just built a OneFlow with XLA on CUDA 10.1 for you. Please download it from here: 
https://oneflow-public.oss-cn-beijing.aliyuncs.com/wip/oneflow_cu101_xla-0.1.8-cp36-cp36m-manylinux2014_x86_64.whl

**Comment by qianzhang613** [comment]
> I just built a OneFlow with XLA on CUDA 10.1 for you. Please download it from here:
> https://oneflow-public.oss-cn-beijing.aliyuncs.com/wip/oneflow_cu101_xla-0.1.8-cp36-cp36m-manylinux2014_x86_64.whl

thanks very much!!

**Comment by qianzhang613** [comment]
> I just built a OneFlow with XLA on CUDA 10.1 for you. Please download it from here:
> https://oneflow-public.oss-cn-beijing.aliyuncs.com/wip/oneflow_cu101_xla-0.1.8-cp36-cp36m-manylinux2014_x86_64.whl

the wheel file  name `manylinux2014 ` same have problem when install with pip3 :
```
ERROR: oneflow_cu101_xla-0.1.8-cp36-cp36m-manylinux2014_x86_64.whl is not a supported wheel on this platform.
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 326, in run
    self.name, wheel_cache
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 271, in populate_requirement_set
    requirement_set.add_requirement(req_to_add)
  File "/usr/local/lib/python3.6/site-packages/pip/_internal/req/req_set.py", line 91, in add_requirement
    wheel.filename
pip._internal.exceptions.InstallationError: oneflow_cu101_xla-0.1.8-cp36-cp36m-manylinux2014_x86_64.whl is not a supported wheel on this platform.
```
after change the wheel tag to `oneflow_cu101_xla-0.1.8-py3-none-any.whl `  it is able to install.

**Comment by daquexian** [comment]
> the wheel file name `manylinux2014 ` same have problem when install with pip3 :
> 

> after change the wheel tag to `oneflow_cu101_xla-0.1.8-py3-none-any.whl ` it is able to install.

Could you please upgrade your pip version and try again?

**Comment by qianzhang613** [comment]
> > the wheel file name `manylinux2014 ` same have problem when install with pip3 :
> 
> > after change the wheel tag to `oneflow_cu101_xla-0.1.8-py3-none-any.whl ` it is able to install.
> 
> Could you please upgrade your pip version and try again?

ok after update pip to 20.1 the wheel can install, thanks
