### ISSUE TITLE
BatchNorm layer: varaible 'BatchNorm-beta' already exists

### ISSUE THREAD

**Issue by zhen8838** [Oneflow-Inc/oneflow#3588]
Os : Ubuntu 18.04
oneflow version : `oneflow-cu102     0.1.10`
When use `batch_normalization` layer, got error :
```sh
(flow) ➜  gitio /home/zqh/workspace/miniconda3/envs/flow/bin/python /home/zqh/Documents/gitio/source/_posts/mindspore-tf/dcgan_flow.py
File mnist.npz already exist, path: ./mnist.npz
I0922 12:55:55.601016178   16647 ev_epoll_linux.c:82]        Use of signals is disabled. Epoll engine will not be used
Traceback (most recent call last):
  File "/home/zqh/Documents/gitio/source/_posts/mindspore-tf/dcgan_flow.py", line 104, in <module>
    np.random.randn(BATCH_SIZE, 100).astype('float32'))
  File "/home/zqh/workspace/miniconda3/envs/flow/lib/python3.7/site-packages/oneflow/python/framework/function_util.py", line 158, in Func
    return _RunLazyJob(sess, job_func, *args, **kwargs)
  File "/home/zqh/workspace/miniconda3/envs/flow/lib/python3.7/site-packages/oneflow/python/framework/function_util.py", line 218, in _RunLazyJob
    return session.TryInit().LazyRun(job_func, *args, **kwargs)
  File "/home/zqh/workspace/miniconda3/envs/flow/lib/python3.7/site-packages/oneflow/python/framework/session_util.py", line 204, in TryInit
    self.Init()
  File "/home/zqh/workspace/miniconda3/envs/flow/lib/python3.7/site-packages/oneflow/python/framework/session_util.py", line 216, in Init
    compiler.Compile(self, func_desc, self.config_proto)
  File "/home/zqh/workspace/miniconda3/envs/flow/lib/python3.7/site-packages/oneflow/python/framework/compiler.py", line 44, in Compile
    _CompileJob(function_desc)
  File "/home/zqh/workspace/miniconda3/envs/flow/lib/python3.7/site-packages/oneflow/python/framework/compiler.py", line 104, in _CompileJob
    ret = func(*inputs)
  File "/home/zqh/Documents/gitio/source/_posts/mindspore-tf/dcgan_flow.py", line 79, in train_job
    generated_images = generator(noise, training=True)
  File "/home/zqh/Documents/gitio/source/_posts/mindspore-tf/dcgan_flow.py", line 21, in generator
    x = fl.batch_normalization(x, 1, training=training)
  File "/home/zqh/workspace/miniconda3/envs/flow/lib/python3.7/site-packages/oneflow/python/ops/layers.py", line 893, in batch_normalization
    reuse=False,
  File "/home/zqh/workspace/miniconda3/envs/flow/lib/python3.7/site-packages/oneflow/python/ops/get_variable.py", line 73, in api_get_variable
    reuse=reuse,
  File "/home/zqh/workspace/miniconda3/envs/flow/lib/python3.7/site-packages/oneflow/python/ops/get_variable.py", line 165, in get_lazy_variable
    "when param reuse is False".format(name)
AssertionError: varaible 'BatchNorm-beta' already exists, getting the same variable is not allowed when param reuse is False
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/zqh/workspace/miniconda3/envs/flow/lib/python3.7/site-packages/oneflow/python/framework/session_context.py", line 42, in TryCloseDefaultSession
    _default_session.TryClose()
  File "/home/zqh/workspace/miniconda3/envs/flow/lib/python3.7/site-packages/oneflow/python/framework/session_util.py", line 226, in TryClose
    self.Close()
  File "/home/zqh/workspace/miniconda3/envs/flow/lib/python3.7/site-packages/oneflow/python/framework/session_util.py", line 231, in Close
    assert len(self.job_name2var_name2var_blob_) == 0
AssertionError
```
Code:
```python
import oneflow as flow
import oneflow.layers as fl
import oneflow.nn as fn
import oneflow.typing as tp
import numpy as np
import time

BATCH_SIZE = 250


def generator(noise, training):
  x = fl.dense(noise, 7 * 7 * 256, use_bias=False)
  x = flow.reshape(x, (-1, 256, 7, 7))
  x = fl.batch_normalization(x, 1, training=training)
  x = fn.leaky_relu(x)

  # assert model.output_shape == (None, 7, 7, 256)  # 注意：batch size 没有限制

  x = fl.conv2d(x, 128, (5, 5), strides=(1, 1), padding='SAME', use_bias=False)
  # assert model.output_shape == (None, 7, 7, 128)
  x = fl.batch_normalization(x, 1, training=training)
  x = fn.leaky_relu(x)

  x = fn.conv2d_transpose(x, 64, (5, 5), strides=(2, 2), padding='SAME', use_bias=False)
  # assert model.output_shape == (None, 14, 14, 64)
  x = fl.batch_normalization(x, 1, training=training)
  x = fn.leaky_relu(x)

  x = fn.conv2d_transpose(x, 1, (5, 5), strides=(2, 2),
                          padding='SAME', use_bias=False)
  x = flow.math.tanh(x)
  # assert model.output_shape == (None, 28, 28, 1)
  return x


def discriminator(images, training=True):
  x = fl.conv2d(images, 64, (5, 5), strides=(2, 2), padding='SAME')
  x = fn.leaky_relu(x)
  if training:
    x = fn.dropout(x, 0.3)

  x = fl.Conv2D(x, 128, (5, 5), strides=(2, 2), padding='SAME')
  x = fn.leaky_relu(x)
  if training:
    x = fn.dropout(x, 0.3)

  x = flow.reshape(x, (-1, 128 * 7 * 7))
  x = fl.dense(x, 1)
  return x


def discriminator_loss(real_output, fake_output):
  real_loss = flow.nn.sigmoid_cross_entropy_with_logits(flow.ones_like(real_output), real_output)
  fake_loss = flow.nn.sigmoid_cross_entropy_with_logits(flow.zeros_like(fake_output), fake_output)
  total_loss = real_loss + fake_loss
  return total_loss


def generator_loss(fake_output):
  return flow.nn.sigmoid_cross_entropy_with_logits(flow.ones_like(fake_output), fake_output)


def get_train_config():
  config: flow.FunctionConfig = flow.function_config()
  # 设置默认数据类型
  config.default_data_type(flow.float32)
  # 设置自动混合精度
  # config.enable_auto_mixed_precision(True)
  # config.set_enable_reused_mem()
  return config


@flow.global_function(type="train", function_config=get_train_config())
def train_job(
    images: tp.Numpy.Placeholder((BATCH_SIZE, 1, 28, 28), dtype=flow.float32),
    noise: tp.Numpy.Placeholder((BATCH_SIZE, 100), dtype=flow.float32),
) -> tp.Numpy:
  with flow.scope.placement("gpu", "0:0"):
    generated_images = generator(noise, training=True)
    real_output = discriminator(images, training=True)
    fake_output = discriminator(generated_images, training=True)

    gen_loss = generator_loss(fake_output)
    disc_loss = discriminator_loss(real_output, fake_output)

  g_lr = flow.optimizer.PiecewiseConstantScheduler([], [0.0001])
  flow.optimizer.Adam(g_lr).minimize(gen_loss)

  d_lr = flow.optimizer.PiecewiseConstantScheduler([], [0.0001])
  flow.optimizer.Adam(d_lr).minimize(disc_loss)
  return gen_loss, disc_loss


if __name__ == "__main__":
  ((train_images, train_labels),
   (test_images, test_labels)) = flow.data.load_mnist(BATCH_SIZE, BATCH_SIZE)

  for epoch in range(50):

    start = time.time()

    for i, (images, _) in enumerate(zip(train_images, train_labels)):
      gen_loss, disc_loss = train_job(images,
                                      np.random.randn(BATCH_SIZE, 100).astype('float32'))

    print('Time for epoch {} is {} sec'.format(epoch + 1, time.time() - start))

```

**Comment by Ldpe2G** [comment]
First, you must give each batch_normalization layer a unique name, for example:

```python
def generator(noise, training):
  # ......
  x = fl.batch_normalization(x, 1, training=training, name="bn1")
  # ......
  # assert model.output_shape == (None, 7, 7, 256)  # 注意：batch size 没有限制

  # ......
  x = fl.batch_normalization(x, 1, training=training, name="bn2")
  # ......

  # assert model.output_shape == (None, 14, 14, 64)
  x = fl.batch_normalization(x, 1, training=training, name="bn3")
  # ......
  return x
```

Second, your implementation of GAN algorithm is not right. The discriminator and generator should be updated alternatly not simutanoutly, so you should write two job functions. The minist GAN example has already be implemented in [OneFlow-Benchmark](https://github.com/Oneflow-Inc/OneFlow-Benchmark/tree/master/Generative).

**Comment by zhen8838** [comment]
Ok, Thanks for your example code.
