### ISSUE TITLE
i'm not in China and i can‘t download 0.2.0

### ISSUE THREAD

**Issue by 15168387900** [Oneflow-Inc/oneflow#3759]
Looking in links: https://oneflow-inc.github.io/nightly
Collecting oneflow_cu101
  Downloading https://oneflow-public.oss-cn-beijing.aliyuncs.com/nightly/oneflow_cu101-0.2.0-cp36-cp36m-manylinux2014_x86_64.whl (451.9MB)
     |▎                               | 4.1MB 9.0kB/s eta 13:49:59ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/urllib3/response.py", line 425, in _error_catcher
    yield
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/urllib3/response.py", line 507, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
    data = self.__fp.read(amt)
  File "/usr/lib/python3.6/http/client.py", line 463, in read
    n = self.readinto(b)
  File "/usr/lib/python3.6/http/client.py", line 507, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/cli/base_command.py", line 153, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/commands/install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/operations/prepare.py", line 194, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/download.py", line 465, in unpack_url
    progress_bar=progress_bar
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/download.py", line 316, in unpack_http_url
    progress_bar)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/download.py", line 551, in _download_http_url
    _download_url(resp, link, content_file, hashes, progress_bar)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/download.py", line 255, in _download_url
    consume(downloaded_chunks)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/misc.py", line 641, in consume
    deque(iterator, maxlen=0)
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/download.py", line 223, in written_chunks
    for chunk in chunks:
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/utils/ui.py", line 160, in iter
    for x in it:
  File "/usr/local/lib/python3.6/dist-packages/pip/_internal/download.py", line 212, in resp_read
    decode_content=False):
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/urllib3/response.py", line 564, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/urllib3/response.py", line 529, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/urllib3/response.py", line 430, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='oneflow-public.oss-cn-beijing.aliyuncs.com', port=443): Read timed out.

**Comment by jackalcooper** [comment]
I upload the package to Azure. You should install it without any trouble by running:
```
python3 -m pip install https://1fdevgroup06241201diag.blob.core.windows.net/rel/oneflow/oneflow_cu101-0.2.0-cp36-cp36m-manylinux2014_x86_64.whl
```
