### ISSUE TITLE
有遇到这种情况吗

### ISSUE THREAD

**Issue by liuao520** [Oneflow-Inc/oneflow#3846]
2020-11-16 13:39:53.614591: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
<oneflow.python.framework.remote_blob.LazyConsistentBlob object at 0x7f1a402acbe0>
Traceback (most recent call last):
  File "test01.py", line 30, in <module>
    outputs = test_job(images_in)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/function_util.py", line 158, in Func
    return _RunLazyJob(sess, job_func, *args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/function_util.py", line 218, in _RunLazyJob
    return session.TryInit().LazyRun(job_func, *args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_util.py", line 212, in TryInit
    self.Init()
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_util.py", line 225, in Init
    compiler.Compile(self, func_desc, self.config_proto)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 44, in Compile
    _CompileJob(function_desc)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 102, in _CompileJob
    ret = func(*inputs)
  File "test01.py", line 19, in test_job
    outpus = hrnet.call(images, training=True)
  File "/content/drive/My Drive/HRNet/core/hrnet.py", line 271, in call
    x = make_bottleneck_layer(x, filter_num=64, blocks=4, training=training)
  File "/content/drive/My Drive/HRNet/core/resnet_module.py", line 153, in make_bottleneck_layer
    x = BottleNeck('make_bottle0', inputs, filter_num, stride=stride, training=training)
  File "/content/drive/My Drive/HRNet/core/resnet_module.py", line 114, in BottleNeck
    residual = _conv2d_layer(name+str(time), inputs, filter_num * 4, (1, 1), stride, "SAME",use_bias=False)
  File "/content/drive/My Drive/HRNet/core/resnet_module.py", line 48, in _conv2d_layer
    input=input, filters=weight, strides=strides, padding=padding, dilations=1,data_format=data_format, name=name, groups=groups
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/ops/nn_ops.py", line 549, in conv2d
    name,
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/ops/nn_ops.py", line 576, in conv2d_op
    .Attr("groups", groups)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/ops/user_op_builder.py", line 145, in InferAndTryRun
    compile_context.CurJobAddOp(self.op_conf_)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compile_context.py", line 57, in CurJobAddOp
    return CurJobAddConsistentOp(op_conf, scope_symbol)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compile_context.py", line 67, in CurJobAddConsistentOp
    op_attr = c_api_util.CurJobBuildAndInferCtx_AddAndInferConsistentOp(op_conf)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/c_api_util.py", line 261, in CurJobBuildAndInferCtx_AddAndInferConsistentOp
    raise JobBuildAndInferError(error)
oneflow.python.framework.job_build_and_infer_error.JobBuildAndInferError: 

error msg: 

check_failed_error {
}

split hint only support 'S' or 'B', but get:5
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_context.py", line 42, in TryCloseDefaultSession
    _default_session.TryClose()
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_util.py", line 235, in TryClose
    self.Close()
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_util.py", line 240, in Close
    assert len(self.job_name2var_name2var_blob_) == 0
AssertionError

**Comment by doombeaker** [comment]
`split hint only support 'S' or 'B', but get:5`
和 SBP 设置似乎有关系。

请问你在跑的脚本是否可以上传

**Comment by Ldpe2G** [comment]
貌似在构建残差快内卷积层的时候崩了，试试设置 `flow.config.enable_debug_mode(True)` 看下更详细的报错信息

**Comment by chengtbf** [comment]
我猜测是你传入的tensor的name包含了意外的“:”字符。。。，比如`_conv2d_layer`的`groups`参数，你可以print一下看看是不是携带了意外的":"。可以换一个名字，用"_5"、".5"...，而不是用“:5”作为tensor name的结尾。

因为oneflow内部有个特殊的规则是tensor的name中最右边的":"是一个特殊的分隔符。
- 比如： tensor_name_xxx:S0，表示用户希望这个tensor是以SBP Parallel = Split(0)切分这个Tensor的。
- 又比如： tensor_name_xxx:B，表示用户希望这个tensor是以SBP Parallel = Broadcast 广播这个Tensor的。

见：
python端设置：
https://github.com/Oneflow-Inc/oneflow/blob/91396f09a871b9f2e09f9cf07779b38746d95ce4/oneflow/python/framework/blob_desc.py#L118
C++中的检查：
https://github.com/Oneflow-Inc/oneflow/blob/91396f09a871b9f2e09f9cf07779b38746d95ce4/oneflow/core/operator/operator.cpp#L711

**Comment by chengtbf** [comment]
@liuao520  我们之后会把这个特殊分隔符修改掉，不使用常见的":"，换成ASCII码表中前面无法被用户设置的特殊字符。

但目前你需要修改你的tensor name，去除掉其中的":"。

**Comment by liuao520** [comment]
@chengtbf 
谢谢您的解答   这个是我使用flow.nn.conv2d出现的问题，
在我尝试着使用flow.layers.conv2d时，groups设为了1，有这个报错，
2020-11-17 09:34:46.111989: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "test01.py", line 30, in <module>
    outputs = test_job(images_in)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/function_util.py", line 158, in Func
    return _RunLazyJob(sess, job_func, *args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/function_util.py", line 218, in _RunLazyJob
    return session.TryInit().LazyRun(job_func, *args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_util.py", line 212, in TryInit
    self.Init()
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_util.py", line 225, in Init
    compiler.Compile(self, func_desc, self.config_proto)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 44, in Compile
    _CompileJob(function_desc)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 102, in _CompileJob
    ret = func(*inputs)
  File "test01.py", line 19, in test_job
    outpus = hrnet.call(images, training=True)
  File "/content/drive/MyDrive/HRNet/core/hrnet.py", line 257, in call
    kernel_size=(3, 3), strides=2, padding="SAME", use_bias=False)
  File "/content/drive/MyDrive/HRNet/core/resnet_module.py", line 76, in _conv2d_layer
    trainable=True, name=name)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/ops/layers.py", line 455, in conv2d
    assert groups <= filters
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/blob_trait.py", line 96, in __ge__
    return oneflow.math.greater_equal(self, rhs)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/ops/math_ops.py", line 1211, in greater_equal
    return build_broadcast_binary_op("broadcast_greater_equal", x, y, name)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/ops/math_ops.py", line 427, in build_broadcast_binary_op
    .Input("y", [y])
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/ops/user_op_builder.py", line 254, in Input
    input_conf[input_name].s.append(input_blob.unique_name)
AttributeError: 'int' object has no attribute 'unique_name'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_context.py", line 42, in TryCloseDefaultSession
    _default_session.TryClose()
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_util.py", line 235, in TryClose
    self.Close()
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_util.py", line 240, in Close
    assert len(self.job_name2var_name2var_blob_) == 0
AssertionError

然后，还有name的命名问题，加了时间戳，都重名，有解决办法吗

**Comment by chengtbf** [comment]
> File "/content/drive/MyDrive/HRNet/core/resnet_module.py", line 76, in _conv2d_layer
> trainable=True, name=name)
> File "/root/.local/lib/python3.6/site-packages/oneflow/python/ops/layers.py", line 455, in conv2d
> assert groups <= filters

你这里的filters是不是用错了，被当成了tensor进行推导了。我们的conv2d的接口要求filters必须是int类型。
https://github.com/Oneflow-Inc/oneflow/blob/8e7c99a581c72d5476b3db2cd7b4a1072becaec7/oneflow/python/ops/layers.py#L383


> 然后，还有name的命名问题，加了时间戳，都重名，有解决办法吗

“加了时间戳，都重名”是什么意思？我没太理解。。。时间戳可以转换成不带`:`的格式吗。

**Comment by doombeaker** [comment]
>然后，还有name的命名问题，加了时间戳，都重名，有解决办法吗

如果仅仅是为了取唯一的名字，可以用 `import oneflow.python.framework.id_util as id_util`，参考 https://github.com/Oneflow-Inc/oneflow/blob/8e7c99a581c72d5476b3db2cd7b4a1072becaec7/oneflow/python/ops/array_ops.py#L146

另外，@chengtbf 的意思是，正是因为时间戳里有":" 这种特殊字符串，OneFlow才会出一些问题，所以你得避免在name中有特殊字符串。
