### ISSUE TITLE
mseloss

### ISSUE THREAD

**Issue by 316070411773** [Oneflow-Inc/oneflow#3895]
没有看到mesloss，自己实现以下  有以下问题
 for i in range(num_of_joints):
            heatmap_pred = flow.squeeze(heatmap_pred_list[i])
            heatmap_gt = flow.squeeze(heatmap_gt_list[i])
            temp = flow.math.square(heatmap_pred * target_weight[:, i] - heatmap_gt * target_weight[:, i])
            loss += 0.5 * flow.math.reduce_mean(temp, axis=1, keepdims=True)
            # loss += 0.5 * mse_(y_true=heatmap_pred * target_weight[:, i],
            #                        y_pred=heatmap_gt * target_weight[:, i])
        return loss / num_of_joints

问题出现
2020-11-23 06:57:55.621911: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
17
Traceback (most recent call last):
  File "loss_test.py", line 59, in <module>
    outputs = test_job(images,target,target_weight,y_pred)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/function_util.py", line 158, in Func
    return _RunLazyJob(sess, job_func, *args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/function_util.py", line 218, in _RunLazyJob
    return session.TryInit().LazyRun(job_func, *args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_util.py", line 212, in TryInit
    self.Init()
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_util.py", line 225, in Init
    compiler.Compile(self, func_desc, self.config_proto)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 44, in Compile
    _CompileJob(function_desc)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 102, in _CompileJob
    ret = func(*inputs)
  File "loss_test.py", line 29, in test_job
    loss_metric = loss.call(y_pred, target, target_weight)
  File "/content/drive/MyDrive/mycode/core/loss.py", line 33, in call
    temp = flow.math.square(heatmap_pred * target_weight[:, i] - heatmap_gt * target_weight[:, i])
TypeError: 'LazyConsistentBlob' object is not subscriptable

**Comment by MARD1NO** [comment]
您好，静态图下我们暂时不支持切片操作，我们后续会支持，如果您需要使用切片操作，可以考虑使用 
[slice](https://oneflow-api.readthedocs.io/en/latest/oneflow.html?highlight=slice#oneflow.slice)

[slice_v2](https://oneflow-api.readthedocs.io/en/latest/oneflow.html?highlight=slice#oneflow.slice_v2)

MSELoss 正在开发，具体实现可参考 #3798
