### ISSUE TITLE
TypeError: Array must be contiguous (C_ or F_).  A non-contiguous array was given

### ISSUE THREAD

**Issue by 15168387900** [Oneflow-Inc/oneflow#3921]
What should I do in this situation?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/oneflow/python/framework/job_instance.py", line 119, in PushBlob
    self.push_cb_(ofblob.OfBlob(of_blob_ptr))
  File "/usr/local/lib/python3.6/dist-packages/oneflow/python/framework/input_blob_def.py", line 333, in Copy
    ofblob.CopyFromNdarray(copied)
  File "/usr/local/lib/python3.6/dist-packages/oneflow/python/framework/ofblob.py", line 109, in CopyFromNdarray
    return self._CopyBodyFromNdarray(src_ndarray)
  File "/usr/local/lib/python3.6/dist-packages/oneflow/python/framework/ofblob.py", line 117, in _CopyBodyFromNdarray
    copy_method(self.of_blob_ptr_, src_ndarray)
TypeError: Array must be contiguous (C_ or F_).  A non-contiguous array was given

F1126 09:11:44.629273  2668 oneflow_internalPYTHON_wrap.cpp:4717] Swig::DirectorMethodException
*** Check failure stack trace: ***
    @     0x7fcb47c6c3fd  google::LogMessage::Fail()
    @     0x7fcb47c6dc4a  google::LogMessage::SendToLog()
    @     0x7fcb47c6becd  google::LogMessage::Flush()
    @     0x7fcb47c6f079  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fcb464449d0  SwigDirector_ForeignJobInstance::PushBlob()
    @     0x7fcb468b5099  oneflow::ForeignInputKernel::ForwardDataContent()
    @     0x7fcb468b58a0  oneflow::ForeignInputKernel::Forward()
    @     0x7fcb468d60e7  oneflow::Kernel::Launch()
    @     0x7fcb46477315  oneflow::Actor::AsyncLaunchKernel()
    @     0x7fcb4648f869  oneflow::NormalForwardCompActor::Act()
    @     0x7fcb464795f2  oneflow::Actor::TryLogActEvent()
    @     0x7fcb4647b076  oneflow::Actor::ActUntilFail()
    @     0x7fcb4647bb15  oneflow::Actor::HandlerNormal()
    @     0x7fcb46b1d019  oneflow::Thread::PollMsgChannel()
    @     0x7fcb46b1adfa  (unknown)
    @     0x7fcb70eb36df  (unknown)
    @     0x7fcb71f956db  start_thread
    @     0x7fcb722ce71f  clone
```

Below is some of my code:

```
import os
from imageio import imread
from PIL import Image
import numpy as np


def RandomFlip(sample):
    if (np.random.randint(0, 2) == 1):
        sample['LR'] = np.fliplr(sample['LR']).copy()
        sample['HR'] = np.fliplr(sample['HR']).copy()
        sample['LR_sr'] = np.fliplr(sample['LR_sr']).copy()
    if (np.random.randint(0, 2) == 1):
        sample['Ref'] = np.fliplr(sample['Ref']).copy()
        sample['Ref_sr'] = np.fliplr(sample['Ref_sr']).copy()
    if (np.random.randint(0, 2) == 1):
        sample['LR'] = np.flipud(sample['LR']).copy()
        sample['HR'] = np.flipud(sample['HR']).copy()
        sample['LR_sr'] = np.flipud(sample['LR_sr']).copy()
    if (np.random.randint(0, 2) == 1):
        sample['Ref'] = np.flipud(sample['Ref']).copy()
        sample['Ref_sr'] = np.flipud(sample['Ref_sr']).copy()
    return sample


def RandomRotate(sample):
    k1 = np.random.randint(0, 4)
    sample['LR'] = np.rot90(sample['LR'], k1).copy()
    sample['HR'] = np.rot90(sample['HR'], k1).copy()
    sample['LR_sr'] = np.rot90(sample['LR_sr'], k1).copy()
    k2 = np.random.randint(0, 4)
    sample['Ref'] = np.rot90(sample['Ref'], k2).copy()
    sample['Ref_sr'] = np.rot90(sample['Ref_sr'], k2).copy()
    return sample


def Transpose(sample):
    LR, LR_sr, HR, Ref, Ref_sr = sample['LR'], sample['LR_sr'], sample['HR'], sample['Ref'], sample['Ref_sr']
    LR = LR.transpose((2,0,1))
    LR_sr = LR_sr.transpose((2,0,1))
    HR = HR.transpose((2,0,1))
    Ref = Ref.transpose((2,0,1))
    Ref_sr = Ref_sr.transpose((2,0,1))
    return {'LR': LR,
            'LR_sr': LR_sr,
            'HR': HR,
            'Ref': Ref,
            'Ref_sr': Ref_sr}


class TrainSet(object):
    def __init__(self, args):
        self.input_list = sorted([os.path.join(args.data_dir, 'train/input', name) for name in
            os.listdir(os.path.join(args.data_dir, 'train/input'))])
        self.ref_list = sorted([os.path.join(args.data_dir, 'train/ref', name) for name in
            os.listdir(os.path.join(args.data_dir, 'train/ref'))])

    def __len__(self):
        return len(self.input_list)

    def __getitem__(self, idx):
        ### HR
        HR = imread(self.input_list[idx])
        h, w = HR.shape[:2]
        # HR = HR[:h//4*4, :w//4*4, :]

        ### LR and LR_sr
        LR = np.array(Image.fromarray(HR).resize((w // 4, h // 4), Image.BICUBIC))
        LR_sr = np.array(Image.fromarray(LR).resize((w, h), Image.BICUBIC))

        ### Ref and Ref_sr
        Ref_sub = imread(self.ref_list[idx])
        h2, w2 = Ref_sub.shape[:2]
        Ref_sr_sub = np.array(Image.fromarray(Ref_sub).resize((w2 // 4, h2 // 4), Image.BICUBIC))
        Ref_sr_sub = np.array(Image.fromarray(Ref_sr_sub).resize((w2, h2), Image.BICUBIC))

        ### complete ref and ref_sr to the same size, to use batch_size > 1
        Ref = np.zeros((160, 160, 3))
        Ref_sr = np.zeros((160, 160, 3))
        Ref[:h2, :w2, :] = Ref_sub
        Ref_sr[:h2, :w2, :] = Ref_sr_sub

        ### change type
        LR = LR.astype(np.float32)
        LR_sr = LR_sr.astype(np.float32)
        HR = HR.astype(np.float32)
        Ref = Ref.astype(np.float32)
        Ref_sr = Ref_sr.astype(np.float32)

        ### rgb range to [-1, 1]
        LR = LR / 127.5 - 1.
        LR_sr = LR_sr / 127.5 - 1.
        HR = HR / 127.5 - 1.
        Ref = Ref / 127.5 - 1.
        Ref_sr = Ref_sr / 127.5 - 1.

        sample = {'LR': LR,
                  'LR_sr': LR_sr,
                  'HR': HR,
                  'Ref': Ref,
                  'Ref_sr': Ref_sr}

        sample = RandomFlip(sample)
        sample = RandomRotate(sample)
        sample = Transpose(sample)
        return sample
```

```
@flow.global_function(type="train", function_config=func_config)
        def train_lte(
            input: tp.Numpy.Placeholder((self.batch_size, 3, 160, 160))
        ) -> Tuple[tp.Numpy, tp.Numpy, tp.Numpy]:
            print(1)
            x_lv1, x_lv2, x_lv3 = self.LTE(input)
            x = flow.get_variable(
                shape=(9, 64, 160, 160),
                name="x_var",
                dtype=flow.float32,
                initializer=flow.random_normal_initializer()
            )
            loss = x_lv1 + x
            flow.optimizer.Adam(lr_scheduler, 0.9, 0.999).minimize(loss)
            return x_lv1, x_lv2, x_lv3
```

```
batch_num = len(data_train) // self.batch_size
        print("****************** start training *****************")
        for epoch_idx in range(epochs):
            start = time.time()
            print("****************** train  *****************")
            for batch_idx in range(batch_num):
                lr, lr_sr, hr, ref, ref_sr = [], [], [], [], []
                for idx in range(self.batch_size):
                    sample = data_train[batch_idx * self.batch_size + idx]
                    lr.append(sample['LR'][np.newaxis, :])
                    lr_sr.append(sample['LR_sr'][np.newaxis, :])
                    hr.append(sample['HR'][np.newaxis, :])
                    ref.append(sample['Ref'][np.newaxis, :])
                    ref_sr.append(sample['Ref_sr'][np.newaxis, :])
                lr = np.concatenate(lr, axis=0)
                lr_sr = np.concatenate(lr_sr, axis=0)
                hr = np.concatenate(hr, axis=0)
                ref = np.concatenate(ref, axis=0)
                ref_sr = np.concatenate(ref_sr, axis=0)

                print(lr_sr.shape)
                _, _, lrsr_lv3 = train_lte((lr_sr + 1.) / 2.)
```

The error occurred when `_, _, lrsr_lv3 = train_lte((lr_sr + 1.) / 2.)`
The matter is that How to make `lr_sr`  contiguous?

**Comment by leaves-zwx** [comment]
You could call [`numpy. ascontiguousarray`](https://numpy.org/doc/stable/reference/generated/numpy.ascontiguousarray.html?highlight=ascontiguousarray) to convert `lr_sr` to be contiguous. 

Calling `lr_sr.flags` could help you to detect if the array is contiguous, output as below:

```
  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
```

`C_CONTIGUOUS : False` and `F_CONTIGUOUS : False` means that your array is neither row-major contiguous (c_contiguous) nor col-major contiguous (f_contiguous).
