### ISSUE TITLE
assert len(self.job_name2var_name2var_blob_) == 0

### ISSUE THREAD

**Issue by 15168387900** [Oneflow-Inc/oneflow#3928]
I get this error during testing my code:
```
Traceback (most recent call last):
  File "of_ttsr.py", line 274, in <module>
    ttsr.train(epochs=args.epochs)
  File "of_ttsr.py", line 212, in train
    check_point.init()
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_context.py", line 49, in Func
    GetDefaultSession().TryInit()
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_util.py", line 186, in TryInit
    self.Init()
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_util.py", line 218, in Init
    compiler.Compile(self, func_desc, self.config_proto)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 47, in Compile
    c_api_util.CurJobBuildAndInferCtx_Complete()
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/c_api_util.py", line 197, in CurJobBuildAndInferCtx_Complete
    raise JobBuildAndInferError(error)
oneflow.python.framework.job_build_and_infer_error.JobBuildAndInferError: 

error msg: 


check_failed_error {
}


Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_context.py", line 42, in TryCloseDefaultSession
    _default_session.TryClose()
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_util.py", line 241, in TryClose
    self.Close()
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_util.py", line 246, in Close
    assert len(self.job_name2var_name2var_blob_) == 0
AssertionError
```
And I found that the error is in the following code:
(Because the `init` succeeded after deleting this code)
```
@flow.global_function(type="train", function_config=func_config)
def train_searchtransfer(
    lrsr_lv3_unfold: tp.Numpy.Placeholder((self.batch_size, 2304, 1600)),
    refsr_lv3_unfold: tp.Numpy.Placeholder((self.batch_size, 2304, 1600)),
    ref_lv3_unfold: tp.Numpy.Placeholder((self.batch_size, 2304, 1600)),
    ref_lv2_unfold: tp.Numpy.Placeholder((self.batch_size, 4608, 1600)),
    ref_lv1_unfold: tp.Numpy.Placeholder((self.batch_size, 9216, 1600))
) -> Tuple[tp.Numpy, tp.Numpy, tp.Numpy, tp.Numpy]:
    refsr_lv3_unfold = flow.transpose(refsr_lv3_unfold, perm=[0, 2, 1])

    refsr_lv3_unfold = flow.math.l2_normalize(refsr_lv3_unfold, axis=2)  # [N, Hr*Wr, C*k*k]
    lrsr_lv3_unfold = flow.math.l2_normalize(lrsr_lv3_unfold, axis=1)  # [N, C*k*k, H*W]

    R_lv3 = flow.matmul(refsr_lv3_unfold, lrsr_lv3_unfold)  # [N, Hr*Wr, H*W]
    R_lv3_star = flow.math.reduce_max(R_lv3, axis=1)  # [N, H*W]
    R_lv3_star_arg = flow.math.argmax(R_lv3, axis=1)  # [N, H*W]

    T_lv3_unfold = self.bis(ref_lv3_unfold, R_lv3_star_arg)
    T_lv2_unfold = self.bis(ref_lv2_unfold, R_lv3_star_arg)
    T_lv1_unfold = self.bis(ref_lv1_unfold, R_lv3_star_arg)

    return R_lv3_star, T_lv3_unfold, T_lv2_unfold, T_lv1_unfold
```
```
def bis(self, input, index):
    # batch index select
    # input: [N, ?, ?, ...]
    # dim: scalar > 0
    # index: [N, idx]
    views = [input.shape[0]] + [1 if i != 2 else -1 for i in range(1, len(input.shape))]
    index = flow.reshape(index, shape=views)
    index_list = []
    for i in range(input.shape[1]):
        index_list.append(index)
    index = flow.concat(inputs=index_list, axis=1)
    return flow.dim_gather(input, 2, index)
```
I tried to give each op a name but it still got the error.

**Comment by 15168387900** [comment]
> I get this error during testing my code:
> 
> ```
> Traceback (most recent call last):
>   File "of_ttsr.py", line 274, in <module>
>     ttsr.train(epochs=args.epochs)
>   File "of_ttsr.py", line 212, in train
>     check_point.init()
>   File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_context.py", line 49, in Func
>     GetDefaultSession().TryInit()
>   File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_util.py", line 186, in TryInit
>     self.Init()
>   File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_util.py", line 218, in Init
>     compiler.Compile(self, func_desc, self.config_proto)
>   File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/compiler.py", line 47, in Compile
>     c_api_util.CurJobBuildAndInferCtx_Complete()
>   File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/c_api_util.py", line 197, in CurJobBuildAndInferCtx_Complete
>     raise JobBuildAndInferError(error)
> oneflow.python.framework.job_build_and_infer_error.JobBuildAndInferError: 
> 
> error msg: 
> 
> 
> check_failed_error {
> }
> 
> 
> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
>   File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_context.py", line 42, in TryCloseDefaultSession
>     _default_session.TryClose()
>   File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_util.py", line 241, in TryClose
>     self.Close()
>   File "/root/.local/lib/python3.6/site-packages/oneflow/python/framework/session_util.py", line 246, in Close
>     assert len(self.job_name2var_name2var_blob_) == 0
> AssertionError
> ```
> 
> And I found that the error is in the following code:
> (Because the `init` succeeded after deleting this code)
> 
> ```
> @flow.global_function(type="train", function_config=func_config)
> def train_searchtransfer(
>     lrsr_lv3_unfold: tp.Numpy.Placeholder((self.batch_size, 2304, 1600)),
>     refsr_lv3_unfold: tp.Numpy.Placeholder((self.batch_size, 2304, 1600)),
>     ref_lv3_unfold: tp.Numpy.Placeholder((self.batch_size, 2304, 1600)),
>     ref_lv2_unfold: tp.Numpy.Placeholder((self.batch_size, 4608, 1600)),
>     ref_lv1_unfold: tp.Numpy.Placeholder((self.batch_size, 9216, 1600))
> ) -> Tuple[tp.Numpy, tp.Numpy, tp.Numpy, tp.Numpy]:
>     refsr_lv3_unfold = flow.transpose(refsr_lv3_unfold, perm=[0, 2, 1])
> 
>     refsr_lv3_unfold = flow.math.l2_normalize(refsr_lv3_unfold, axis=2)  # [N, Hr*Wr, C*k*k]
>     lrsr_lv3_unfold = flow.math.l2_normalize(lrsr_lv3_unfold, axis=1)  # [N, C*k*k, H*W]
> 
>     R_lv3 = flow.matmul(refsr_lv3_unfold, lrsr_lv3_unfold)  # [N, Hr*Wr, H*W]
>     R_lv3_star = flow.math.reduce_max(R_lv3, axis=1)  # [N, H*W]
>     R_lv3_star_arg = flow.math.argmax(R_lv3, axis=1)  # [N, H*W]
> 
>     T_lv3_unfold = self.bis(ref_lv3_unfold, R_lv3_star_arg)
>     T_lv2_unfold = self.bis(ref_lv2_unfold, R_lv3_star_arg)
>     T_lv1_unfold = self.bis(ref_lv1_unfold, R_lv3_star_arg)
> 
>     return R_lv3_star, T_lv3_unfold, T_lv2_unfold, T_lv1_unfold
> ```
> 
> ```
> def bis(self, input, index):
>     # batch index select
>     # input: [N, ?, ?, ...]
>     # dim: scalar > 0
>     # index: [N, idx]
>     views = [input.shape[0]] + [1 if i != 2 else -1 for i in range(1, len(input.shape))]
>     index = flow.reshape(index, shape=views)
>     index_list = []
>     for i in range(input.shape[1]):
>         index_list.append(index)
>     index = flow.concat(inputs=index_list, axis=1)
>     return flow.dim_gather(input, 2, index)
> ```
> 
> I tried to give each op a name but it still got the error.

I changed the `type` of `flow.global_function` to `"predict"`
Then no error was reported : )

**Comment by Ldpe2G** [comment]
@15168387900 try add the following to your python script
```python
flow.config.enable_debug_mode(True)
```
then you willl get more detailed error messages.
