### ISSUE TITLE
stack_conf

### ISSUE THREAD

**Issue by liuao520** [Oneflow-Inc/oneflow#3941]
首先  请问类似tf.convert_to_tensor的算子  有相关转化吗  比如接受一些value如numpy arrays, Python lists,,转化成blob
其次遇到这个错误
Traceback (most recent call last):
  File "train.py", line 78, in <module>
    images, target, target_weight = gt.get_ground_truth()
  File "/content/mycode/core/make_ground_truth.py", line 49, in get_ground_truth
    batch_images_tensor = flow.stack(batch_images, axis=0)    # (batch_size, image_height, image_width, channels)
  File "/root/.local/lib/python3.6/site-packages/oneflow/python/ops/array_ops.py", line 708, in stack
    getattr(op_conf.stack_conf, "in").extend([input.unique_name for input in inputs])
AttributeError: stack_conf

**Comment by liuao520** [comment]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 325.0, 160.0, 2.0, 398.0, 177.0, 2.0, 0.0, 0.0, 0.0, 437.0, 238.0, 2.0, 0.0, 0.0, 0.0, 477.0, 270.0, 2.0, 287.0, 255.0, 1.0, 339.0, 267.0, 2.0, 0.0, 0.0, 0.0, 423.0, 314.0, 2.0, 0.0, 0.0, 0.0, 355.0, 367.0, 2.0]
例如以上是我当前从文件中读取的一系列字符串(keypoints)
原本 keypoints_tensor = tf.convert_to_tensor(value=keypoints, dtype=tf.dtypes.float32)执行这个语句变成一个keypoints_tensor
我试着用keypoints_tensor = flow.tensor_buffer_to_tensor(keypoints, flow.float32)
但报错

Traceback (most recent call last):
  File "train.py", line 79, in <module>
    images, target, target_weight = gt.get_ground_truth()
  File "/content/mycode/core/make_ground_truth.py", line 42, in get_ground_truth
    image, keypoints_3d, keypoints_3d_exist = self.__get_one_human_instance_keypoints(line_keypoints=item)
  File "/content/mycode/core/make_ground_truth.py", line 63, in __get_one_human_instance_keypoints
    keypoints_tensor = flow.tensor_buffer_to_tensor(keypoints, flow.float32)
TypeError: tensor_buffer_to_tensor() missing 1 required positional argument: 'instance_shape'
