### ISSUE TITLE
KeyError: 'eps' when print(layernorm)

### ISSUE THREAD

**Issue by L1aoXingyu** [Oneflow-Inc/oneflow#6106]
```
import oneflow.nn as nn
layer = nn.LayerNorm(32)
print(layer)
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspace/oneflow/python/oneflow/nn/module.py", line 572, in __repr__
    extra_repr = self.extra_repr()
  File "/workspace/oneflow/python/oneflow/nn/modules/normalization.py", line 317, in extra_repr
    **self.__dict__
KeyError: 'eps'
```

**Comment by MARD1NO** [comment]
```python
// 233行
self.epsilon = eps -> self.eps = eps
```
