### ISSUE TITLE
Eager Consistent BUG of Optimizer zero grad 

### ISSUE THREAD

**Issue by chengtbf** [Oneflow-Inc/oneflow#6176]
单机单卡， Eager Consistent 执行 Optimizer 时报错：

```console
======================================================================
ERROR: test_scalar_consistent_train_graph_gpu (__main__.TestScalarGraph)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_graph_scalar.py", line 167, in test_scalar_consistent_train_graph_gpu
    _test_scalar_consistent_train_graph(test_case, flow.placement("cuda", { 0:[0]}))
  File "test_graph_scalar.py", line 118, in _test_scalar_consistent_train_graph
    of_sgd.zero_grad()
  File "/home/chengcheng/oneflow/python/oneflow/nn/optimizer/optimizer.py", line 248, in zero_grad
    param.grad.zeros_()
oneflow._oneflow_internal.exception.RuntimeException: 
  File "/home/chengcheng/oneflow/oneflow/api/python/utils/tensor_utils.cpp", line 33, in EagerMirroredTensorZeros
    t->AsMirroredTensor()
  File "/home/chengcheng/oneflow/oneflow/core/framework/tensor.h", line 539, in AsMirroredTensor
    RuntimeError : This is a oneflow bug, please submit issues in 'https://github.com/Oneflow-Inc/oneflow/issues' include the log information of the error, the minimum reproduction code, and the system information.

----------------------------------------------------------------------
Ran 6 tests in 1.778s

FAILED (errors=2)
``` 

- oneflow 版本： https://github.com/Oneflow-Inc/oneflow/commit/332c05c54b5ca69681e48eb35d55a769bc0d2822

最小可复现代码：

```python
import os
import unittest
import numpy as np

import oneflow as flow
import oneflow.unittest

def _test_scalar_consistent_train_graph(test_case, placement):
    sbp_b = flow.sbp.broadcast

    class MyModule(flow.nn.Module):
        def __init__(self):
            super().__init__()
            self.weight = flow.nn.Parameter(flow.tensor(5.0))

        def forward(self, x):
            return x * self.weight + 1.0

    my_module = MyModule()
    my_module.to_consistent(placement=placement, sbp=sbp_b)

    of_sgd = flow.optim.SGD(my_module.parameters(), lr=0.001, momentum=0.9)
    eager_out_list = []
    for i in range(3):
        x = flow.tensor(i * 1.0, requires_grad=False)
        x = x.to_consistent(placement=placement, sbp=sbp_b)
        print("x: ", x)
        of_eager_out = my_module(x)
        print("of_eager_out: ", of_eager_out)
        of_eager_out.backward()
        of_sgd.step()
        of_sgd.zero_grad()
        eager_out_list.append(of_eager_out)
        print("of_eager_weight: ", my_module.weight)

class TestScalarGraph(oneflow.unittest.TestCase):
    def test_scalar_consistent_train_graph_gpu(test_case):
        _test_scalar_consistent_train_graph(test_case, flow.placement("cuda",  { 0:[0]}))

if __name__ == "__main__":
    unittest.main()
```

**Comment by wyg1997** [comment]
Fix in #6202
