### ISSUE TITLE
ConsistentTensor.numpy() ERROR

### ISSUE THREAD

**Issue by chengtbf** [Oneflow-Inc/oneflow#6178]
Consistent  支持了 String 方法，但是没有支持 .numpy() 方法，可以 print，但是不能取到 numpy 值，这个应该是不合理的？

- oneflow 版本： https://github.com/Oneflow-Inc/oneflow/commit/332c05c54b5ca69681e48eb35d55a769bc0d2822

最小可复现代码：

```console
chengcheng@oneflow-21:~/debug/graph $ python3
Python 3.8.5 (default, May 27 2021, 13:30:53) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import oneflow as flow
>>> x = flow.tensor(5.0)
>>> x = x.to_consistent(placement=flow.placement("cuda", {0:[0]}), sbp=flow.sbp.broadcast)
>>> x
tensor(5.,
       placement=oneflow.placement(device_type="cuda", machine_device_ids={0 : [0]}, hierarchy=(1,)),
       sbp=(oneflow.sbp.broadcast,), dtype=oneflow.float32)
>>> print(x)
tensor(5.,
       placement=oneflow.placement(device_type="cuda", machine_device_ids={0 : [0]}, hierarchy=(1,)),
       sbp=(oneflow.sbp.broadcast,), dtype=oneflow.float32)
>>> x.numpy()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chengcheng/oneflow/python/oneflow/framework/tensor.py", line 50, in _tensor_numpy
    copy_to_numpy(ndarray)
oneflow._oneflow_internal.exception.RuntimeException: 
  File "/home/chengcheng/oneflow/oneflow/api/python/utils/tensor_utils.h", line 43, in CopyBetweenMirroredTensorAndNumpy
    t->AsMirroredTensor()
  File "/home/chengcheng/oneflow/oneflow/core/framework/tensor.h", line 539, in AsMirroredTensor
    RuntimeError : This is a oneflow bug, please submit issues in 'https://github.com/Oneflow-Inc/oneflow/issues' include the log information of the error, the minimum reproduction code, and the system information.
>>> 
```

**Comment by chengtbf** [comment]
ConsistentTensor.numpy() 的语义是取到所有数据。会有 to Broadcast 操作。
