### ISSUE TITLE
TensorMeta 的 string 方法

### ISSUE THREAD

**Issue by chengtbf** [Oneflow-Inc/oneflow#6242]
有时候仅需要检查 Tensor 的 Meta 信息是否合法/一致，这时候报错信息就希望将 TensorMeta 信息打印出来（C++里）。 希望提供 TensorMeta 的 DebugString 或者 ToString 方法 （最好是 基类提供，子类重载补充实现）。

代码位置：

https://github.com/Oneflow-Inc/oneflow/blob/788bd1a5920c609f8c5cd60f79f071ebec17918e/oneflow/core/framework/tensor_meta.h#L35

**Comment by chengtbf** [comment]
tensor meta 没有被很好的维护。 直接取 tensor->tensor_meta() 既能 cast 成 mirrored meta，也能 cast 成 Consistent meta

```console
chengcheng@oneflow-21:~/debug $ python3 test_1d_simple.py 
i =  0  x.shape= oneflow.Size([16, 1, 28, 28])
graph input x.shape= oneflow.Size([16, 1, 28, 28])
[ERROR](GRAPH:PipelineGraph_0:PipelineGraph) build graph got error: <class 'oneflow._oneflow_internal.exception.CheckFailedException'> 
  File "/home/chengcheng/oneflow/oneflow/core/framework/nn_graph.cpp", line 126, in RegisterInputOpNamesAndTensors
    TensorMetaToString(input_tensor->tensor_meta())
  File "/home/chengcheng/oneflow/oneflow/core/framework/nn_graph.cpp", line 60, in TensorMetaToString
    Check failed: !(mirrored_meta && consistent_meta)
Traceback (most recent call last):
  File "test_1d_simple.py", line 81, in <module>
    loss = graph_pipeline(x)
  File "/home/chengcheng/oneflow/python/oneflow/nn/graph/graph.py", line 249, in __call__
    self._compile(*args)
  File "/home/chengcheng/oneflow/python/oneflow/nn/graph/graph.py", line 411, in _compile
    eager_outputs = self._build_graph(*args)
  File "/home/chengcheng/oneflow/python/oneflow/nn/graph/graph.py", line 495, in _build_graph
    self._c_nn_graph.register_input_op_names_and_tensors(
oneflow._oneflow_internal.exception.CheckFailedException: 
  File "/home/chengcheng/oneflow/oneflow/core/framework/nn_graph.cpp", line 126, in RegisterInputOpNamesAndTensors
    TensorMetaToString(input_tensor->tensor_meta())
  File "/home/chengcheng/oneflow/oneflow/core/framework/nn_graph.cpp", line 60, in TensorMetaToString
    Check failed: !(mirrored_meta && consistent_meta)

```

**Comment by liufengwei0103** [comment]
tensor->tensor_meta() 既能 cast 成 mirrored meta，也能 cast 成 Consistent meta。没明白，我试了一下不行啊。从逻辑上看着也不行。有复现代码吗? @chengtbf

**Comment by liufengwei0103** [comment]
> tensor->tensor_meta() 既能 cast 成 mirrored meta，也能 cast 成 Consistent meta。没明白，我试了一下不行啊。从逻辑上看着也不行。有复现代码吗? @chengtbf

**Comment by liufengwei0103** [comment]
点错了，close了

**Comment by chengtbf** [comment]
https://github.com/Oneflow-Inc/oneflow/pull/6243/commits/632bd62ef8cc84246a7a4b20ebc3fb753ed38dcd#r714656161

看一下这里，这分支的这个 commit 可以复现。

**Comment by chengtbf** [comment]
另外，我其实也希望有 TensorMeta 的 Symbol 方法，可以直接判断一个 Tensor 的 TensorMeta 是否和之前保存的一致。而直接取 Tensor::tensor_meta()  的 结果好像只能保存基类信息（shape dtype），但是没有保存子类的 （device/ placement + sbp） 信息？

**Comment by liufengwei0103** [comment]
该feature不再需要。
