### ISSUE TITLE
flow.reshape support Scalar

### ISSUE THREAD

**Issue by chengtbf** [Oneflow-Inc/oneflow#6255]
- commit : https://github.com/Oneflow-Inc/oneflow/commit/8f67c6bdc59c0575f8aabda5a998a02bf7747c3f

reshape 检查了 shape NumAxes() > 0 导致无法处理 Scalar 情形

另外我记得之前有地方用到 Reshape 处理 Scalar ，临时用 expend dims 之类的操作绕过去了？  @MARD1NO 现在可以把那个限制去掉了。

### master 报错：

```console
chengcheng@oneflow-16:~ $ python3
Python 3.6.8 (default, Apr  2 2020, 13:34:55) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import oneflow as flow
>>> x = flow.tensor(2.0)
>>> x
tensor(2., dtype=oneflow.float32)
>>> x.shape
oneflow.Size([])
>>> a = flow.reshape(x, ())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chengcheng/oneflow/python/oneflow/nn/modules/reshape.py", line 59, in reshape_op
    return flow._C.reshape(input, shape)
oneflow._oneflow_internal.exception.CheckFailedException: 
  File "/home/chengcheng/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 139, in Dispatch<oneflow::one::Tensor>
    Dispatch<TensorTuple>(op_expr, inputs, ctx)
  File "/home/chengcheng/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 131, in Dispatch<oneflow::one::TensorTuple>
    Dispatch(op_expr, inputs, outputs.get(), ctx)
  File "/home/chengcheng/oneflow/oneflow/core/framework/op_interpreter/op_interpreter.cpp", line 109, in Apply
    internal_->Apply(op_expr, inputs, outputs, ctx)
  File "/home/chengcheng/oneflow/oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp", line 147, in NaiveInterpret
    user_op_expr.InferLogicalShapeAndDType( attrs, device_tag ... TensorMeta* { return output_tensor_metas->at(i); })
  File "/home/chengcheng/oneflow/oneflow/core/framework/op_expr.cpp", line 387, in InferLogicalShapeAndDType
    shape_infer_fn_(&infer_ctx)
  File "/home/chengcheng/oneflow/oneflow/user/ops/reshape_op.cpp", line 49, in LogicalTensorDescInferFn
    Check failed: (shape.NumAxes()) >= (1) (0 vs 1)
>>> 
```

### torch ：

```console
chengcheng@oneflow-21:~ $ python3
Python 3.8.5 (default, May 27 2021, 13:30:53) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> a = torch.tensor(1)
>>> a.shape
torch.Size([])
>>> b = torch.reshape(a, (-1,))
>>> b
tensor([1])
>>> b.shape
torch.Size([1])
>>> c = torch.reshape(a, (1,))
>>> c.shape
torch.Size([1])
>>> d = torch.reshape(a, (2,))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: shape '[2]' is invalid for input of size 1
>>> e = torch.reshape(b, ())
>>> e
tensor(1)
>>> e.shape
```

**Comment by chengtbf** [comment]
- 分支： https://github.com/Oneflow-Inc/oneflow/pull/6254/commits/6d15ae94784967db04df18344a026f4a444c02fa

### 本分支

```console
hengcheng@oneflow-21:~ $ python3
Python 3.8.5 (default, May 27 2021, 13:30:53) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import oneflow as flow
>>> x = flow.tensor(1)
>>> x
tensor(1, dtype=oneflow.int64)
>>> x.shape
oneflow.Size([])
>>> a = flow.reshape(x, (1,))
>>> a
tensor([1], dtype=oneflow.int64)
>>> a.shape
oneflow.Size([1])
>>> b = flow.reshape(x, ())
>>> b
tensor(1, dtype=oneflow.int64)
>>> c = flow.reshape(a, ())
>>> c.shape
oneflow.Size([])

```


验证结果与 torch 完全一致
