### ISSUE TITLE
(s0, p) -> (s0, s0) 不支持

### ISSUE THREAD

**Issue by liufengwei0103** [Oneflow-Inc/oneflow#6292]
```
 import oneflow as flow

placement = flow.placement("cuda", {0:range(2)}, hierarchy=(2, 1))
x = flow.ones(6, 6, placement=placement, sbp=[flow.sbp.split(0), flow.sbp.partial_sum])
x = x.to_consistent(placement=placement, sbp=[flow.sbp.split(0), flow.sbp.split(0)])
```
 

信息：
Traceback (most recent call last):
  File "2d_sbp.py", line 6, in <module>
    x = x.to_consistent(placement=placement, sbp=[flow.sbp.split(0), flow.sbp.split(0)])
  File "/home/liufengwei/oneflow/python/oneflow/nn/modules/consistent_cast.py", line 105, in to_consistent_op
    return flow._C.to_consistent(input, placement, sbp, grad_sbp)
oneflow._oneflow_internal.exception.BoxingNotSupportedException: 
  File "/home/liufengwei/oneflow/oneflow/core/functional/impl/consistent_cast.cpp", line 338, in operator()
    ConsistentToConsistent(x, parallel_desc, sbp_parallels, grad_sbp_parallels)
  File "/home/liufengwei/oneflow/oneflow/core/functional/impl/consistent_cast.cpp", line 232, in ConsistentToConsistent
    OpInterpUtil::Dispatch<one::Tensor>( *op, {consistent_tensor}, OpExprInterpContext(AttrMap{}, parallel_desc, nd_sbp))
  File "/home/liufengwei/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 139, in Dispatch<oneflow::one::Tensor>
    Dispatch<TensorTuple>(op_expr, inputs, ctx)
  File "/home/liufengwei/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 131, in Dispatch<oneflow::one::TensorTuple>
    Dispatch(op_expr, inputs, outputs.get(), ctx)
  File "/home/liufengwei/oneflow/oneflow/core/framework/op_interpreter/op_interpreter.cpp", line 94, in Apply
    internal_->Apply(op_expr, inputs, outputs, ctx)
  File "/home/liufengwei/oneflow/oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp", line 209, in ApplyImpl
    ConsistentToConsistent(op_expr, inputs, outputs, ctx)
  File "/home/liufengwei/oneflow/oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp", line 181, in RawConsistentToConsistent
    RecursiveGetBoxingOutput(input, out_nd_sbp, out_parallel_desc, in_parallel_id->has_value() || out_parallel_id->has_value())
  File "/home/liufengwei/oneflow/oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp", line 77, in CalcBoxingOutput
    mgr->GetEagerBoxingInterpreter(in_nd_sbp, out_nd_sbp, in_parallel_desc, out_parallel_desc)
consistent-to-consistent not supported. from_nd_sbp: (oneflow.sbp.split(axis=0), oneflow.sbp.partial_sum), to_nd_sbp: (oneflow.sbp.split(axis=0), oneflow.sbp.split(axis=0)), from_placement: oneflow.placement(device_type="cuda", machine_device_ids={0 : [0, 1]}, hierarchy=(2, 1)), to_placement: oneflow.placement(device_type="cuda", machine_device_ids={0 : [0, 1]}, hierarchy=(2, 1))

**Comment by lixinqi** [comment]
背后的原因其实是暂时不支持sbp改写。比如(S0, P)->(S0, S0)虽然非法，但是如果我们改写boxing，先reshape，然后boxing就会被改写为S0, P)->(S0, S1)
