### ISSUE TITLE
Consistent tensor indexing

### ISSUE THREAD

**Issue by Garfieldgzhh** [Oneflow-Inc/oneflow#7020]
对consistent tensor 做 indexing 操作的时候报错

## 复现代码：

```
# test.py

import numpy as np
import oneflow as flow

placement = flow.placement("cuda",{0:[0, 1]})
sbp = sbp = flow.sbp.split(0)

x = flow.rand(3, 4, 5, placement=placement, sbp=sbp)
print(x)
print(x[1])
```
oneflow是从master上编译的
运行方式：python3 -m  oneflow.distributed.launch --nproc_per_node 2 test.py

报错信息：
```
loaded library: /lib/x86_64-linux-gnu/libibverbs.so.1
loaded library: loaded library: /lib/x86_64-linux-gnu/libibverbs.so.1
/lib/x86_64-linux-gnu/libibverbs.so.1
F1213 17:05:54.635650 88881 eager_nccl_kernels.cu:267] Check failed: in->shape().elem_cnt() == out->shape().elem_cnt() (20 vs. 30) (1,4,5) vs (3,2,5)
*** Check failure stack trace: ***
    @     0x7f60f658ddfd  google::LogMessage::Fail()
    @     0x7f60f658f64a  google::LogMessage::SendToLog()
    @     0x7f60f658d8cd  google::LogMessage::Flush()
    @     0x7f60f6590a79  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f60f22ea42d  oneflow::EagerNcclS2SKernel<>::Compute()
    @     0x7f60f0f61348  oneflow::vm::LocalCallOpKernelUtil::Compute()
    @     0x7f60f0f29adf  oneflow::vm::LocalCallOpKernelInstructionType::Compute()
    @     0x7f60f1f7a7a6  oneflow::vm::CudaStreamType::Compute()
    @     0x7f60f1f9e9fe  oneflow::vm::StreamType::Run()
    @     0x7f60f1fad2cb  oneflow::vm::VirtualMachine::DispatchAndPrescheduleInstructions()
    @     0x7f60f1fadc6e  oneflow::vm::VirtualMachine::Schedule()
    @     0x7f60f1f8e294  oneflow::OneflowVM::Loop()
    @     0x7f60f6c3329f  (unknown)
    @     0x7f6344dc4609  start_thread
    @     0x7f6344f00293  clone
    @              (nil)  (unknown)
Killing subprocess 88577
Killing subprocess 88578
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/guanzhanghuihong/.local/lib/python3.8/site-packages/oneflow/distributed/launch.py", line 211, in <module>
    main()
  File "/home/guanzhanghuihong/.local/lib/python3.8/site-packages/oneflow/distributed/launch.py", line 199, in main
    sigkill_handler(signal.SIGTERM, None)
  File "/home/guanzhanghuihong/.local/lib/python3.8/site-packages/oneflow/distributed/launch.py", line 167, in sigkill_handler
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', 'test.py']' died with <Signals.SIGABRT: 6>.
```
和后江讨论过后，当sbp设置为split(0)的时候，应该会自动插入boxing把x转为broadcast。

**Comment by hjchen2** [comment]
这里报错的原因应该是`x = flow.rand(3, 4, 5, placement=placement, sbp=sbp)`里面的3不能按0维平均分

**Comment by Garfieldgzhh** [comment]
> 这里报错的原因应该是`x = flow.rand(3, 4, 5, placement=placement, sbp=sbp)`里面的3不能按0维平均分

形状改为（4，4，5）之后还是会报类似的错误

**Comment by liufengwei0103** [comment]
这个问题和 https://github.com/Oneflow-Inc/OneTeam/issues/738是同一个问题。

**Comment by chengtbf** [comment]
这个问题被哪个 PR 修复了？ 我看

- Oneflow-Inc/OneTeam#738 

好像也没有完全解决？

**Comment by Garfieldgzhh** [comment]
我也没有看到解决的地方。因为这个issue和issue 738重复了，所以关闭这个

**Comment by Garfieldgzhh** [comment]
> 
```
import numpy as np
import oneflow as flow

placement = flow.placement("cuda",{0:[0, 1]})
sbp = sbp = flow.sbp.split(0)
x = flow.rand(4, 4, 5, placement=placement, sbp=sbp)

print(x[1])
```
报错：
```
F1214 00:25:50.646647 1280317 eager_nccl_kernels.cu:267] Check failed: in->shape().elem_cnt() == out->shape().elem_cnt() (10 vs. 8) (2,5) vs (4,2)
*** Check failure stack trace: ***
    @     0x7f8d22150dfd  google::LogMessage::Fail()
F1214 00:25:50.649406 1280311 eager_nccl_kernels.cu:267] Check failed: in->shape().elem_cnt() == out->shape().elem_cnt() (10 vs. 12) (2,5) vs (4,3)
*** Check failure stack trace: ***
    @     0x7f66faba2dfd  google::LogMessage::Fail()
    @     0x7f8d2215264a  google::LogMessage::SendToLog()
    @     0x7f8d221508cd  google::LogMessage::Flush()
    @     0x7f66faba464a  google::LogMessage::SendToLog()
    @     0x7f66faba28cd  google::LogMessage::Flush()
    @     0x7f8d22153a79  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f8d1dead42d  oneflow::EagerNcclS2SKernel<>::Compute()
    @     0x7f8d1cb24348  oneflow::vm::LocalCallOpKernelUtil::Compute()
    @     0x7f66faba5a79  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f66f68ff42d  oneflow::EagerNcclS2SKernel<>::Compute()
    @     0x7f66f5576348  oneflow::vm::LocalCallOpKernelUtil::Compute()
    @     0x7f8d1caecadf  oneflow::vm::LocalCallOpKernelInstructionType::Compute()
    @     0x7f66f553eadf  oneflow::vm::LocalCallOpKernelInstructionType::Compute()
    @     0x7f8d1db3d7a6  oneflow::vm::CudaStreamType::Compute()
    @     0x7f8d1db619fe  oneflow::vm::StreamType::Run()
    @     0x7f66f658f7a6  oneflow::vm::CudaStreamType::Compute()
    @     0x7f66f65b39fe  oneflow::vm::StreamType::Run()
    @     0x7f8d1db702cb  oneflow::vm::VirtualMachine::DispatchAndPrescheduleInstructions()
    @     0x7f8d1db70c6e  oneflow::vm::VirtualMachine::Schedule()
    @     0x7f66f65c22cb  oneflow::vm::VirtualMachine::DispatchAndPrescheduleInstructions()
    @     0x7f66f65c2c6e  oneflow::vm::VirtualMachine::Schedule()
    @     0x7f8d1db51294  oneflow::OneflowVM::Loop()
    @     0x7f8d227f629f  (unknown)
    @     0x7f8f70987609  start_thread
    @     0x7f8f70ac3293  clone
    @              (nil)  (unknown)
    @     0x7f66f65a3294  oneflow::OneflowVM::Loop()
    @     0x7f66fb24829f  (unknown)
    @     0x7f69493d9609  start_thread
    @     0x7f6949515293  clone
    @              (nil)  (unknown)
Killing subprocess 1280011
Killing subprocess 1280012
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/guanzhanghuihong/.local/lib/python3.8/site-packages/oneflow/distributed/launch.py", line 211, in <module>
    main()
  File "/home/guanzhanghuihong/.local/lib/python3.8/site-packages/oneflow/distributed/launch.py", line 199, in main
    sigkill_handler(signal.SIGTERM, None)
  File "/home/guanzhanghuihong/.local/lib/python3.8/site-packages/oneflow/distributed/launch.py", line 167, in sigkill_handler
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', 'test.py']' died with <Signals.SIGABRT: 6>.
```
但是如果是shape为（4，4），是可以正常打印的：
```
tensor([0.6355, 0.4277, 0.8102, 0.2268],
       placement=oneflow.placement(device_type="cuda", machine_device_ids={0 : [0, 1]}, hierarchy=(2,)),
       sbp=(oneflow.sbp.split(axis=0),), dtype=oneflow.float32)
tensor([0.6355, 0.4277, 0.8102, 0.2268],
       placement=oneflow.placement(device_type="cuda", machine_device_ids={0 : [0, 1]}, hierarchy=(2,)),
       sbp=(oneflow.sbp.split(axis=0),), dtype=oneflow.float32)
```

**Comment by chengtbf** [comment]
为什么上述例子报错提示的 shape 是 2 维的，但是数据是 3 维的？

**Comment by Garfieldgzhh** [comment]
我没有看出报错信息里哪里提示了shape的维度，是不是因为x[1]应该是2维的？

**Comment by hjchen2** [comment]
x[1]出来的维度是(4, 5)，打印这个tensor时用到了slice，在对其中5切分时可能又触发了非均匀切分

**Comment by chengtbf** [comment]
> 我没有看出报错信息里哪里提示了shape的维度，是不是因为x[1]应该是2维的？

报错：
```
F1214 00:25:50.646647 1280317 eager_nccl_kernels.cu:267] Check failed: in->shape().elem_cnt() == out->shape().elem_cnt() (10 vs. 8) (2,5) vs (4,2)
````

这里显示是 (2, 5) 和 (4, 2) 不对应
