### ISSUE TITLE
52算力版本自己编译，执行报错

### ISSUE THREAD

**Issue by muzhailong** [Oneflow-Inc/oneflow#7061]
代码：https://gitee.com/mzl2020/oneflow_models
执行：run_distribute.sh

`Namespace(attention_probs_dropout_prob=0.1, checkpoint_path='checkpoints', ctrl_port=50051, cuda_devices=None, do_eval=None, do_lower_case=True, do_train=None, epochs=1, gpu_num_per_node=1, grad_acc_steps=1, hidden_dropout_prob=0.1, hidden_size_per_head=64, learning_rate=5e-05, log_dir='./output', loss_print_every_n_iter=10, loss_print_every_n_iters=20, lr=0.001, max_position_embeddings=512, max_predictions_per_seq=20, metric_local=False, model='BERT Pretrain', model_load_dir=None, model_save_dir='./output/model_save-2021-12-20-16:57:46', model_save_every_n_iter=10000, nccl_fusion_max_ops=24, nccl_fusion_threshold_mb=16, node_ips=['192.168.1.13', '192.168.1.14'], num_attention_heads=12, num_hidden_layers=12, num_nodes=1, ofrecord_path='./data/wiki_ofrecord_seq_len_128', optim_name='adamw', save_last_snapshot=False, seq_length=128, train_batch_size=32, train_data_part=4, train_dataset_size=10000000, train_global_batch_size=64, type_vocab_size=2, use_consistent=None, use_ddp=None, use_fp16=False, use_xla=None, val_batch_size=32, val_global_batch_size=None, val_print_every_n_iters=20, vocab_size=30522, warmup_proportion=0.1, weight_decay=0.01, weight_decay_rate=0.01, with_cuda=True)
Creating Dataloader
Namespace(attention_probs_dropout_prob=0.1, checkpoint_path='checkpoints', ctrl_port=50051, cuda_devices=None, do_eval=None, do_lower_case=True, do_train=None, epochs=1, gpu_num_per_node=1, grad_acc_steps=1, hidden_dropout_prob=0.1, hidden_size_per_head=64, learning_rate=5e-05, log_dir='./output', loss_print_every_n_iter=10, loss_print_every_n_iters=20, lr=0.001, max_position_embeddings=512, max_predictions_per_seq=20, metric_local=False, model='BERT Pretrain', model_load_dir=None, model_save_dir='./output/model_save-2021-12-20-16:57:46', model_save_every_n_iter=10000, nccl_fusion_max_ops=24, nccl_fusion_threshold_mb=16, node_ips=['192.168.1.13', '192.168.1.14'], num_attention_heads=12, num_hidden_layers=12, num_nodes=1, ofrecord_path='./data/wiki_ofrecord_seq_len_128', optim_name='adamw', save_last_snapshot=False, seq_length=128, train_batch_size=32, train_data_part=4, train_dataset_size=10000000, train_global_batch_size=64, type_vocab_size=2, use_consistent=None, use_ddp=None, use_fp16=False, use_xla=None, val_batch_size=32, val_global_batch_size=None, val_print_every_n_iters=20, vocab_size=30522, warmup_proportion=0.1, weight_decay=0.01, weight_decay_rate=0.01, with_cuda=True)
Creating Dataloader
Building BERT Model
Building BERT Model
Building Graph
Building Graph
Start training!
Start training!
F1220 16:57:56.399008 23253 gradient_accumulation_rewrite_pass.cpp:186] Check failed: return_in_lbn == old_val (_PipelineGraph_0-input_3/out vs. System-GradientAccumulation-InputUnpack-_PipelineGraph_0-input_3-50/out_0) 
*** Check failure stack trace: ***
    @     0x2b056fd643cd  google::LogMessage::Fail()
    @     0x2b056fd65c4a  google::LogMessage::SendToLog()
    @     0x2b056fd63e8d  google::LogMessage::Flush()
    @     0x2b056fd67079  google::LogMessageFatal::~LogMessageFatal()
    @     0x2b056b5e2ec2  (unknown)
    @     0x2b056b5e3e2f  (unknown)
    @     0x2b056b3c6377  oneflow::Graph<>::TopoForEachNodeWithErrorCaptured()
    @     0x2b056b3c74a6  oneflow::Graph<>::TopoForEachNodeWithErrorCaptured()
    @     0x2b056b5e155d  oneflow::GradientAccumulationRewritePass::Apply()
    @     0x2b056b48a27d  (unknown)
    @     0x2b056b4acec5  oneflow::LazyJobBuildAndInferCtx::Complete()
    @     0x2b056a70f550  CurJobBuildAndInferCtx_Complete()
    @     0x2b056a609653  (unknown)
    @     0x2b056a3de397  (unknown)
    @     0x2b0355d717e7  _PyCFunction_FastCallDict
    @     0x2b0355ddd14f  (unknown)
    @     0x2b0355dd1a17  _PyEval_EvalFrameDefault
    @     0x2b0355ddc317  (unknown)
    @     0x2b0355dde35f  _PyFunction_FastCallDict
    @     0x2b0355d33d9e  _PyObject_FastCallDict
    @     0x2b0355d33eb1  _PyObject_Call_Prepend
    @     0x2b0355d33b23  PyObject_Call
    @     0x2b0355dd36a5  _PyEval_EvalFrameDefault
    @     0x2b0355ddc317  (unknown)
    @     0x2b0355dde35f  _PyFunction_FastCallDict
    @     0x2b0355d33d9e  _PyObject_FastCallDict
    @     0x2b0355d33eb1  _PyObject_Call_Prepend
    @     0x2b0355d33b23  PyObject_Call
    @     0x2b0355dd36a5  _PyEval_EvalFrameDefault
    @     0x2b0355ddc317  (unknown)
    @     0x2b0355dde35f  _PyFunction_FastCallDict
    @     0x2b0355d33d9e  _PyObject_FastCallDict
F1220 16:57:56.512796 23252 gradient_accumulation_rewrite_pass.cpp:186] Check failed: return_in_lbn == old_val (_PipelineGraph_0-input_3/out vs. System-GradientAccumulation-InputUnpack-_PipelineGraph_0-input_3-50/out_0) 
*** Check failure stack trace: ***
    @     0x2b9fdede23cd  google::LogMessage::Fail()
    @     0x2b9fdede3c4a  google::LogMessage::SendToLog()
    @     0x2b9fdede1e8d  google::LogMessage::Flush()
    @     0x2b9fdede5079  google::LogMessageFatal::~LogMessageFatal()
    @     0x2b9fda660ec2  (unknown)
    @     0x2b9fda661e2f  (unknown)
    @     0x2b9fda444377  oneflow::Graph<>::TopoForEachNodeWithErrorCaptured()
    @     0x2b9fda4454a6  oneflow::Graph<>::TopoForEachNodeWithErrorCaptured()
    @     0x2b9fda65f55d  oneflow::GradientAccumulationRewritePass::Apply()
    @     0x2b9fda50827d  (unknown)
    @     0x2b9fda52aec5  oneflow::LazyJobBuildAndInferCtx::Complete()
    @     0x2b9fd978d550  CurJobBuildAndInferCtx_Complete()
    @     0x2b9fd9687653  (unknown)
    @     0x2b9fd945c397  (unknown)
    @     0x2b9dc4def7e7  _PyCFunction_FastCallDict
    @     0x2b9dc4e5b14f  (unknown)
    @     0x2b9dc4e4fa17  _PyEval_EvalFrameDefault
    @     0x2b9dc4e5a317  (unknown)
    @     0x2b9dc4e5c35f  _PyFunction_FastCallDict
    @     0x2b9dc4db1d9e  _PyObject_FastCallDict
    @     0x2b9dc4db1eb1  _PyObject_Call_Prepend
    @     0x2b9dc4db1b23  PyObject_Call
    @     0x2b9dc4e516a5  _PyEval_EvalFrameDefault
    @     0x2b9dc4e5a317  (unknown)
    @     0x2b9dc4e5c35f  _PyFunction_FastCallDict
    @     0x2b9dc4db1d9e  _PyObject_FastCallDict
    @     0x2b9dc4db1eb1  _PyObject_Call_Prepend
    @     0x2b9dc4db1b23  PyObject_Call
    @     0x2b9dc4e516a5  _PyEval_EvalFrameDefault
    @     0x2b9dc4e5a317  (unknown)
    @     0x2b9dc4e5c35f  _PyFunction_FastCallDict
    @     0x2b9dc4db1d9e  _PyObject_FastCallDict
Killing subprocess 23252
Killing subprocess 23253
Traceback (most recent call last):
  File "/data/application/guest/python36/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/data/application/guest/python36/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/home/muzhailong/.local/lib/python3.6/site-packages/oneflow/distributed/launch.py", line 211, in <module>
    main()
  File "/data/home/muzhailong/.local/lib/python3.6/site-packages/oneflow/distributed/launch.py", line 199, in main
    sigkill_handler(signal.SIGTERM, None)
  File "/data/home/muzhailong/.local/lib/python3.6/site-packages/oneflow/distributed/launch.py", line 168, in sigkill_handler
    returncode=last_return_code, cmd=cmd
subprocess.CalledProcessError: Command '['/data/application/guest/python36/bin/python3', '-u', 'run_eager_pretraining.py', '--num_hidden_layers', '12', '--num_attention_heads', '12', '--max_position_embeddings', '512', '--seq_length', '128', '--vocab_size', '30522', '--type_vocab_size', '2', '--attention_probs_dropout_prob', '0.1', '--train-data-part', '4', '--hidden_dropout_prob', '0.1', '--max_predictions_per_seq', '20', '--train-batch-size', '32', '--train-global-batch-size', '64', '--learning_rate', '0.00005', '--ofrecord_path', './data/wiki_ofrecord_seq_len_128']' died with <Signals.SIGABRT: 6>.
[muzhailong@cn15 pddl]$ `

**Comment by chengtbf** [comment]
请问您使用的是什么版本的 oneflow 呢~

**Comment by muzhailong** [comment]
> 请问您使用的是什么版本的 oneflow 呢~

master版本

**Comment by lixiang007666** [comment]
@muzhailong 这个使用最新的master版本你有尝试过吗。

**Comment by muzhailong** [comment]
> @muzhailong 这个使用最新的master版本你有尝试过吗。

这是新错误，A100可以跑通，M40不行，应该是某个check没过
`[muzhailong@cn2 ~]$ cd devs/pddl/
[muzhailong@cn2 pddl]$ ./run_distribute.sh 1
loaded library: /lib64/libibverbs.so.1
loaded library: /lib64/libibverbs.so.1
loaded library: /lib64/libibverbs.so.1
F1221 15:15:35.532239 57307 cuda_stream_type.cpp:64] Check failed: cudaGetLastError() : no kernel image is available for execution on the device (209) 
*** Check failure stack trace: ***
    @     0x2b1a949ab8cd  google::LogMessage::Fail()
    @     0x2b1a949ad14a  google::LogMessage::SendToLog()
    @     0x2b1a949ab38d  google::LogMessage::Flush()
    @     0x2b1a949ae579  google::LogMessageFatal::~LogMessageFatal()
    @     0x2b1a90de31e8  oneflow::vm::CudaStreamType::Compute()
    @     0x2b1a90e01f7e  oneflow::vm::StreamType::Run()
    @     0x2b1a90e18a05  oneflow::vm::VirtualMachineEngine::DispatchInstruction()
    @     0x2b1a90e1ae6a  oneflow::vm::VirtualMachineEngine::DispatchAndPrescheduleInstructions()
    @     0x2b1a90e0c6e8  oneflow::VirtualMachine::Loop()
    @     0x2b1a95d22f3f  (unknown)
    @     0x2b18794cedd5  start_thread
    @     0x2b1879ee9ead  __clone
    @              (nil)  (unknown)
F1221 15:15:36.630762 57238 cuda_stream_type.cpp:64] Check failed: cudaGetLastError() : no kernel image is available for execution on the device (209) 
*** Check failure stack trace: ***
    @     0x2b5fa415e8cd  google::LogMessage::Fail()
    @     0x2b5fa416014a  google::LogMessage::SendToLog()
    @     0x2b5fa415e38d  google::LogMessage::Flush()
    @     0x2b5fa4161579  google::LogMessageFatal::~LogMessageFatal()
    @     0x2b5fa05961e8  oneflow::vm::CudaStreamType::Compute()
    @     0x2b5fa05b4f7e  oneflow::vm::StreamType::Run()
    @     0x2b5fa05cba05  oneflow::vm::VirtualMachineEngine::DispatchInstruction()
    @     0x2b5fa05cde6a  oneflow::vm::VirtualMachineEngine::DispatchAndPrescheduleInstructions()
    @     0x2b5fa05bf6e8  oneflow::VirtualMachine::Loop()
    @     0x2b5fa54d5f3f  (unknown)
    @     0x2b5d88c81dd5  start_thread
    @     0x2b5d8969cead  __clone
    @              (nil)  (unknown)
Killing subprocess 57027
Terminated
`

**Comment by lixiang007666** [comment]
### 预期结果：
使用最新的master分支源码编译，运行run_distribute.sh正常训练（代码：https://gitee.com/mzl2020/oneflow_models）。

### 环境：
双机4卡训练，GPU A100可以训练，M40报错。报如下错误：

### 错误信息：
[muzhailong@cn2 pddl]$ ./run_distribute.sh 1 loaded library: /lib64/libibverbs.so.1 loaded library: /lib64/libibverbs.so.1 loaded library: /lib64/libibverbs.so.1 F1221 15:15:35.532239 57307 cuda_stream_type.cpp:64] Check failed: cudaGetLastError() : no kernel image is available for execution on the device (209) *** Check failure stack trace: *** @ 0x2b1a949ab8cd google::LogMessage::Fail() @ 0x2b1a949ad14a google::LogMessage::SendToLog() @ 0x2b1a949ab38d google::LogMessage::Flush() @ 0x2b1a949ae579 google::LogMessageFatal::~LogMessageFatal() @ 0x2b1a90de31e8 oneflow::vm::CudaStreamType::Compute() @ 0x2b1a90e01f7e oneflow::vm::StreamType::Run() @ 0x2b1a90e18a05 oneflow::vm::VirtualMachineEngine::DispatchInstruction() @ 0x2b1a90e1ae6a oneflow::vm::VirtualMachineEngine::DispatchAndPrescheduleInstructions() @ 0x2b1a90e0c6e8 oneflow::VirtualMachine::Loop() @ 0x2b1a95d22f3f (unknown) @ 0x2b18794cedd5 start_thread @ 0x2b1879ee9ead __clone @ (nil) (unknown) F1221 15:15:36.630762 57238 cuda_stream_type.cpp:64] Check failed: cudaGetLastError() : no kernel image is available for execution on the device (209) *** Check failure stack trace: *** @ 0x2b5fa415e8cd google::LogMessage::Fail() @ 0x2b5fa416014a google::LogMessage::SendToLog() @ 0x2b5fa415e38d google::LogMessage::Flush() @ 0x2b5fa4161579 google::LogMessageFatal::~LogMessageFatal() @ 0x2b5fa05961e8 oneflow::vm::CudaStreamType::Compute() @ 0x2b5fa05b4f7e oneflow::vm::StreamType::Run() @ 0x2b5fa05cba05 oneflow::vm::VirtualMachineEngine::DispatchInstruction() @ 0x2b5fa05cde6a oneflow::vm::VirtualMachineEngine::DispatchAndPrescheduleInstructions() @ 0x2b5fa05bf6e8 oneflow::VirtualMachine::Loop() @ 0x2b5fa54d5f3f (unknown) @ 0x2b5d88c81dd5 start_thread @ 0x2b5d8969cead __clone @ (nil) (unknown) Killing subprocess 57027 Terminated

**Comment by muzhailong** [comment]
把源代码里所有的OF_CUDA_CHECK(cudaGetLastError()) 注释掉 52算力的卡就可以跑了  源代码参考：https://gitee.com/mzl2020/oneflow_52

**Comment by jackalcooper** [comment]
这个是cmake参数没有设置正确，`CMAKE_CUDA_ARCHITECTURES` 要设置为 `52-real`

**Comment by muzhailong** [comment]
> 这个是cmake参数没有设置正确，`CMAKE_CUDA_ARCHITECTURES` 要设置为 `52-real`

这个我加了，但是如果不注释掉源代码里所有的`OF_CUDA_CHECK(cudaGetLastError())`还是跑不了的

**Comment by jackalcooper** [comment]
> > 这个是cmake参数没有设置正确，`CMAKE_CUDA_ARCHITECTURES` 要设置为 `52-real`
> 
> 这个我加了，但是如果不注释掉源代码里所有的`OF_CUDA_CHECK(cudaGetLastError())`还是跑不了的

你是怎么加这个参数的呢，去掉这个check只是不报错了，但是错误并没有真的消除。可以看下 build 目录下的 `compile_commands.json` 中cu文件的编译命令是不是确实有52架构的参数
