### ISSUE TITLE
静态图可以run，动态图（eager模式）却报错

### ISSUE THREAD

**Issue by muzhailong** [Oneflow-Inc/oneflow#7094]
代码：https://gitee.com/mzl2020/oneflow_models/tree/master
应该是OfRecordDataLoader的问题，但是不懂这个place应该怎么设置？
`lobal_batch_size:24
Creating Dataloader
Building BERT Model
嵌入层参数量:63561856, encoder layer参数量:63561856，输出层参数量:66707456
split: [{0: 1, 1: 8, 2: 0}, {0: 0, 1: 9, 2: 0}, {0: 0, 1: 7, 2: 1}]
placement: [oneflow.placement(device_type="cuda", machine_device_ids={0 : [0, 1, 2]}, hierarchy=(3,)), oneflow.placement(device_type="cuda", machine_device_ids={1 : [0, 1, 2]}, hierarchy=(3,)), oneflow.placement(device_type="cuda", machine_device_ids={2 : [0, 1, 2]}, hierarchy=(3,))]
Building Graph
Start warmuping!
Start warmuping!
Start warmuping!
Traceback (most recent call last):
  File "train.py", line 448, in <module>
Traceback (most recent call last):
  File "train.py", line 448, in <module>
    loss, mlm_loss, nsp_loss = graph_pipeline.build()
  File "train.py", line 343, in build
    ) = self._train_data_loader()
  File "/data/home/muzhailong/.local/lib/python3.6/site-packages/oneflow/nn/graph/block.py", line 206, in __call__
Traceback (most recent call last):
  File "train.py", line 448, in <module>
    loss, mlm_loss, nsp_loss = graph_pipeline.build()
  File "train.py", line 343, in build
    ) = self._train_data_loader()
  File "/data/home/muzhailong/.local/lib/python3.6/site-packages/oneflow/nn/graph/block.py", line 206, in __call__
    result = self.__block_forward(*args)
  File "/data/home/muzhailong/.local/lib/python3.6/site-packages/oneflow/nn/graph/block.py", line 238, in __block_forward
    result = self.__block_forward(*args)
  File "/data/home/muzhailong/.local/lib/python3.6/site-packages/oneflow/nn/graph/block.py", line 238, in __block_forward
    result = self._origin.__class__.forward(self, *args)
  File "/data/home/muzhailong/devs/pddl/utils/ofrecord_data_utils.py", line 77, in forward
    result = self._origin.__class__.forward(self, *args)
  File "/data/home/muzhailong/devs/pddl/utils/ofrecord_data_utils.py", line 77, in forward
    input_ids = input_ids.to_consistent(placement=placement, sbp=sbp)
  File "/data/home/muzhailong/.local/lib/python3.6/site-packages/oneflow/nn/modules/consistent_cast.py", line 105, in to_consistent_op
    input_ids = input_ids.to_consistent(placement=placement, sbp=sbp)
  File "/data/home/muzhailong/.local/lib/python3.6/site-packages/oneflow/nn/modules/consistent_cast.py", line 105, in to_consistent_op
    return flow._C.to_consistent(input, placement, sbp, grad_sbp)
oneflow._oneflow_internal.exception.CheckFailedException: 
  File "/root/muzhailong/oneflow/oneflow/core/functional/impl/consistent_cast.cpp", line 343, in operator()
    ConsistentToConsistent(x, parallel_desc, sbp_parallels, grad_sbp_parallels)
  File "/root/muzhailong/oneflow/oneflow/core/functional/impl/consistent_cast.cpp", line 235, in ConsistentToConsistent
    OpInterpUtil::Dispatch<one::Tensor>( *op, {consistent_tensor}, OpExprInterpContext(AttrMap{}, parallel_desc, nd_sbp))
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 139, in Dispatch<oneflow::one::Tensor>
    Dispatch<TensorTuple>(op_expr, inputs, ctx)
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 131, in Dispatch<oneflow::one::TensorTuple>
    Dispatch(op_expr, inputs, outputs.get(), ctx)
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/op_interpreter.cpp", line 95, in Apply
    internal_->Apply(op_expr, inputs, outputs, ctx)
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp", line 210, in ApplyImpl
    ConsistentToConsistent(op_expr, inputs, outputs, ctx)
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp", line 182, in RawConsistentToConsistent
    RecursiveGetBoxingOutput(input, out_nd_sbp, out_parallel_desc, in_parallel_id->has_value() || out_parallel_id->has_value())
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp", line 79, in CalcBoxingOutput
    boxing_interpreter->Interpret(input, in_nd_sbp, out_nd_sbp, in_parallel_desc, out_parallel_desc)
  File "/root/muzhailong/oneflow/oneflow/core/boxing/eager_boxing_interpreter.cpp", line 41, in Interpret
    InterpretImpl(input, in_nd_sbp, out_nd_sbp, in_parallel_desc, out_parallel_desc)
  File "/root/muzhailong/oneflow/oneflow/core/boxing/eager_boxing_interpreter.h", line 93, in InterpretImpl
    (*boxing_function_)(input, in_placed_nd_sbp, out_placed_nd_sbp)
  File "/root/muzhailong/oneflow/oneflow/core/boxing/naive_b_to_s_boxing.cpp", line 66, in NaiveBToS
    one::functional::EagerBToS( local_tensor, tensor_placement, out->placement(), *sbp_list, *tensor->shape())
  File "/root/muzhailong/oneflow/oneflow/core/functional/impl/slice_boxing_functor.cpp", line 202, in operator()
    OpInterpUtil::Dispatch<Tensor>(*op_expr, {x})
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 139, in Dispatch<oneflow::one::Tensor>
    Dispatch<TensorTuple>(op_expr, inputs, ctx)
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 131, in Dispatch<oneflow::one::TensorTuple>
    Dispatch(op_expr, inputs, outputs.get(), ctx)
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/op_interpreter.cpp", line 95, in Apply
    internal_->Apply(op_expr, inputs, outputs, ctx)
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp", line 138, in NaiveInterpret
    user_op_expr.InferPhysicalShapeAndDType( attrs, device_tag ... TensorMeta* { return output_tensor_metas->at(i); })
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_expr.cpp", line 435, in InferPhysicalShapeAndDType
    shape_infer_fn_(&infer_ctx)
  File "/root/muzhailong/oneflow/oneflow/user/ops/eager_b_to_s_op.cpp", line 36, in TensorDescInfer
    Check failed: shape.At(out_split_axis) % out_parallel_num == 0
    return flow._C.to_consistent(input, placement, sbp, grad_sbp)
oneflow._oneflow_internal.exception.CheckFailedException: 
  File "/root/muzhailong/oneflow/oneflow/core/functional/impl/consistent_cast.cpp", line 343, in operator()
    ConsistentToConsistent(x, parallel_desc, sbp_parallels, grad_sbp_parallels)
  File "/root/muzhailong/oneflow/oneflow/core/functional/impl/consistent_cast.cpp", line 235, in ConsistentToConsistent
    OpInterpUtil::Dispatch<one::Tensor>( *op, {consistent_tensor}, OpExprInterpContext(AttrMap{}, parallel_desc, nd_sbp))
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 139, in Dispatch<oneflow::one::Tensor>
    Dispatch<TensorTuple>(op_expr, inputs, ctx)
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 131, in Dispatch<oneflow::one::TensorTuple>
    Dispatch(op_expr, inputs, outputs.get(), ctx)
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/op_interpreter.cpp", line 95, in Apply
    internal_->Apply(op_expr, inputs, outputs, ctx)
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp", line 210, in ApplyImpl
    ConsistentToConsistent(op_expr, inputs, outputs, ctx)
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp", line 182, in RawConsistentToConsistent
    RecursiveGetBoxingOutput(input, out_nd_sbp, out_parallel_desc, in_parallel_id->has_value() || out_parallel_id->has_value())
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp", line 79, in CalcBoxingOutput
    boxing_interpreter->Interpret(input, in_nd_sbp, out_nd_sbp, in_parallel_desc, out_parallel_desc)
  File "/root/muzhailong/oneflow/oneflow/core/boxing/eager_boxing_interpreter.cpp", line 41, in Interpret
    InterpretImpl(input, in_nd_sbp, out_nd_sbp, in_parallel_desc, out_parallel_desc)
  File "/root/muzhailong/oneflow/oneflow/core/boxing/eager_boxing_interpreter.h", line 93, in InterpretImpl
    (*boxing_function_)(input, in_placed_nd_sbp, out_placed_nd_sbp)
  File "/root/muzhailong/oneflow/oneflow/core/boxing/naive_b_to_s_boxing.cpp", line 66, in NaiveBToS
    one::functional::EagerBToS( local_tensor, tensor_placement, out->placement(), *sbp_list, *tensor->shape())
  File "/root/muzhailong/oneflow/oneflow/core/functional/impl/slice_boxing_functor.cpp", line 202, in operator()
    OpInterpUtil::Dispatch<Tensor>(*op_expr, {x})
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 139, in Dispatch<oneflow::one::Tensor>
    Dispatch<TensorTuple>(op_expr, inputs, ctx)
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 131, in Dispatch<oneflow::one::TensorTuple>
    Dispatch(op_expr, inputs, outputs.get(), ctx)
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/op_interpreter.cpp", line 95, in Apply
    internal_->Apply(op_expr, inputs, outputs, ctx)
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp", line 138, in NaiveInterpret
    user_op_expr.InferPhysicalShapeAndDType( attrs, device_tag ... TensorMeta* { return output_tensor_metas->at(i); })
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_expr.cpp", line 435, in InferPhysicalShapeAndDType
    shape_infer_fn_(&infer_ctx)
  File "/root/muzhailong/oneflow/oneflow/user/ops/eager_b_to_s_op.cpp", line 36, in TensorDescInfer
    Check failed: shape.At(out_split_axis) % out_parallel_num == 0
    loss, mlm_loss, nsp_loss = graph_pipeline.build()
  File "train.py", line 343, in build
    ) = self._train_data_loader()
  File "/data/home/muzhailong/.local/lib/python3.6/site-packages/oneflow/nn/graph/block.py", line 206, in __call__
    result = self.__block_forward(*args)
  File "/data/home/muzhailong/.local/lib/python3.6/site-packages/oneflow/nn/graph/block.py", line 238, in __block_forward
    result = self._origin.__class__.forward(self, *args)
  File "/data/home/muzhailong/devs/pddl/utils/ofrecord_data_utils.py", line 77, in forward
    input_ids = input_ids.to_consistent(placement=placement, sbp=sbp)
  File "/data/home/muzhailong/.local/lib/python3.6/site-packages/oneflow/nn/modules/consistent_cast.py", line 105, in to_consistent_op
    return flow._C.to_consistent(input, placement, sbp, grad_sbp)
oneflow._oneflow_internal.exception.CheckFailedException: 
  File "/root/muzhailong/oneflow/oneflow/core/functional/impl/consistent_cast.cpp", line 343, in operator()
    ConsistentToConsistent(x, parallel_desc, sbp_parallels, grad_sbp_parallels)
  File "/root/muzhailong/oneflow/oneflow/core/functional/impl/consistent_cast.cpp", line 235, in ConsistentToConsistent
    OpInterpUtil::Dispatch<one::Tensor>( *op, {consistent_tensor}, OpExprInterpContext(AttrMap{}, parallel_desc, nd_sbp))
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 139, in Dispatch<oneflow::one::Tensor>
    Dispatch<TensorTuple>(op_expr, inputs, ctx)
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 131, in Dispatch<oneflow::one::TensorTuple>
    Dispatch(op_expr, inputs, outputs.get(), ctx)
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/op_interpreter.cpp", line 95, in Apply
    internal_->Apply(op_expr, inputs, outputs, ctx)
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp", line 210, in ApplyImpl
    ConsistentToConsistent(op_expr, inputs, outputs, ctx)
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp", line 182, in RawConsistentToConsistent
    RecursiveGetBoxingOutput(input, out_nd_sbp, out_parallel_desc, in_parallel_id->has_value() || out_parallel_id->has_value())
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/eager_consistent_op_interpreter.cpp", line 79, in CalcBoxingOutput
    boxing_interpreter->Interpret(input, in_nd_sbp, out_nd_sbp, in_parallel_desc, out_parallel_desc)
  File "/root/muzhailong/oneflow/oneflow/core/boxing/eager_boxing_interpreter.cpp", line 41, in Interpret
    InterpretImpl(input, in_nd_sbp, out_nd_sbp, in_parallel_desc, out_parallel_desc)
  File "/root/muzhailong/oneflow/oneflow/core/boxing/eager_boxing_interpreter.h", line 93, in InterpretImpl
    (*boxing_function_)(input, in_placed_nd_sbp, out_placed_nd_sbp)
  File "/root/muzhailong/oneflow/oneflow/core/boxing/naive_b_to_s_boxing.cpp", line 66, in NaiveBToS
    one::functional::EagerBToS( local_tensor, tensor_placement, out->placement(), *sbp_list, *tensor->shape())
  File "/root/muzhailong/oneflow/oneflow/core/functional/impl/slice_boxing_functor.cpp", line 202, in operator()
    OpInterpUtil::Dispatch<Tensor>(*op_expr, {x})
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 139, in Dispatch<oneflow::one::Tensor>
    Dispatch<TensorTuple>(op_expr, inputs, ctx)
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 131, in Dispatch<oneflow::one::TensorTuple>
    Dispatch(op_expr, inputs, outputs.get(), ctx)
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/op_interpreter.cpp", line 95, in Apply
    internal_->Apply(op_expr, inputs, outputs, ctx)
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp", line 138, in NaiveInterpret
    user_op_expr.InferPhysicalShapeAndDType( attrs, device_tag ... TensorMeta* { return output_tensor_metas->at(i); })
  File "/root/muzhailong/oneflow/oneflow/core/framework/op_expr.cpp", line 435, in InferPhysicalShapeAndDType
    shape_infer_fn_(&infer_ctx)
  File "/root/muzhailong/oneflow/oneflow/user/ops/eager_b_to_s_op.cpp", line 36, in TensorDescInfer
    Check failed: shape.At(out_split_axis) % out_parallel_num == 0
`

**Comment by clackhan** [comment]
您好，目前eager模式还不支持非均匀切割，您在ofrecord_data_utils.py第77行的to_consistent中请确保input_ids的形状的第0维能够整除parallel_num（即placement参数包含的卡数）
