### ISSUE TITLE
[BUG] 打开hardsigmoid(nn.functional下)的graph报错（test_functional_hardsigmoid_with_random_data）

### ISSUE THREAD

**Issue by lixiang007666** [Oneflow-Inc/oneflow#7262]
问题来源：

在graph模式下跑激活函数的测试，其中nn.functional下的hardsigmoid报错，但是nn.Hardsigmoid()没有报错(可以正常打开graph)。

报错的测试代码：
```
    @autotest(check_graph=True)
    def test_functional_hardsigmoid_with_random_data(test_case):
        device = random_device()
        x = random_pytorch_tensor().to(device)
        y = torch.nn.functional.hardsigmoid(x, random_bool())
        return y
```

错误信息：

```
[ERROR](GRAPH:TestGraphOfFunctional_3:TestGraphOfFunctional) building graph got error: <class 'AssertionError'> 
Tensor([1, 1, 4]).to(cuda)
hardsigmoid(Tensor([1, 1, 4]), True)
-----------------------------------------------------------
This program has 1 input tensor: 
Shape[1, 1, 4]
tensor([[[0.5397, 0.5533, 0.5142, 0.5577]]], device='cuda:0',
       grad_fn=<HardsigmoidBackward0>)
-----------------------------------------------------------
E
======================================================================
ERROR: test_functional_hardsigmoid_with_random_data (test_activation.TestHardsigmoidModule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lixiang/oneflow/python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 384, in dual_method
    test_g_res = test_g()
  File "/home/lixiang/oneflow/python/oneflow/nn/graph/graph.py", line 258, in __call__
    self._compile(*args)
  File "/home/lixiang/oneflow/python/oneflow/nn/graph/graph.py", line 506, in _compile
    eager_outputs = self._build_graph(*args)
  File "/home/lixiang/oneflow/python/oneflow/nn/graph/graph.py", line 614, in _build_graph
    ) = self._build_io("output", graph_build_util.build_graph_output, *outputs)
  File "/home/lixiang/oneflow/python/oneflow/nn/graph/graph.py", line 818, in _build_io
    build_args.append(build_tensor_or_none(arg, name, repr_str))
  File "/home/lixiang/oneflow/python/oneflow/nn/graph/graph.py", line 798, in build_tensor_or_none
    build_arg = build_func(name, tensor)
  File "/home/lixiang/oneflow/python/oneflow/framework/graph_build_util.py", line 187, in build_graph_output
    assert out.is_lazy
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lixiang/oneflow/python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 703, in new_f
    res = f(test_case)
  File "/home/lixiang/oneflow/python/oneflow/test/modules/test_activation.py", line 263, in test_functional_hardsigmoid_with_random_data
    y = torch.nn.functional.hardsigmoid(x, random_bool())
  File "/home/lixiang/oneflow/python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 387, in dual_method
    raise OneFlowGraphBuildOrRunError(e)
oneflow.test_utils.automated_test_util.torch_flow_dual_object.OneFlowGraphBuildOrRunError: OneFlow nn.Graph Build Or Run Error: 

----------------------------------------------------------------------
Ran 1 test in 5.454s
```

**Comment by lixiang007666** [comment]
@strint 啸宇哥，这种错误大概是什么原因？

**Comment by strint** [comment]
````
File "/home/lixiang/oneflow/python/oneflow/framework/graph_build_util.py", line 187, in build_graph_output
    assert out.is_lazy
AssertionError
````
已经在这个分支修复，你合并下试试： https://github.com/Oneflow-Inc/oneflow/pull/7254

再打开 ONEFLOW_TEST_VERBOSE 看下 执行状态。

**Comment by lixiang007666** [comment]
> ```
> File "/home/lixiang/oneflow/python/oneflow/framework/graph_build_util.py", line 187, in build_graph_output
>     assert out.is_lazy
> AssertionError
> ```
> 
> 已经在这个分支修复，你合并下试试： #7254
> 
> 再打开 ONEFLOW_TEST_VERBOSE 看下 执行状态。

我合并之后，这个错误没有了，但是graph result和eager result没有对齐。

**Comment by strint** [comment]
> 我合并之后，这个错误没有了，但是graph result和eager result没有对齐。

看下具体哪个case出错了，然后手动复现下

**Comment by lixiang007666** [comment]
错误复现：

nn.functional.hardsigmoid在GPU环境下，inplace版本出现eager和graph不一致的情况，正常版本一致。

复现代码：

```
import oneflow as flow
import numpy as np 

#x = np.array([-0.5, 0, 0.5]).astype(np.float32)
x=flow.randn(1, 4, 6, 7, 6)


input = flow.Tensor(x).to("cuda")
# hardsigmoid = flow.nn.Hardsigmoid()
# out = hardsigmoid(input)

# print(out)


out2 = flow.nn.functional.hardsigmoid(input,True).to("cuda")
print(out2)

print("-------------------------------------")

def model(x):
    return flow.nn.functional.hardsigmoid(x,True).to("cuda")

class Graph(flow.nn.Graph):
    def __init__(self):
        super().__init__()
        self.m=model

    def build(self,x):
        out = self.m(x)
        return out

graph=Graph()
out3=graph(input)

print(out3)
```

**Comment by strint** [comment]
graph的非Inplace结果也更新下看看

**Comment by strint** [comment]
```
out2_ = flow.nn.functional.hardsigmoid(input,True).to("cuda")
```
这一行，因为是Inplace执行，所以把input给改了，你可以打印下看看。

这个input再给graph时，graph的输入和eager输入已经不一样了。大概率是这个原因。

**Comment by lixiang007666** [comment]
> 

确实是这个原因～

**Comment by strint** [comment]
需要把graph的输入，deepcopy一下。

参考写法：https://github.com/Oneflow-Inc/oneflow/pull/7270/files#diff-d47cb1e379a82c3ca695ecc96762868fbecabc350e4dc5c35b15d5f62f0381e2R330
