### ISSUE TITLE
[Bug]Numpy data type 0 is not valid to OneFlow data type

### ISSUE THREAD

**Issue by mc622426** [Oneflow-Inc/oneflow#7314]
## System Information

- What is your OneFlow installation (pip, source, dockerhub):python3 -m pip install -f https://release.oneflow.info oneflow==0.5.0+cu112
- OS:Ubuntu 16.04.6 LTS
- Python version:3.8
- CUDA driver version:V11.2

[代码位置](https://gitee.com/zhijiangtianshu/ts-cv/tree/master/Visions/segmentation/FaceSeg)
报错信息：
```
 File "train.py", line 95, in main
    label = flow.Tensor(label_nd, dtype=flow.float32, requires_grad=False)
oneflow._oneflow_internal.exception.TypeException: 
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/api/python/functional/py_function.h", line 69, in call
    TypeError: _legacy_tensor_ctor(): received an invalid combination of arguments. The valid signatures are:
	*0: Tensor (*, Device device=None)
	*1: Tensor (*, Placement placement, SbpList sbp)
	*2: Tensor (Tensor other)
	*3: Tensor (PyObject* data, *, Device device=None)
	*4: Tensor (PyObject* data, *, Placement placement, SbpList sbp)
	*5: Tensor (Shape size, *, Device device=None)
	*6: Tensor (Shape size, *, Placement placement, SbpList sbp)
train.sh: line 25: 28619 Aborted                 python3 train.py --learning_rate $LEARNING_RATE --mom $MOM --epochs $EPOCH --model_path $MODEL_PATH --dataset_path $DATASET_PATH --save_model_name $SAVE_MODEL_NAME   
```
按照给出的提示，将line 95改为 `label = flow.tensor(label_nd, dtype=flow.float32, requires_grad=False)`
会出现如下报错：
```
Traceback (most recent call last):
  File "train.py", line 124, in <module>
    main(args)
  File "train.py", line 101, in main
    loss = criterion(mask_probs_flat, true_masks_flat)
  File "train.py", line 52, in __call__
    jaccard_target = flow.tensor((targets.numpy() == 1)).to(flow.device("cuda"))
oneflow._oneflow_internal.exception.InvalidValueException: 
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/api/python/utils/tensor_utils.cpp", line 147, in MakeLocalTensorFromData
    numpy::GetOFDataTypeFromNpArray(np_arr)
Numpy data type 0 is not valid to OneFlow data type.

```

**Comment by mc622426** [comment]
System Information
What is your OneFlow installation (pip, source, dockerhub):python3 -m pip install -f https://release.oneflow.info oneflow==0.5.0+cu112
Python version:3.8
CUDA driver version:V7.5.17

代码位置：[https://gitee.com/zhijiangtianshu/ts-cv/tree/master/Visions/segmentation/FaceSeg]
报错信息：
```
File "train.py", line 95, in main
label = flow.Tensor(label_nd, dtype=flow.float32, requires_grad=False)
oneflow._oneflow_internal.exception.TypeException:
File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/api/python/functional/py_function.h", line 69, in call
TypeError: _legacy_tensor_ctor(): received an invalid combination of arguments. The valid signatures are:
0: Tensor (, Device device=None)
1: Tensor (, Placement placement, SbpList sbp)
*2: Tensor (Tensor other)
3: Tensor (PyObject data, *, Device device=None)
4: Tensor (PyObject data, *, Placement placement, SbpList sbp)
*5: Tensor (Shape size, *, Device device=None)
*6: Tensor (Shape size, *, Placement placement, SbpList sbp)
train.sh: line 25: 28619 Aborted python3 train.py --learning_rate $LEARNING_RATE --mom $MOM --epochs $EPOCH --model_path $MODEL_PATH --dataset_path $DATASET_PATH --save_model_name $SAVE_MODEL_NAME

```
按照给出的提示，将line 95改为 `label = flow.tensor(label_nd, dtype=flow.float32, requires_grad=False)`
会出现如下报错：
```
Traceback (most recent call last):
  File "train.py", line 124, in <module>
    main(args)
  File "train.py", line 101, in main
    loss = criterion(mask_probs_flat, true_masks_flat)
  File "train.py", line 52, in __call__
    jaccard_target = flow.tensor((targets.numpy() == 1)).to(flow.device("cuda"))
oneflow._oneflow_internal.exception.InvalidValueException: 
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/api/python/utils/tensor_utils.cpp", line 147, in MakeLocalTensorFromData
    numpy::GetOFDataTypeFromNpArray(np_arr)
Numpy data type 0 is not valid to OneFlow data type.
```

**Comment by strint** [comment]
> Numpy data type 0 is not valid to OneFlow data type.

https://github.com/numpy/numpy/blob/main/numpy/core/include/numpy/ndarraytypes.h#L65

看起来我们没有支持bool。

`label_nd` 转换成 float来计算？ @MARD1NO

**Comment by strint** [comment]
解决办法

```
>>> import numpy
# 创建 numpy bool ndarray
>>> lable_nd = numpy.ones((2, 2), dtype=bool)
>>> lable_nd
array([[ True,  True],
       [ True,  True]])

# 从numpy bool 转到oneflow Tensor，有兼容错误
>>> import oneflow as flow
>>> label = flow.Tensor(label_nd, dtype=flow.float32, requires_grad=False)                                                                                                                                  
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
oneflow._oneflow_internal.exception.TypeException: 
  File "/home/xuxiaoyu/oneflow/oneflow/api/python/functional/py_function.h", line 76, in call
    TypeError: _legacy_tensor_ctor(): received an invalid combination of arguments. The valid signatures are:
        *0: Tensor (*, Device device=None)
        *1: Tensor (*, Placement placement, SbpList sbp)
        *2: Tensor (Tensor other)
        *3: Tensor (PyObject* data, *, Device device=None)
        *4: Tensor (PyObject* data, *, Placement placement, SbpList sbp)
        *5: Tensor (Shape size, *, Device device=None)
        *6: Tensor (Shape size, *, Placement placement, SbpList sbp)

# flow.Tensor改为flow.tensor，有bool numpy data 到oneflow tensor的错误，bool类型不支持
>>> label = flow.tensor(label_nd, dtype=flow.float32, requires_grad=False)                                                                                                                                  
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
oneflow._oneflow_internal.exception.InvalidValueException: 
  File "/home/xuxiaoyu/oneflow/oneflow/api/python/utils/tensor_utils.cpp", line 147, in MakeLocalTensorFromData
    numpy::GetOFDataTypeFromNpArray(np_arr)
Numpy data type 0 is not valid to OneFlow data type.

# bool numpy类型转为int类型
>>> label_nd_int = label_nd.astype(int)                                                                                                                                                                     
>>> label_nd_int
array([[1, 1],
       [1, 1]])

# int numpy 转为oneflow tensor
>>> label = flow.tensor(label_nd_int, dtype=flow.float32, requires_grad=False)                                                                                                                              
>>> label
tensor(..., size=(2, 2), dtype=oneflow.float32)
```

**Comment by strint** [comment]
这里和bool关联的问题，因为targets本身是tensor，所以更直接的解决办法：
```
jaccard_target = flow.tensor((targets.numpy() == 1)).to(flow.device("cuda"))
```
改成
```
jaccard_target = (targets == 1)
```

**Comment by mc622426** [comment]
@strint 解决！
