### ISSUE TITLE
[BUG] NLLLoss打开Graph测试报错

### ISSUE THREAD

**Issue by lixiang007666** [Oneflow-Inc/oneflow#7374]
## Summary
背景：Graph模式支持所有Op单测项目

NLLLoss设置check_graph=True报错，NLLLoss需要接收multi tensor，报错内容大概信息为multi-input tensor使用的device不同：

```cpp
(base) lixiang@oneflow-21:~/oneflow/python/oneflow/test/modules$ python3 -m unittest test_loss.TestNLLLossModule.test_nll_loss_with_random_data_dim_2
Environment has been initialized, this env init will do nothing.
/home/lixiang/anaconda3/lib/python3.8/site-packages/torch/_tensor.py:1013: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  aten/src/ATen/core/TensorBody.h:417.)
  return self._grad
[ERROR](GRAPH:TestGraphOfModule_1:TestGraphOfModule) building graph got error: <class 'oneflow._oneflow_internal.exception.CheckFailedException'> 
  File "/home/lixiang/oneflow/oneflow/core/functional/impl/nn_functor.cpp", line 699, in operator()
    OpInterpUtil::Dispatch<TensorTuple>(*op_weight_, {input_ ... Data_YouAreNotAllowedToCallThisFuncOutsideThisFile()}, attrs)
  File "/home/lixiang/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 131, in Dispatch<oneflow::one::TensorTuple>
    Dispatch(op_expr, inputs, outputs.get(), ctx)
  File "/home/lixiang/oneflow/oneflow/core/framework/op_interpreter/op_interpreter.cpp", line 96, in Apply
    internal_->Apply(op_expr, inputs, outputs, ctx)
  File "/home/lixiang/oneflow/oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp", line 634, in ApplyImpl
    Check failed: device_tag == GetDeviceTagOfTensor(input_tensor)  Lazy nn.Graph name : TestGraphOfModule_1 encountered ERROR where multi-input tensor has different device type in module/op_name: test_module-nll-2. Please use tensor.to() or tensor.to_consistent() to make all input with same device.
E
======================================================================
ERROR: test_nll_loss_with_random_data_dim_2 (test_loss.TestNLLLossModule)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lixiang/oneflow/python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 836, in new_f
    res = f(test_case, *args, **kwargs)
  File "/home/lixiang/oneflow/python/oneflow/test/modules/test_loss.py", line 149, in test_nll_loss_with_random_data_dim_2
    return test_nll_loss(2)
  File "/home/lixiang/oneflow/python/oneflow/test/modules/test_loss.py", line 141, in test_nll_loss
    y = m(x, target)
  File "/home/lixiang/oneflow/python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 393, in dual_method
    test_g_res = test_g(*graph_args)
  File "/home/lixiang/oneflow/python/oneflow/nn/graph/graph.py", line 258, in __call__
    self._compile(*args)
  File "/home/lixiang/oneflow/python/oneflow/nn/graph/graph.py", line 506, in _compile
    eager_outputs = self._build_graph(*args)
  File "/home/lixiang/oneflow/python/oneflow/nn/graph/graph.py", line 598, in _build_graph
    outputs = self.build(*lazy_args)
  File "/home/lixiang/oneflow/python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 378, in build
    res = self.test_module(*args)
  File "/home/lixiang/oneflow/python/oneflow/nn/graph/block.py", line 209, in __call__
    result = self.__block_forward(*args)
  File "/home/lixiang/oneflow/python/oneflow/nn/graph/block.py", line 241, in __block_forward
    result = self._origin.__class__.forward(self, *args)
  File "/home/lixiang/oneflow/python/oneflow/nn/modules/loss.py", line 332, in forward
    return flow._C.nll_loss(
oneflow._oneflow_internal.exception.CheckFailedException: 
  File "/home/lixiang/oneflow/oneflow/core/functional/impl/nn_functor.cpp", line 699, in operator()
    OpInterpUtil::Dispatch<TensorTuple>(*op_weight_, {input_ ... Data_YouAreNotAllowedToCallThisFuncOutsideThisFile()}, attrs)
  File "/home/lixiang/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 131, in Dispatch<oneflow::one::TensorTuple>
    Dispatch(op_expr, inputs, outputs.get(), ctx)
  File "/home/lixiang/oneflow/oneflow/core/framework/op_interpreter/op_interpreter.cpp", line 96, in Apply
    internal_->Apply(op_expr, inputs, outputs, ctx)
  File "/home/lixiang/oneflow/oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp", line 634, in ApplyImpl
    Check failed: device_tag == GetDeviceTagOfTensor(input_tensor)  Lazy nn.Graph name : TestGraphOfModule_1 encountered ERROR where multi-input tensor has different device type in module/op_name: test_module-nll-2. Please use tensor.to() or tensor.to_consistent() to make all input with same device.
```

## Code to reproduce bug

**测试代码：**
```cpp
    @autotest(check_graph=True)
    def test_nll_loss_with_random_data_dim_2(test_case):
        return test_nll_loss(2)
```

**test_nll_loss：**

```cpp
def test_nll_loss(dim=int):
    (
        x,
        target,
        weight,
        ignore_index,
        device,
    ) = generate_necessity_for_cross_entropy_or_nll_loss(dim)
    m = torch.nn.NLLLoss(
        weight=oneof(weight, nothing()),
        reduction=oneof("none", "sum", "mean", nothing()),
        ignore_index=ignore_index,
    )
    m.train(random())
    m.to(device)

    y = m(x, target)
    return y
```

**generate_necessity_for_cross_entropy_or_nll_loss：**

```cpp
def generate_necessity_for_cross_entropy_or_nll_loss(dim: int):
    if dim > 5 or dim < 2:
        raise ValueError("dim should be less than 5 or greater than 1. ")
    device = random_device()
    num_classes = random(low=2).to(int)
    batch_size = random(low=10, high=100).to(int)
    ignore_index = (
        random(0, num_classes).to(int) | nothing()
        if num_classes.value() > 2
        else nothing()
    )
    extra_dim = [random().to(int) for _ in range(dim - 2)]
    return (
        random_pytorch_tensor(dim, batch_size, num_classes, *extra_dim).to(device),
        random_pytorch_tensor(
            dim - 1,
            batch_size,
            *extra_dim,
            low=0,
            high=num_classes,
            dtype=int,
            requires_grad=False,
        ).to(device),
        random_pytorch_tensor(1, num_classes, low=0, high=3, requires_grad=False).to(
            device
        ),
        ignore_index,
        device,
    )
```

**Comment by lixiang007666** [comment]
@strint

**Comment by lixiang007666** [comment]
还有好多其他的case都会在`Please use tensor.to() or tensor.to_consistent() to make all input with same device.` 这个check报错。

**Comment by strint** [comment]
> 还有好多其他的case都会在`Please use tensor.to() or tensor.to_consistent() to make all input with same device.` 这个check报错。

尝试确认下`flow._C.nll_loss`的各个输入的device，应该是这里出问题了
