### ISSUE TITLE
[BUG]Numpy data type 9 is not valid to OneFlow data type.

### ISSUE THREAD

**Issue by lixiang007666** [Oneflow-Inc/oneflow#7397]
## Summary

背景：Graph模式支持Op单测。

关联PR：https://github.com/Oneflow-Inc/oneflow/pull/7373

在autotest框架中，有`graph_functional_oneflow = copy.deepcopy(oneflow)`的需求，但是会导致下面的错误。

```cpp
(base) lixiang@oneflow-21:~/oneflow/python/oneflow/test/modules$ python3 -m unittest test_tensor_ops.TestTensorOps.test_double
Environment has been initialized, this env init will do nothing.
Before running eager module or functional:  <bound method _to of tensor([0], dtype=oneflow.int64)>
_________________ <bound method _to of tensor([0], dtype=oneflow.int64)>
E
======================================================================
ERROR: test_double (test_tensor_ops.TestTensorOps)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lixiang/oneflow/python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 886, in new_f
    res = f(test_case, *args, **kwargs)
  File "/home/lixiang/oneflow/python/oneflow/test/modules/test_tensor_ops.py", line 122, in test_double
    x = random_pytorch_tensor(dtype=int).to(device)
  File "/home/lixiang/oneflow/python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 358, in dual_method
    graph_functional_oneflow = copy.deepcopy(oneflow)
  File "/home/lixiang/anaconda3/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/lixiang/anaconda3/lib/python3.8/copy.py", line 237, in _deepcopy_method
    return type(x)(x.__func__, deepcopy(x.__self__, memo))
  File "/home/lixiang/anaconda3/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/lixiang/anaconda3/lib/python3.8/copy.py", line 272, in _reconstruct
    y.__setstate__(state)
  File "/home/lixiang/oneflow/python/oneflow/framework/check_point_v2.py", line 217, in tensor_setstate
    flow.tensor(pickle_dict["data"], dtype=pickle_dict["dtype"])
oneflow._oneflow_internal.exception.InvalidValueException: 
  File "/home/lixiang/oneflow/oneflow/api/python/utils/tensor_utils.cpp", line 154, in MakeLocalTensorFromData
    numpy::GetOFDataTypeFromNpArray(np_arr)
Numpy data type 9 is not valid to OneFlow data type.

----------------------------------------------------------------------
Ran 1 test in 0.015s

FAILED (errors=1)
```

## Code to reproduce bug

与`graph_functional_oneflow = copy.deepcopy(oneflow)`相关的代码：

```cpp
                            if verbose:
                                print(
                                    "Before running eager module or functional: ",
                                    repr(oneflow),
                                )
                            if testing_graph:
                                print("_________________",oneflow)
                                graph_functional_oneflow = copy.deepcopy(oneflow)
                                print("_________________",graph_functional_oneflow)
                            oneflow_res = oneflow(*oneflow_args, **oneflow_kwargs)
                            if verbose:
                                print(
                                    "The result after running eager module or functional: ",
                                    oneflow_res,
                                )

···
···
···
                                    class TestGraphOfFunctional(flow.nn.Graph):
                                        def __init__(self):
                                            super().__init__()

                                        def build(self):
                                            return graph_functional_oneflow(
                                                *graph_args, **graph_kwargs
                                            )
```

测试的代码：

```cpp
    @autotest(n=1, auto_backward=False, rtol=1e-4, atol=1e-4, check_graph=True)
    def test_double(test_case):
        device = random_device()
        x = random_pytorch_tensor(dtype=int).to(device)
        y = x.double()
        return y
```
还有很多case也会报相同的错误，直接使用deepcopy()导致了这些问题。

**Comment by lixiang007666** [comment]
@strint @BBuf

**Comment by strint** [comment]
我用deepcopy构造测试，也遇到类似的问题。

是我们numpy到tensor没有支持`NPY_LONGLONG`，https://github.com/numpy/numpy/blob/main/numpy/core/include/numpy/ndarraytypes.h#L65

看起来`NPY_LONGLONG`对应int64，https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.longlong 

我们把它对应到`DataType::kInt64`应该就好了。

torch也是这么处理的：https://github.com/pytorch/pytorch/blob/master/torch/csrc/utils/tensor_numpy.cpp#L279-L283

我下午试下，然后告诉你。

**Comment by strint** [comment]
参考这个：https://github.com/Oneflow-Inc/oneflow/commit/85703383f83d964478b2c613130096304bb5cd68

在你的开发分支改下就好。
