### ISSUE TITLE
[BUG]tensor.numpy() is not allowed to called in nn.Graph.build(*args) or called by lazy tensor.

### ISSUE THREAD

**Issue by lixiang007666** [Oneflow-Inc/oneflow#7410]
## Summary

背景：Graph模式支持Op单测。

测试nonzero，打开Graph抛出OneFlowGraphBuildOrRunError，具体报错信息：

```cpp
(base) lixiang@oneflow-22:~/oneflow/python/oneflow/test/modules$ python3 -m unittest test_nonzero.TestNonzero.test_nonzero_with_random_data
Environment has been initialized, this env init will do nothing.
test_nonzero_with_random_data
PyTorch error: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Before running eager module or functional:  <bound method _to of tensor([[[0.9585, 0.4271, 0.9146, 0.7771],
         [0.3000, 0.5399, 0.5360, 0.4506],
         [0.2291, 0.6072, 0.1752, 0.8274],
         [0.7133, 0.9009, 0.7626, 0.1241]]], dtype=oneflow.float32,
       requires_grad=True)>
The result after running eager module or functional:  tensor([[[0.9585, 0.4271, 0.9146, 0.7771],
         [0.3000, 0.5399, 0.5360, 0.4506],
         [0.2291, 0.6072, 0.1752, 0.8274],
         [0.7133, 0.9009, 0.7626, 0.1241]]], dtype=oneflow.float32,
       requires_grad=True)
After running eager module or functional:  <bound method _to of tensor([[[0.9585, 0.4271, 0.9146, 0.7771],
         [0.3000, 0.5399, 0.5360, 0.4506],
         [0.2291, 0.6072, 0.1752, 0.8274],
         [0.7133, 0.9009, 0.7626, 0.1241]]], dtype=oneflow.float32,
       requires_grad=True)>
Run graph of function:  <bound method _to of tensor([[[0.9585, 0.4271, 0.9146, 0.7771],
         [0.3000, 0.5399, 0.5360, 0.4506],
         [0.2291, 0.6072, 0.1752, 0.8274],
         [0.7133, 0.9009, 0.7626, 0.1241]]], dtype=oneflow.float32,
       requires_grad=True)> , graph check is intentionally skiped.
Before running eager module or functional:  <function nonzero_op at 0x7f79d0051790>
The result after running eager module or functional:  tensor([[0, 0, 0],
        [0, 0, 1],
        [0, 0, 2],
        [0, 0, 3],
        [0, 1, 0],
        [0, 1, 1],
        [0, 1, 2],
        [0, 1, 3],
        [0, 2, 0],
        [0, 2, 1],
        [0, 2, 2],
        [0, 2, 3],
        [0, 3, 0],
        [0, 3, 1],
        [0, 3, 2],
        [0, 3, 3]], dtype=oneflow.int32)
After running eager module or functional:  <function nonzero_op at 0x7f79d0051790>
Run graph of function:  <function nonzero_op at 0x7f79d0051790>
(GRAPH:TestGraphOfFunctional_0:TestGraphOfFunctional) start building graph.
(GRAPH:TestGraphOfFunctional_0:TestGraphOfFunctional) start building graph builders of parameters and buffers.
(GRAPH:TestGraphOfFunctional_0:TestGraphOfFunctional) end building graph builders of parameters and buffers.
(GRAPH:TestGraphOfFunctional_0:TestGraphOfFunctional) start building graph inputs.
(GRAPH:TestGraphOfFunctional_0:TestGraphOfFunctional) end building graph inputs.
(GRAPH:TestGraphOfFunctional_0:TestGraphOfFunctional) start building graph modules.
[ERROR](GRAPH:TestGraphOfFunctional_0:TestGraphOfFunctional) building graph got error: <class 'AssertionError'> tensor.numpy() is not allowed to called in nn.Graph.build(*args) or called by lazy tensor.
Tensor([1, 4, 4]).to(cpu)
nonzero(Tensor([1, 4, 4]))
-----------------------------------------------------------
This program has 1 input tensor: 
Shape[1, 4, 4]
tensor([[[0.9585, 0.4271, 0.9146, 0.7771],
         [0.3000, 0.5399, 0.5360, 0.4506],
         [0.2291, 0.6072, 0.1752, 0.8274],
         [0.7133, 0.9009, 0.7626, 0.1241]]], requires_grad=True)
-----------------------------------------------------------
E
======================================================================
ERROR: test_nonzero_with_random_data (test_nonzero.TestNonzero)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lixiang/oneflow/python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 491, in dual_method
    test_g_res = test_g()
  File "/home/lixiang/oneflow/python/oneflow/nn/graph/graph.py", line 258, in __call__
    self._compile(*args)
  File "/home/lixiang/oneflow/python/oneflow/nn/graph/graph.py", line 506, in _compile
    eager_outputs = self._build_graph(*args)
  File "/home/lixiang/oneflow/python/oneflow/nn/graph/graph.py", line 598, in _build_graph
    outputs = self.build(*lazy_args)
  File "/home/lixiang/oneflow/python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 441, in build
    return graph_functional_oneflow(
  File "/home/lixiang/oneflow/python/oneflow/nn/modules/nonzero.py", line 29, in nonzero_op
    slice_tup_list = [[0, int(size.numpy()), 1]]
  File "/home/lixiang/oneflow/python/oneflow/framework/tensor.py", line 951, in _numpy
    assert (
AssertionError: tensor.numpy() is not allowed to called in nn.Graph.build(*args) or called by lazy tensor.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lixiang/oneflow/python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 894, in new_f
    res = f(test_case, *args, **kwargs)
  File "/home/lixiang/oneflow/python/oneflow/test/modules/test_nonzero.py", line 64, in test_nonzero_with_random_data
    y = torch.nonzero(x)
  File "/home/lixiang/oneflow/python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 499, in dual_method
    raise OneFlowGraphBuildOrRunError(e)
oneflow.test_utils.automated_test_util.torch_flow_dual_object.OneFlowGraphBuildOrRunError: OneFlow nn.Graph Build Or Run Error: tensor.numpy() is not allowed to called in nn.Graph.build(*args) or called by lazy tensor.

```

也有很多case报相同的错误。

## Code to reproduce bug

**测试代码：**

```python
    @autotest(auto_backward=False, check_graph=True)
    def test_nonzero_with_random_data(test_case):
        device = random_device()
        x = random_pytorch_tensor(ndim=random(2, 5).to(int)).to(device)
        y = torch.nonzero(x)
        return y

```

**Comment by strint** [comment]
```
AssertionError: tensor.numpy() is not allowed to called in nn.Graph.build(*args) or called by lazy tensor.
```

这是一个已知的约束。lazy-tensor.numpy() 是一个graph下未定义的行为。

处理方法是单测中个，看能否把numpy方法去掉，按说是不需要的。

**Comment by lixiang007666** [comment]
补充：

nonzero在python层的实现如下：
```python
def nonzero_op(input, as_tuple=False):
    if as_tuple and not input.ndim:
        input = input.unsqueeze(0)
    (res, size) = flow._C.argwhere(input)
    slice_tup_list = [[0, int(size.numpy()), 1]]
    res = flow.slice(res, slice_tup_list=slice_tup_list)
    if as_tuple:
        return tuple([flow._C.transpose(res, [1, 0])[x] for x in range(res.shape[1])])
    else:
        return res
```
问题可能出在`slice_tup_list = [[0, int(size.numpy()), 1]]`这行代码，lazy tensor不能调用`.numpy()`。

**这里是后续需要改进的地方**，故暂时将nonzero的check graph设置为ValidatedFlase
