### ISSUE TITLE
nn.Graph only accept lazy tensor to call backward() in lazy mode.

### ISSUE THREAD

**Issue by lixiang007666** [Oneflow-Inc/oneflow#7463]
## Summary

问题背景：Graph模式支持所有Op单测项目。

打开MaxPool的Graph测试报错。` OneFlow nn.Graph Build Or Run Error: nn.Graph only accept lazy tensor to call backward() in lazy mode.`

## Code to reproduce bug

测试代码如下：

```python
    @autotest(auto_backward=False, check_graph=True)
    def test_maxpool1d_with_random_data(test_case):
        return_indices = False
        m = torch.nn.MaxPool1d(
            kernel_size=random(4, 6).to(_size_1_t),
            stride=random(1, 3).to(_size_1_t) | nothing(),
            padding=random(1, 3).to(_size_1_t) | nothing(),
            dilation=random(2, 4).to(_size_1_t) | nothing(),
            ceil_mode=random(),
            return_indices=return_indices,
        )
        m.train(random())
        device = random_device()
        m.to(device)
        x = random_tensor(ndim=3, dim2=random(20, 22)).to(device)
        y = m(x)
        # if return_indices:
        #     return unpack_indices(y)
        # else:
        return y, y.sum().backward() #只考虑return_indices = False
```

**因为.backward()，所以会导致测试抛出下面的错误：**

```powershell
(base) lixiang@oneflow-23:~/oneflow/python/oneflow/test/modules$ python3 -m unittest test_maxpool.TestMaxPooling.test_maxpool1d_with_random_data
Environment has been initialized, this env init will do nothing.
[ERROR](GRAPH:TestGraphOfFunctional_1:TestGraphOfFunctional) building graph got error: <class 'AssertionError'> nn.Graph only accept lazy tensor to call backward() in lazy mode.
MaxPool1d(kernel_size=[4], stride=2, ceil_mode=True, return_indices=False)
Module.train(False)
Module.to(cpu)
Tensor([1, 1, 20]).to(cpu)
MaxPool1d(kernel_size=[4], stride=2, padding=0, dilation=1, ceil_mode=True)(Tensor([1, 1, 20]))
Tensor([1, 1, 9]).sum()
Tensor([]).backward()
-----------------------------------------------------------
This program has 1 input tensor: 
Shape[1, 1, 20]
tensor([[[0.8959, 0.6950, 0.3241, 0.0732, 0.7888, 0.6403, 0.9810, 0.5341,
          0.0126, 0.7041, 0.6872, 0.6552, 0.3578, 0.8817, 0.6402, 0.1652,
          0.4868, 0.3563, 0.3015, 0.3118]]], requires_grad=True)
-----------------------------------------------------------
E
======================================================================
ERROR: test_maxpool1d_with_random_data (test_maxpool.TestMaxPooling)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lixiang/oneflow/python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 492, in dual_method
    test_g_res = test_g()
  File "/home/lixiang/oneflow/python/oneflow/nn/graph/graph.py", line 263, in __call__
    self._compile(*args, **kwargs)
  File "/home/lixiang/oneflow/python/oneflow/nn/graph/graph.py", line 511, in _compile
    eager_outputs = self.__build_graph(*args, **kwargs)
  File "/home/lixiang/oneflow/python/oneflow/nn/graph/graph.py", line 603, in __build_graph
    outputs = self.build(*lazy_args, **lazy_kwargs)
  File "/home/lixiang/oneflow/python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 446, in build
    return graph_functional_oneflow(
  File "/home/lixiang/oneflow/python/oneflow/framework/tensor.py", line 58, in _backward
    assert (
AssertionError: nn.Graph only accept lazy tensor to call backward() in lazy mode.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lixiang/oneflow/python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 903, in new_f
    res = f(test_case, *args, **kwargs)
  File "/home/lixiang/oneflow/python/oneflow/test/modules/test_maxpool.py", line 85, in test_maxpool1d_with_random_data
    return y, y.sum().backward()
  File "/home/lixiang/oneflow/python/oneflow/test_utils/automated_test_util/torch_flow_dual_object.py", line 500, in dual_method
    raise OneFlowGraphBuildOrRunError(e)
oneflow.test_utils.automated_test_util.torch_flow_dual_object.OneFlowGraphBuildOrRunError: OneFlow nn.Graph Build Or Run Error: nn.Graph only accept lazy tensor to call backward() in lazy mode.
```

**Comment by lixiang007666** [comment]
@strint

**Comment by strint** [comment]
```
return y, y.sum().backward() 
```
backward() 没有返回值，不懂这里返回backward有什么意义。

请 @BBuf 帮忙看看，这个是不是可以去掉。

**Comment by BBuf** [comment]
> ```
> .backward() 
> ```
> 
> 
>     
> 
>   
> 
> backward() 没有返回值，不懂这里返回backward有什么意义。

我也不清楚为什么要这样写，我感觉直接开一下auto_backward=True就可以了。
