### ISSUE TITLE
weight_norm, nn.Graph.build()'s input/output item only support types: Tensor/None.

### ISSUE THREAD

**Issue by lixiang007666** [Oneflow-Inc/oneflow#7466]
## Summary

问题背景：Graph模式支持所有Op单测项目。

weight_norm的Graph检查抛出错误: `NotImplementedError: nn.Graph.build()'s input/output item only support types: Tensor/None.`

## Code to reproduce bug
测试的代码如下：

```python
import oneflow as flow
import numpy as np 

m = flow.nn.utils.weight_norm(flow.nn.Linear(5, 4), name='weight',dim=1)
print(m.weight_g.size())

def model(x):
    return flow.nn.utils.weight_norm(x, name='weight',dim=1)

class WeightNormGraph(flow.nn.Graph):
    def __init__(self):
        super().__init__()
        self.m=model

    def build(self,x):
        out = self.m(x)
        return out

graph=WeightNormGraph()
out=graph(flow.nn.Linear(5, 4))
print(out.weight_g.size())


```
错误信息：

```powershell
(base) lixiang@oneflow-23:~/test$ python3 test_weight_norm.py 
oneflow.Size([1, 5])
[ERROR](INPUT:_WeightNormGraph_0_input.0.0_2:<class 'oneflow.nn.modules.linear.Linear'>)
[ERROR](GRAPH:WeightNormGraph_0:WeightNormGraph) building graph got error: <class 'NotImplementedError'> nn.Graph.build()'s input/output item only support types: Tensor/None.
Traceback (most recent call last):
  File "test_weight_norm.py", line 20, in <module>
    out=graph(flow.nn.Linear(5, 4))
  File "/home/lixiang/oneflow/python/oneflow/nn/graph/graph.py", line 263, in __call__
    self._compile(*args, **kwargs)
  File "/home/lixiang/oneflow/python/oneflow/nn/graph/graph.py", line 511, in _compile
    eager_outputs = self.__build_graph(*args, **kwargs)
  File "/home/lixiang/oneflow/python/oneflow/nn/graph/graph.py", line 596, in __build_graph
    arg_op_names, lazy_args, lazy_kwargs, self._args_repr, _ = self.__build_io(
  File "/home/lixiang/oneflow/python/oneflow/nn/graph/graph.py", line 838, in __build_io
    out = io_node.map_leaf(leaf_node_fn)
  File "/home/lixiang/oneflow/python/oneflow/nn/graph/util.py", line 157, in map_leaf
    l_value.append(node.map_leaf(leaf_node_fn))
  File "/home/lixiang/oneflow/python/oneflow/nn/graph/util.py", line 157, in map_leaf
    l_value.append(node.map_leaf(leaf_node_fn))
  File "/home/lixiang/oneflow/python/oneflow/nn/graph/util.py", line 169, in map_leaf
    mapped_value = leaf_node_fn(self)
  File "/home/lixiang/oneflow/python/oneflow/nn/graph/graph.py", line 834, in leaf_node_fn
    arg_repr = self.__io_item_check_and_gen_repr(
  File "/home/lixiang/oneflow/python/oneflow/nn/graph/graph.py", line 880, in __io_item_check_and_gen_repr
    raise NotImplementedError(
NotImplementedError: nn.Graph.build()'s input/output item only support types: Tensor/None.
```

**在Graph的build过程中，输入了nn.modules.linear.Linear类型。所以weight_norm单侧的check_graph先设置成"ValidatedFlase"吗？**

**Comment by lixiang007666** [comment]
@strint

**Comment by strint** [comment]
是的，build接口输入module，是明确不支持的。

这个先标记为"ValidatedFlase"吧。
