### ISSUE TITLE
BatchNorm1d的Bug：TypeError: normalization(): argument 'gamma' must be tensor, not NoneType

### ISSUE THREAD

**Issue by ZiqiuChi** [Oneflow-Inc/oneflow#7740]
在复现MOCOV3过程中发现，相关PR： https://github.com/Oneflow-Inc/libai/pull/160

复现如下：

```
# import oneflow as flow
# import oneflow.nn as nn

import torch as flow
import torch.nn as nn

class DemoNet(nn.Module):
    def __init__(self) -> None:
        super(DemoNet, self).__init__()

        self.linear = nn.Sequential(
            nn.Linear(10,10),
            nn.ReLU(),
            nn.BatchNorm1d(10, affine=False),
            nn.Linear(10,1)
        )

    def forward(self,x):
        
        return self.linear(x)


model = DemoNet()

x = flow.randn(16,10)
y = flow.ones(16,1)

y_hat = model(x)
```

在torch中，nn.BatchNorm1d(10, affine=False)中设置affine=True或False没问题。

在oneflow中，当设置affine=False时前向计算会报错：

```
Traceback (most recent call last):
  File "projects/demo_bn1d.py", line 25, in <module>
    y_hat = model(x)
  File "/dataset/czq_home/anaconda3/envs/libai/lib/python3.7/site-packages/oneflow/nn/module.py", line 87, in __call__
    res = self.forward(*args, **kwargs)
  File "projects/demo_bn1d.py", line 17, in forward
    return self.linear(x)
  File "/dataset/czq_home/anaconda3/envs/libai/lib/python3.7/site-packages/oneflow/nn/module.py", line 87, in __call__
    res = self.forward(*args, **kwargs)
  File "/dataset/czq_home/anaconda3/envs/libai/lib/python3.7/site-packages/oneflow/nn/utils/container.py", line 99, in forward
    input = module(input)
  File "/dataset/czq_home/anaconda3/envs/libai/lib/python3.7/site-packages/oneflow/nn/module.py", line 87, in __call__
    res = self.forward(*args, **kwargs)
  File "/dataset/czq_home/anaconda3/envs/libai/lib/python3.7/site-packages/oneflow/nn/modules/batchnorm.py", line 122, in forward
    is_training=is_training,
oneflow._oneflow_internal.exception.TypeException: 
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/api/python/functional/py_function.cpp", line 98, in ParseArgs
    TypeError: normalization(): argument 'gamma' must be tensor, not NoneType
```

版本：

```
'0.7.0.dev20220228+cu112'
```

**Comment by MARD1NO** [comment]
这个问题是因为我们的normalization系列没有给weight，bias这两个Tensor设置为Optional，以往的情况我们默认都是affine=True，后续需要修改下这个实现

**Comment by ZiqiuChi** [comment]
> 这个问题是因为我们的normalization系列没有给weight，bias这两个Tensor设置为Optional，以往的情况我们默认都是affine=True，后续需要修改下这个实现

好的~
