### ISSUE TITLE
Dry run with WORLD_SIZE>1 can't be recognized by oneflow

### ISSUE THREAD

**Issue by SoloGao** [Oneflow-Inc/oneflow#8018]
## Summary

Dry run with WORLD_SIZE>1 can't be recognized by oneflow

> Traceback (most recent call last):
  File "/workspace/AlexNet-Graph.py", line 24, in <module>
    input = flow.randn(64,10,placement=flow.placement("cpu",[0,1]),sbp=flow.sbp.split(0))
  File "/usr/local/lib/python3.10/site-packages/oneflow/nn/modules/random_ops.py", line 244, in randn_op
    return flow._C.randn(
oneflow._oneflow_internal.exception.CheckFailedException: 
  File "/oneflow-src/oneflow/core/functional/impl/random_functor.cpp", line 185, in operator()
    CheckDeviceIdsIsValid(placement)
  File "/oneflow-src/oneflow/core/job/parallel_desc.cpp", line 500, in RawCheckDeviceIdsIsValid
    placement->CheckDeviceIdsIsValid()
  File "/oneflow-src/oneflow/core/job/parallel_desc.cpp", line 324, in CheckDeviceIdsIsValid
    Check failed: (machine_id) < (GlobalProcessCtx::WorldSize()) (1 vs 1) Placment is invalid because rank must be less than world size!

## Code to reproduce bug

```import os
os.environ["ONEFLOW_DEBUG_PASS"] = 'ALL'
os.environ["ONEFLOW_DEBUG_MODE"] = '1'

os.environ["WORLD_SIZE"] = "100"
os.environ["RANK"] = "0"
os.environ["LOCAL_RANK"] = "0"
os.environ["MASTER_ADDR"] = "127.0.0.1"
os.environ["MASTER_PORT"] = "12345"
os.environ["ONEFLOW_DRY_RUN"] = '1'

import oneflow as flow
import oneflow.nn as nn

input = flow.randn(64,10,placement=flow.placement("cpu",[0,1]),sbp=flow.sbp.split(0))
output = flow.randn(64,40,placement=flow.placement("cpu",[0,1]),sbp=flow.sbp.split(1))```

## System Information

- What is your OneFlow installation (pip, source, dockerhub): source
- OS: Debian GNU/Linux 11 (bullseye)
- OneFlow version (run `python3 -m oneflow --doctor`): 0.7.0+cpu
- Python version: 3.10.4
- CUDA driver version: N/A
- GPU models: N/A
- Other info:

**Comment by SoloGao** [comment]
@s14n

**Comment by SoloGao** [comment]
The full code is shown below
```
import os
os.environ["ONEFLOW_DEBUG_PASS"] = 'ALL'
os.environ["ONEFLOW_DEBUG_MODE"] = '1'

os.environ["WORLD_SIZE"] = "100"
os.environ["RANK"] = "0"
os.environ["LOCAL_RANK"] = "0"
os.environ["MASTER_ADDR"] = "127.0.0.1"
os.environ["MASTER_PORT"] = "12345"
os.environ["ONEFLOW_DRY_RUN"] = '1'

import oneflow as flow
import oneflow.nn as nn

DEVICE = "cuda" if flow.cuda.is_available() else "cpu"
print("Using {} device".format(DEVICE))

input = flow.randn(64,10,placement=flow.placement("cpu",[0,1]),sbp=flow.sbp.split(0))
output = flow.randn(64,40,placement=flow.placement("cpu",[0,1]),sbp=flow.sbp.split(1))

class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.layer1 = nn.Linear(10,50)
        self.layer2 = nn.Linear(50,20)
        
        self.layer1.to_global(placement=flow.placement("cpu",[0,1]),sbp=flow.sbp.broadcast)
        self.layer2.to_global(placement=flow.placement("cpu",[0,1]),sbp=flow.sbp.split(0))
    def forward(self, x):
        out_stage0 = self.layer1(x)
        in_stage1 = out_stage0.to_global(placement=flow.placement("cpu",[0,1]),sbp=flow.sbp.broadcast)
        out_stage1 = self.layer2(in_stage1)
        return out_stage1


model = NeuralNetwork()
model = model.to_global(placement=flow.placement("cpu",[0,1]),sbp=flow.sbp.broadcast)

loss_fn = nn.MSELoss()
optimizer = flow.optim.SGD(model.parameters(), lr=1e-3)

class GraphNN(flow.nn.Graph):
    def __init__(self):
        super().__init__()
        self.model = model
        self.loss_fn = loss_fn
        self.add_optimizer(optimizer)

    def build(self, x, y):
        y_pred = self.model(x)
        loss = self.loss_fn(y_pred, y)
        loss.backward()
        return loss


graph_nn = GraphNN()
graph_nn.debug(3)

loss = graph_nn(input, output)
```

**Comment by s14n** [comment]
The ONEFLOW_DRY_RUN is an experimental feature for debug that was temporarily deprecated during refactoring and will be reimplemented later.

**Comment by SoloGao** [comment]
Thanks for the reply! And three more questions:
1. Which version of Oneflow is the most recent ONEFLOW_DRY_RUNable version?
2. Do you have a plan for the time that the ONEFLOW_DRY_RUN be re-implemented?
3. If we can't dry_run, will the easiest way to test a multiple-machine graph generation be manually changing the world_size?  And how?
