### ISSUE TITLE
yolo v4 rebuild erros

### ISSUE THREAD

**Issue by a1056632260** [Oneflow-Inc/oneflow#8202]
## Summary

Dataset erro

## Code to reproduce bug
probably in this area
 target['boxes'] = torch.as_tensor(boxes, dtype=torch.float32)
        target['labels'] = torch.as_tensor(bboxes_with_cls_id[...,-1].flatten(), dtype=torch.int64)
        target['image_id'] = torch.tensor([get_image_id(img_path)])
        target['area'] = (target['boxes'][:,3])*(target['boxes'][:,2])
        target['iscrowd'] = torch.zeros((num_objs,), dtype=torch.int64)

## System Information
oneflow) saxsax@saxsax-ROG-Strix-G513QM-G513QM:~/桌面/pytorch-YOLOv4-master$ /home/saxsax/miniconda3/envs/oneflow/bin/python /home/saxsax/桌面/pytorch-YOLOv4-master/train.py
libibverbs not available, ibv_fork_init skipped
log file path:log/log_2022-05-12_17-30-10.txt
2022-05-12 17:30:10,916 train.py[line:614] INFO: Using device cuda:0
2022-05-12 17:30:12,548 train.py[line:313] INFO: Starting training:
        Epochs:          300
        Batch size:      4
        Subdivisions:    1
        Learning rate:   0.001
        Training size:   408
        Validation size: 102
        Checkpoints:     True
        Device:          cuda
        Images size:     608
        Optimizer:       adam
        Dataset classes: 80
        Train label path:train.txt
        Pretrained:
    
W20220512 17:30:12.550408 31786 tensor_api.cpp:231] OneFlow don't support non-contiguous array now, and we will copy the array to a contiguous one.
Epoch 1/300:   0%|       | 0/408 [00:00<?, ?img/s]
Traceback (most recent call last):
  File "/home/saxsax/桌面/pytorch-YOLOv4-master/train.py", line 626, in <module>
    train(model=model,
  File "/home/saxsax/桌面/pytorch-YOLOv4-master/train.py", line 373, in train
    images = batch[0]
TypeError: 'ExceptionWrapper' object is not subscriptable
- What is your OneFlow installation (pip, source, dockerhub):
- OS:ubuntu20.04
- OneFlow version (run `python3 -m oneflow --doctor`):0.7
- Python version:3.9
- CUDA driver version:11.6
- GPU models:
- Other info:

**Comment by a1056632260** [comment]
I USED  import oneflow as torch
