### ISSUE TITLE
liboneflow.so: undefined symbol: del_curterm

### ISSUE THREAD

**Issue by wangkuiyi** [Oneflow-Inc/oneflow#8398]
On an AWS GPU host, I built OneFlow using conda without using CUDA.  Both the following commands succeeded.

```
cmake .. -C ../cmake/caches/international/cpu.cmake
cmake -j64
```

However, importing `oneflow` in Python 3 complains `ImportError: /home/wkyi/w/oneflow/build/liboneflow.so: undefined symbol: del_curterm`

```
(oneflow-dev-gcc7-v2) [wkyi@ip-172-31-16-248 build]$ source source.sh
(oneflow-dev-gcc7-v2) [wkyi@ip-172-31-16-248 build]$ python3 -m oneflow --doctor
Traceback (most recent call last):
  File "/home/wkyi/anaconda3/envs/oneflow-dev-gcc7-v2/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/wkyi/anaconda3/envs/oneflow-dev-gcc7-v2/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/wkyi/anaconda3/envs/oneflow-dev-gcc7-v2/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/wkyi/w/oneflow/python/oneflow/__init__.py", line 21, in <module>
    import oneflow._oneflow_internal
ImportError: /home/wkyi/w/oneflow/build/liboneflow.so: undefined symbol: del_curterm
```

The host system information is as the following

```
(oneflow-dev-gcc7-v2) [wkyi@ip-172-31-16-248 build]$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

**Comment by daquexian** [comment]
Could you please check out https://github.com/Oneflow-Inc/oneflow/pull/8400 and try again? It works well in my fedora docker container. Thanks!

**Comment by wangkuiyi** [comment]
Thanks @daquexian for the quick fix. Awesome work!

I confirm I can build OneFlow now. And here is my note https://wkyi.quip.com/JuQ0AuodVJn4/Use-GDB-to-Walkthrough-OneFlow-Source-Code of building a debug version of OneFlow so I could run `gdb python3` to trace the C++ code of OneFlow.
