### ISSUE TITLE
cannot print float16 Tensor element

### ISSUE THREAD

**Issue by EaglewithFire** [Oneflow-Inc/oneflow#8702]
## Summary

print() worked well when I try to output an element from float64 Tensor.
But it doesn't work for float16 Tensor and produces the message below.

Traceback (most recent call last):
  File "/home/rehanchy/workspace/learningOneflow/test.py", line 8, in <module>
    print(float_t_1[1, 2, 3, 4], float_t_2[1, 2, 3, 4])
  File "/home/rehanchy/.local/lib/python3.9/site-packages/oneflow/framework/tensor.py", line 78, in _getitem
    return flow._C.tensor_getitem(self, key)
oneflow._oneflow_internal.exception.OpKernelNotFoundException: 
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/functional/impl/array_functor.cpp", line 1832, in operator()
    Slice(expand_input, start, end, step)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 139, in Dispatch<oneflow::one::Tensor>
    Dispatch<TensorTuple>(op_expr, inputs, ctx)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 131, in Dispatch<oneflow::one::TensorTuple>
    Dispatch(op_expr, inputs, outputs.get(), ctx)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/op_interpreter/op_interpreter.cpp", line 96, in Apply
    internal_->Apply(op_expr, inputs, outputs, ctx)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/op_interpreter/eager_mirrored_op_interpreter.cpp", line 165, in NaiveInterpret
    PhysicalRun([&](InstructionsBuilder* builder) -> Maybe ... input_eager_blob_objects, output_eager_blob_objects, ctx, stream); })
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/instructions_builder.cpp", line 599, in PhysicalRun
    Build(&instructions_builder)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/instructions_builder.cpp", line 358, in LocalCallOpKernel
    vm::LocalCallOpKernelPhyInstrOperand::New( opkernel ... consistent_tensor_infer_result, ctx, *one::CurrentDevVmDepObjectConsumeMode())
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/eager/local_call_opkernel_phy_instr_operand.h", line 54, in New
    ptr->Init()
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/eager/local_call_opkernel_phy_instr_operand.cpp", line 26, in Init
    mut_opkernel()->ChooseOpKernel(&user_opkernel_, &need_temp_storage_, attrs(), inputs().get(), outputs().get(), consistent_tensor_infer_result().get())
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/user/kernels/stateful_local_opkernel.cpp", line 453, in ChooseOpKernel
    user_op::UserOpRegistryMgr::Get().GetOpKernelRegistryResult(op_type_name, *reg_ctx_)
Cannot find the kernel matching Current OperatorConf. 
 The Info of OperatorConf are 
 op_name: slice1
 op_type_name: slice
 DeviceType_Name: kCPU
 DataType_Name of x_0: kFloat16
 DataType_Name of y_0: kFloat16
op_kernels_not_found_debug_str: "((device_type == cpu) and (data_type of tensor \'y\' == kBool))"
op_kernels_not_found_debug_str: "((device_type == cpu) and (data_type of tensor \'y\' == kFloat))"
op_kernels_not_found_debug_str: "((device_type == cpu) and (data_type of tensor \'y\' == kDouble))"
op_kernels_not_found_debug_str: "((device_type == cpu) and (data_type of tensor \'y\' == kInt32))"
op_kernels_not_found_debug_str: "((device_type == cpu) and (data_type of tensor \'y\' == kInt64))"
op_kernels_not_found_debug_str: "((device_type == cpu) and (data_type of tensor \'y\' == kInt8))"
op_kernels_not_found_debug_str: "((device_type == cpu) and (data_type of tensor \'y\' == kUInt8))"
op_kernels_not_found_debug_str: "((device_type == gpu) and (data_type of tensor \'y\' == kBool))"
op_kernels_not_found_debug_str: "((device_type == gpu) and (data_type of tensor \'y\' == kFloat))"
op_kernels_not_found_debug_str: "((device_type == gpu) and (data_type of tensor \'y\' == kDouble))"
op_kernels_not_found_debug_str: "((device_type == gpu) and (data_type of tensor \'y\' == kInt32))"
op_kernels_not_found_debug_str: "((device_type == gpu) and (data_type of tensor \'y\' == kInt64))"
op_kernels_not_found_debug_str: "((device_type == gpu) and (data_type of tensor \'y\' == kInt8))"
op_kernels_not_found_debug_str: "((device_type == gpu) and (data_type of tensor \'y\' == kUInt8))"
op_kernels_not_found_debug_str: "((device_type == gpu) and (data_type of tensor \'y\' == kFloat16))"

## Code to reproduce bug

```python
import oneflow as flow

My_tensor = flow.empty([2, 3, 4, 5], dtype=flow.float64)
My_tensor.uniform_(0, 3)
print(My_tensor[1, 2, 3, 4])
float_t_1 = flow.HalfTensor(My_tensor)
float_t_2 = flow.HalfTensor(My_tensor)
print(float_t_1[1, 2, 3, 4], float_t_2[1, 2, 3, 4])
```

## System Information

- What is your OneFlow installation (pip, source, dockerhub): pip
- OS: Ubuntu 18.04.1
- OneFlow version (run `python3 -m oneflow --doctor`): 0.7.0+cu112
- Python version: 3.9.12

**Comment by s14n** [comment]
Thanks for your feedback. This code works well in oneflow v0.8.0. Please try to update oneflow to v0.8.0 by `pip3 install oneflow`.
