### ISSUE TITLE
运行oneflow示例失败

### ISSUE THREAD

**Issue by young-chao** [Oneflow-Inc/oneflow#8846]
## 总结

运行oneflow示例失败
Placement is invalid because rank must be less than world size

代码：
import oneflow as flow
import oneflow.nn as nn
import flowvision
import flowvision.transforms as transforms

BATCH_SIZE=64
EPOCH_NUM = 1

PLACEMENT = flow.placement("cuda", [0,1])
S0 = flow.sbp.split(0)
B = flow.sbp.broadcast

DEVICE = "cuda" if flow.cuda.is_available() else "cpu"
# DEVICE = "cpu"
print("Using {} device".format(DEVICE))

training_data = flowvision.datasets.CIFAR10(
    root="data",
    train=True,
    transform=transforms.ToTensor(),
    download=True,
)

train_dataloader = flow.utils.data.DataLoader(
    training_data, BATCH_SIZE, shuffle=True
)

model = flowvision.models.mobilenet_v2().to(DEVICE)
model.classifer = nn.Sequential(nn.Dropout(0.2), nn.Linear(model.last_channel, 10))
model = model.to_global(placement=PLACEMENT, sbp=B)

loss_fn = nn.CrossEntropyLoss().to(DEVICE)
optimizer = flow.optim.SGD(model.parameters(), lr=1e-3)

for t in range(EPOCH_NUM):
    print(f"Epoch {t+1}\n-------------------------------")
    size = len(train_dataloader.dataset)
    for batch, (x, y) in enumerate(train_dataloader):
        x = x.to_global(placement=PLACEMENT, sbp=S0)
        y = y.to_global(placement=PLACEMENT, sbp=S0)

        # Compute prediction error
        pred = model(x)
        loss = loss_fn(pred, y)

        # Backpropagation
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        current = batch * BATCH_SIZE
        if batch % 5 == 0:
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")

控制台输出：
loaded library: /lib/x86_64-linux-gnu/libibverbs.so.1
Using cuda device
Files already downloaded and verified
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server/extensions/ms-python.python-2022.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/root/.vscode-server/extensions/ms-python.python-2022.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/root/.vscode-server/extensions/ms-python.python-2022.10.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/root/.vscode-server/extensions/ms-python.python-2022.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/root/.vscode-server/extensions/ms-python.python-2022.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/root/.vscode-server/extensions/ms-python.python-2022.10.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/workspace/workfile/raytest/oneflow_test/test_3.py", line 34, in <module>
    model = model.to_global(placement=PLACEMENT, sbp=B)
  File "/usr/local/lib/python3.8/dist-packages/oneflow/nn/module.py", line 1047, in to_global
    return self._apply(convert)
  File "/usr/local/lib/python3.8/dist-packages/oneflow/nn/module.py", line 895, in _apply
    module._apply(fn, applied_dict)
  File "/usr/local/lib/python3.8/dist-packages/oneflow/nn/module.py", line 895, in _apply
    module._apply(fn, applied_dict)
  File "/usr/local/lib/python3.8/dist-packages/oneflow/nn/module.py", line 895, in _apply
    module._apply(fn, applied_dict)
  File "/usr/local/lib/python3.8/dist-packages/oneflow/nn/module.py", line 910, in _apply
    param_applied = fn(param)
  File "/usr/local/lib/python3.8/dist-packages/oneflow/nn/module.py", line 1045, in convert
    return t.to_global(placement=placement, sbp=sbp)
RuntimeError: Check failed: (machine_id) < (GlobalProcessCtx::WorldSize()) (1 vs 1) Placement is invalid because rank must be less than world size!

系统信息
- What is your OneFlow installation:pip
- OS:Ubuntu
- OneFlow version:0.8.0
- Python version:3.8.10
- CUDA driver version: 460.27.04（11.2）

**Comment by ShiyuanResearch** [comment]
你好，可以参考 https://docs.oneflow.org/master/parallelism/03_consistent_tensor.html 和 https://docs.oneflow.org/master/parallelism/04_launch.html 来设置环境变量或者使用launch模块来运行。

**Comment by young-chao** [comment]
你好，你的邮件已收到，谢谢！
