### ISSUE TITLE
对不可导的算子进行了求导操作，报错信息不直观

### ISSUE THREAD

**Issue by ShiyuanResearch** [Oneflow-Inc/oneflow#8871]
现在对不可导的算子的实现方式是在ods定义中设置NoGrad，该设置会将对应的requires_grad设置为false从而实现不可导。

如果对该不可导算子求导，会报错：
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shiyuan/oneflow/python/oneflow/framework/tensor.py", line 33, in _backward
    flow.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/shiyuan/oneflow/python/oneflow/autograd/autograd.py", line 110, in backward
    backward_api(
oneflow._oneflow_internal.exception.Exception: Check failed: outputs.at(i)->requires_grad() All output tensors `.requires_grad` should be true
  File "/home/shiyuan/oneflow/oneflow/api/python/autograd/autograd.cpp", line 87, in Backward
    CheckAndInitOutGrads(outputs, out_grads)
  File "/home/shiyuan/oneflow/oneflow/api/python/autograd/autograd.cpp", line 52, in CheckAndInitOutGrads

Error Type: oneflow.ErrorProto.check_failed_error
```

该报错信息不直观，用户很难从该错误信息中知道自己行为错误，对一个不可导的算子做了backward()，开发者也很难立刻定位到错误实现。

如果此处的报错信息显示该算子不可导或者该算子的导数未实现，可能更直观一些。

**Comment by wyg1997** [comment]
那就要求 NoGrad 算子的输入的 requires_grad 都必须是 False，如果不是的话就提示 xxx 算子是不可导的，如果想调用的话就要在 `with flow.no_grad()` 域内调用，或对输入要先做 `input.detach()` 处理？

**Comment by hjchen2** [comment]
你这里的问题是，对一个requires_grad=false的Tensor调用backward/grad接口，这是不允许的。只是这里的报错信息好像没有对齐pytorch的"RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn"

**Comment by wyg1997** [comment]
> 

他应该是说某个 requires_grad=True 的 Tensor，在调用声明为 NoGrad 的算子后，requires_grad 变为了 False，这个变化用户是无感的，最后想 backward 的时候才发现 requires_grad 是 False，报错到了 autograd.backward 这里，对于 debug 来说是比较不友好的？

**Comment by ShiyuanResearch** [comment]
正常调用NoGrad算子，如果backward()反向走到了NoGrad算子，Apply()报错该算子不可导或者求导未实现，怎么样

**Comment by ShiyuanResearch** [comment]
> > 你这里的问题是，对一个requires_grad=False的Tensor调用backward/grad接口，这是不允许的。只是这里的报错信息好像没有对齐pytorch的"RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn"
> 
> 他应该是说某个 requires_grad=True 的 Tensor，在调用声明为 NoGrad 的算子后，requires_grad 变为了 False，这个变化用户是无感的，最后想 backward 的时候才发现 requires_grad 是 False，报错到了 autograd.backward 这里，对于 debug 来说是比较不友好的？

是的，requires_grad是被oneflow改成false的，用户本身不知道自己是对一个requires_grad false求导。也不知道具体是哪个op出的错，不知道哪个op是不可导的

**Comment by hjchen2** [comment]
> > 那就要求 NoGrad 算子的输入的 requires_grad 都必须是 False，如果不是的话就提示 xxx 算子是不可导的，如果想调用的话就要在 with flow.no_grad() 域内调用，或对输入要先做 input.detach() 处理？
> 
> 正常调用NoGrad算子，如果backward()反向走到了NoGrad算子，Apply()报错该算子不可导或者求导未实现，怎么样

这个不符合autograd engine的机制，因为requires_grad=False时autograd engine根本就不会为它插入grad fn，走到了backward也是进行不下去的。这里只要对齐pytorch的报错信息就可以，具体是哪个op导致的requires_grad=False，单步调试一下就知道了。

**Comment by wyg1997** [comment]
> 这个不符合autograd engine的机制，因为requires_grad=False时autograd engine根本就不会为它插入grad fn，走到了backward也是进行不下去的。这里只要对齐pytorch的报错信息就可以，具体是哪个op导致的requires_grad=False，单步调试一下就知道了。

支持的话可以？为这些 NoGrad 的算子设置一个空的后向 grad_fn，一旦被调用就报哪个算子不可导，给一个 error 出去？

**Comment by hjchen2** [comment]
> 支持的话也可以？为这些 NoGrad 的算子设置一个空的后向 grad_fn，一旦被调用就报哪个算子不可导，给一个 error 出去？

不行的，需要找到最开始的那个空的后向 grad_fn才行

**Comment by hjchen2** [comment]
我的建议是对齐pytorch就行，即使报错说某个算子不支持后向，用户也一样需要去代码里找一下这个算子在哪调用过

**Comment by ShiyuanResearch** [comment]
我看了一下pytorch，NoGrad算子的out_tensor不会强制修改成false，然后插入了一个NotImplemented的grad_fn，这样是不是就符合autograd engine的机制了。

目前的报错信息很难让用户知道自己调用了一个不可导的算子，用户可能都不知道需要关注tensor的requires_grad进行单步调试。

类似情况pytorch的报错是：
```
RuntimeError: derivative for "op_name" is not implemented
```

**Comment by hjchen2** [comment]
> 我看了一下pytorch，NoGrad算子的out_tensor不会强制修改成false，然后插入了一个NotImplemented的grad_fn，这样是不是就符合autograd engine的机制了。
> 
> 目前的报错信息很难让用户知道自己调用了一个不可导的算子，用户可能都不知道需要关注tensor的requires_grad进行单步调试。
> 
> 类似情况pytorch的报错是：
> 
> ```
> RuntimeError: derivative for "op_name" is not implemented
> ```

是哪个例子？

**Comment by hjchen2** [comment]
[Yinggang Wang](https://app.slack.com/team/U01CNBLC45P)
  [43 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659942552133609?thread_ts=1659942470.852459&cid=G48PTMA15)
这样的话好像符合我说的第二个方案:rolling_on_the_floor_laughing:


[Shiyuan Shangguan](https://app.slack.com/team/U4FT8UX43)
  [40 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659942680098869?thread_ts=1659942470.852459&cid=G48PTMA15)
是的，我写完评论才发现你已经给出类似的设计了


[Houjiang Chen](https://app.slack.com/team/UJWCZMTFY)
  [40 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659942733330789?thread_ts=1659942470.852459&cid=G48PTMA15)
这是哪个例子


[Houjiang Chen](https://app.slack.com/team/UJWCZMTFY)
  [39 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659942742709999?thread_ts=1659942470.852459&cid=G48PTMA15)
我这里怎么报错不是这样的


[Shiyuan Shangguan](https://app.slack.com/team/U4FT8UX43)
  [38 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659942811835289?thread_ts=1659942470.852459&cid=G48PTMA15)
import torch
x = torch.tensor([1.]).requires_grad_()
y = torch.tensor([1.]).requires_grad_()
out = torch.floor_divide(x, y)
out.backward()


[Houjiang Chen](https://app.slack.com/team/UJWCZMTFY)
  [38 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659942812154799?thread_ts=1659942470.852459&cid=G48PTMA15)
截屏2022-08-08 15.13.15.png 
截屏2022-08-08 15.13.15.png




[Yinggang Wang](https://app.slack.com/team/U01CNBLC45P)
  [36 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659942918891309?thread_ts=1659942470.852459&cid=G48PTMA15)
zeros_like 机制不太一样，他相当于 source op，不用后向的


[Houjiang Chen](https://app.slack.com/team/UJWCZMTFY)
  [36 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659942935041439?thread_ts=1659942470.852459&cid=G48PTMA15)
那这个floor_divide是比较特殊的op，它单纯是因为没有实现对应的backward


[Houjiang Chen](https://app.slack.com/team/UJWCZMTFY)
  [35 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659943008525679?thread_ts=1659942470.852459&cid=G48PTMA15)
torch.div(x, y, rounding_mode='floor')


[Houjiang Chen](https://app.slack.com/team/UJWCZMTFY)
  [35 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659943016363819?thread_ts=1659942470.852459&cid=G48PTMA15)
正常情况下应该用这个操作


[Shiyuan Shangguan](https://app.slack.com/team/U4FT8UX43)
  [35 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659943041005789?thread_ts=1659942470.852459&cid=G48PTMA15)
嗯，floor_div对应div(“trunc”)


[Shiyuan Shangguan](https://app.slack.com/team/U4FT8UX43)
  [34 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659943101052679?thread_ts=1659942470.852459&cid=G48PTMA15)
不讨论具体op的话，我觉得对于不可导的算子，这个报错信息更合理一些


[Shiyuan Shangguan](https://app.slack.com/team/U4FT8UX43)
  [33 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659943159469979?thread_ts=1659942470.852459&cid=G48PTMA15)
起码用户知道是因为对不可导的算子求导出的错，而且知道具体是哪个op


[Houjiang Chen](https://app.slack.com/team/UJWCZMTFY)
  [32 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659943175114679?thread_ts=1659942470.852459&cid=G48PTMA15)
但我们都是实现了的啊


[Houjiang Chen](https://app.slack.com/team/UJWCZMTFY)
  [32 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659943227113059?thread_ts=1659942470.852459&cid=G48PTMA15)
我们不是因为某个op支持求导，但因为没有实现对应的求导过程而报错 (edited) 


[Houjiang Chen](https://app.slack.com/team/UJWCZMTFY)
  [31 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659943258590959?thread_ts=1659942470.852459&cid=G48PTMA15)
我们出现报错一定是这个op不支持求导


[Houjiang Chen](https://app.slack.com/team/UJWCZMTFY)
  [31 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659943269870619?thread_ts=1659942470.852459&cid=G48PTMA15)
而不是not implemented


[Yinggang Wang](https://app.slack.com/team/U01CNBLC45P)
  [31 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659943273440229?thread_ts=1659942470.852459&cid=G48PTMA15)
对，但用户不知道是哪个 op


[Houjiang Chen](https://app.slack.com/team/UJWCZMTFY)
  [30 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659943290851729?thread_ts=1659942470.852459&cid=G48PTMA15)
:joy:不需要知道


[Shiyuan Shangguan](https://app.slack.com/team/U4FT8UX43)
  [30 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659943330327009?thread_ts=1659942470.852459&cid=G48PTMA15)
但我们都是实现了的啊
没有吧，现在对NoGrad求导，报错是oneflow._oneflow_internal.exception.Exception: Check failed: [outputs.at](http://outputs.at/)(i)->requires_grad() All output tensors `.requires_grad` should be true


[Houjiang Chen](https://app.slack.com/team/UJWCZMTFY)
  [29 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659943390361879?thread_ts=1659942470.852459&cid=G48PTMA15)
no grad是这个op本身就没有导数，而不是它有导数但我们没实现的问题


[Houjiang Chen](https://app.slack.com/team/UJWCZMTFY)
  [28 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659943419609119?thread_ts=1659942470.852459&cid=G48PTMA15)
pytorch里面floor_divide也是有导数的，但只是因为他没实现而已


[Yinggang Wang](https://app.slack.com/team/U01CNBLC45P)
  [28 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659943422782429?thread_ts=1659942470.852459&cid=G48PTMA15)
这个报错信息我一会会 refine 一下，现在是看有没有必要让用户知道哪一步这个 output.requires_grad 变成了 False


[Houjiang Chen](https://app.slack.com/team/UJWCZMTFY)
  [27 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659943502527849?thread_ts=1659942470.852459&cid=G48PTMA15)
相当于pytorch的一个bug


[Shiyuan Shangguan](https://app.slack.com/team/U4FT8UX43)
  [27 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659943515463109?thread_ts=1659942470.852459&cid=G48PTMA15)
嗯，我也只是觉得NoGrad的报错应该更直观一些


[Shiyuan Shangguan](https://app.slack.com/team/U4FT8UX43)
  [26 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659943581960649?thread_ts=1659942470.852459&cid=G48PTMA15)
未实现求导可以报错提示，不支持求导为什么不可以报错提示呢


[Shiyuan Shangguan](https://app.slack.com/team/U4FT8UX43)
  [22 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659943799920499?thread_ts=1659942470.852459&cid=G48PTMA15)
不需要知道哪个op不支持求导
需要知道吧，如果网络很复杂的话，让用户自己去找也很麻烦


[Houjiang Chen](https://app.slack.com/team/UJWCZMTFY)
  [21 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659943852637279?thread_ts=1659942470.852459&cid=G48PTMA15)
哎，不是直不直接的问题，no grad就是标记某个op是不是可导，不可导的op产生的结果的requires_grad一定是False，本身就说明了这个op是不可导的，而且如果用户最终没有调用这个错误的backward，我们也插入对所有的no grad算子都插入一个unimplemented grad fn，这个插入和反向遍历的开销都是很大的


[Houjiang Chen](https://app.slack.com/team/UJWCZMTFY)
  [21 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659943876103399?thread_ts=1659942470.852459&cid=G48PTMA15)
知道不也一样需要去网络里找一遍在什么地方调用了这个op么


[Houjiang Chen](https://app.slack.com/team/UJWCZMTFY)
  [16 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659944138436829?thread_ts=1659942470.852459&cid=G48PTMA15)
一旦决定要插入这样一个空的grad fn，那它就必然会传染到整个网络，最终本来很简单的一个后向图，变成了一个非常复杂的后向图


[Shiyuan Shangguan](https://app.slack.com/team/U4FT8UX43)
  [15 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659944193895999?thread_ts=1659942470.852459&cid=G48PTMA15)
嗯，那unimplemented grad fn这个方案不好，可以用其他的方式让报错更直观一些。


[Houjiang Chen](https://app.slack.com/team/UJWCZMTFY)
  [12 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659944389117999?thread_ts=1659942470.852459&cid=G48PTMA15)
好像没有其他方式，因为eager下并不知道未来要对哪个Tensor求backward


[Yinggang Wang](https://app.slack.com/team/U01CNBLC45P)
  [12 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659944395186129?thread_ts=1659942470.852459&cid=G48PTMA15)
我提的第一种方案（让 NoGrad 的 op 检察所有输入，要求 requires_grad 都是 False），会造成 torch 能跑的代码我们跑不了，不对齐。
但如果不处理的话，pytorch 如果用户用错了，想 backward 的时候报错，他可以通过 op 名快速定位到哪个 op 的问题，而我们就得用户在模型里一点点往上翻着找了，似乎也不太好？ (edited) 


[Houjiang Chen](https://app.slack.com/team/UJWCZMTFY)
  [12 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659944420425609?thread_ts=1659942470.852459&cid=G48PTMA15)
我觉得对齐pytorch就好了


[Houjiang Chen](https://app.slack.com/team/UJWCZMTFY)
  [11 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659944444566709?thread_ts=1659942470.852459&cid=G48PTMA15)
不能因为pytorch的一个bug就要去对齐它的bug下的报错


[Houjiang Chen](https://app.slack.com/team/UJWCZMTFY)
  [11 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659944468070309?thread_ts=1659942470.852459&cid=G48PTMA15)
它正常情况下的报错就是
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn


[Houjiang Chen](https://app.slack.com/team/UJWCZMTFY)
  [10 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659944513278989?thread_ts=1659942470.852459&cid=G48PTMA15)
因为他的bug我们是可以避免的，没必要bug也要去对齐吧:joy:


[Shiyuan Shangguan](https://app.slack.com/team/U4FT8UX43)
  [10 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659944526101369?thread_ts=1659942470.852459&cid=G48PTMA15)
NoGrad算子的结果的requires_grad是False，如果用户求导，记录requires_gradd False的第一个op_name，报给用户呢


[Yinggang Wang](https://app.slack.com/team/U01CNBLC45P)
  [9 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659944570209899?thread_ts=1659942470.852459&cid=G48PTMA15)
这个做不到，因为 autograd engine 只记录 requires_grad=True 的 tracing


[Houjiang Chen](https://app.slack.com/team/UJWCZMTFY)
  [3 minutes ago](https://of-world.slack.com/archives/G48PTMA15/p1659944924454269?thread_ts=1659942470.852459&cid=G48PTMA15)
我觉得是这样的，eager下只能尽可能去把报错信息报的更精确，但到底什么才是精确的报错信息，这个得推敲一下。对一个requires_grad=False的Tensor去做backward本来就是不允许的，不是因为前面哪个op不支持grad，只是因为它的requires_grad=False，因为也可能单纯就是因为用户没有设置requires_grad=True。再比如
x = flow.Tensor(2, 3)
y = flow.Tensor(2, 4)
x + y
这里就应该在x + y的地方报错，而不是去报`x = flow.Tensor(2, 3)`创建Tensor出错 (edited)

**Comment by wyg1997** [comment]
#8872 中顺带优先了一下报错～
