### ISSUE TITLE
oneflow.where dtype check error

### ISSUE THREAD

**Issue by reygu** [Oneflow-Inc/oneflow#8906]
## Code to reproduce bug

```
import oneflow as flow
x = flow.randn(5, 5)
y = flow.where(x > 0, x, 0.0)
```

Output:
```
RuntimeError: Check failed: (x_dtype) == (GetDataType<double>::value) (2 vs 3) expected scalar type 3but found 2
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 143, in Dispatch<oneflow::one::Tensor>
    Dispatch<TensorTuple>(op_expr, inputs, ctx)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 134, in Dispatch<oneflow::one::TensorTuple>
    Dispatch(op_expr, processor.inputs(), outputs.get(), ctx)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/op_interpreter/op_interpreter.cpp", line 96, in Apply
    internal_->Apply(op_expr, inputs, outputs, ctx)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp", line 83, in NaiveInterpret
    [&]() -> Maybe<const LocalTensorInferResult> { LocalTensorMetaInferArgs ... Data_YouAreNotAllowedToCallThisFuncOutsideThisFile(); }()
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/op_interpreter/eager_local_op_interpreter.cpp", line 83, in operator()
    user_op_expr.mut_local_tensor_infer_cache()->GetOrInfer(infer_args)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/local_tensor_infer_cache.cpp", line 199, in GetOrInfer
    Infer(*user_op_expr, infer_args)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/local_tensor_infer_cache.cpp", line 174, in Infer
    user_op_expr.InferPhysicalTensorDesc( infer_args.attrs ... ) -> TensorMeta* { return &output_mut_metas.at(i); })
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/op_expr.cpp", line 546, in InferPhysicalTensorDesc
    dtype_infer_fn_(&infer_ctx)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/user/ops/where_op.cpp", line 272, in InferDataType
    
Error Type: oneflow.ErrorProto.check_failed_error
```

**Comment by ShiyuanResearch** [comment]
这个报错是与pytorch一致的，你看 flow.where(x > 0, x, flow.tensor(0.0)) 能不能满足你的需求。

**Comment by reygu** [comment]
pytorch 这段代码是不报错的，oneflow 在 InferDataType 似乎默认了有浮点操作时 x 只能是 double，是符合预期的就没问题
https://github.com/Oneflow-Inc/oneflow/blob/1307edfdfe8750e1be46a8b827166df3e335c6e6/oneflow/user/ops/where_op.cpp#L264-L280

**Comment by ShiyuanResearch** [comment]
```
import torch
x = torch.randn(5, 5)
y = torch.where(x > 0, x, 0.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: expected scalar type float but found double
```

我这里pytorch也是一样报错的，可能是版本区别，我这里是1.11.0+cu102

**Comment by reygu** [comment]
> ```
> import torch
> x = torch.randn(5, 5)
> y = torch.where(x > 0, x, 0.0)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> RuntimeError: expected scalar type float but found double
> ```
> 
> 我这里pytorch也是一样报错的，可能是版本区别，我这里是1.11.0+cu102

是这原因... '1.12.0+cu113' 没报错

**Comment by reygu** [comment]
> pytorch 这段代码是不报错的，oneflow 在 InferDataType 似乎默认了有浮点操作时 x 只能是 double，是符合预期的就没问题
> 
> https://github.com/Oneflow-Inc/oneflow/blob/1307edfdfe8750e1be46a8b827166df3e335c6e6/oneflow/user/ops/where_op.cpp#L264-L280

这个好像还是有点不对，python 调用 `where(condition, x, y)`, y 是 scalar 的时候其实隐含了 y 是 double，因为 python 没有 float32 类型，所以判断 x 是不是浮点数只判断 x 是不是 double 就行
不过如果是用 C++ 代码调用 `functional::WhereScalarY(condition, x, Scalar(0.0))`, x dtype 是 float32 的话就会报错了，python 代码把 y 转成 tensor 实际上调用的也是 `functional::Where` 这个算子了
