### ISSUE TITLE
About using local tensor in pipeline mode

### ISSUE THREAD

**Issue by DarrenYing** [Oneflow-Inc/oneflow#9093]
## Summary

I slightly modified the example given in https://docs.oneflow.org/master/parallelism/06_pipeline.html
I add a local tensor in the forward function of stage0 and then flow.nn.graph cannot be compiled
I changed the local tensor with to_global function, and got another runtime error:  local_tensor.to_global() is not supported within nn.Graph for now.

I want to find a way to use local tensor in the pipeline stage with flow.nn.Graph API, thanks a lot.

## Code to reproduce bug

```
import oneflow as flow

BATCH_SIZE = 16
BROADCAST = [flow.sbp.broadcast]
P0 = flow.placement("cuda", ranks=[0])
P1 = flow.placement("cuda", ranks=[1])


class Stage0Module(flow.nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = flow.nn.Flatten()
        self.linear0 = flow.nn.Linear(28 * 28, 512)
        self.relu0 = flow.nn.ReLU()

    def forward(self, x):
        tmp = flow.ones(BATCH_SIZE, 1, 28, 28)
        # tmp = tmp.to_global(P0, BROADCAST)
        x = x + tmp
        out = self.flatten(x)
        out = self.linear0(out)
        out = self.relu0(out)
        return out


class Stage1Module(flow.nn.Module):
    def __init__(self):
        super().__init__()
        self.linear1 = flow.nn.Linear(512, 512)
        self.relu1 = flow.nn.ReLU()
        self.linear2 = flow.nn.Linear(512, 10)
        self.relu2 = flow.nn.ReLU()

    def forward(self, x):
        out = self.linear1(x)
        out = self.relu1(out)
        out = self.linear2(out)
        out = self.relu2(out)
        return out


class PipelineModule(flow.nn.Module):
    def __init__(self):
        super().__init__()
        self.m_stage0 = Stage0Module()
        self.m_stage1 = Stage1Module()

        self.m_stage0.to_global(placement=P0, sbp=BROADCAST)
        self.m_stage1.to_global(placement=P1, sbp=BROADCAST)

    def forward(self, x):
        out_stage0 = self.m_stage0(x)
        in_stage1 = out_stage0.to_global(placement=P1, sbp=BROADCAST)
        out_stage1 = self.m_stage1(in_stage1)
        return out_stage1


module_pipeline = PipelineModule()
sgd = flow.optim.SGD(module_pipeline.parameters(), lr=0.001)


class PipelineGraph(flow.nn.Graph):
    def __init__(self):
        super().__init__()
        self.module_pipeline = module_pipeline
        self.module_pipeline.m_stage0.config.set_stage(stage_id=0, placement=P0)
        self.module_pipeline.m_stage1.config.set_stage(stage_id=1, placement=P1)
        self.loss_fn = flow.nn.CrossEntropyLoss()
        self.config.set_gradient_accumulation_steps(2)
        self.add_optimizer(sgd)

    def build(self, x, y):
        out = self.module_pipeline(x)
        loss = self.loss_fn(out, y)
        loss.backward()
        return loss


graph_pipeline = PipelineGraph()

x = flow.randn(BATCH_SIZE, 1, 28, 28)
x = x.to_global(P0, BROADCAST)
y = flow.randint(0, 10, (BATCH_SIZE,))
y = y.to_global(P1, BROADCAST)

for i in range(20):
    loss = graph_pipeline(x, y)
    print(loss.to_local())

```

```
loaded library: /usr/lib/x86_64-linux-gnu/libibverbs.so.1
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
loaded library: /usr/lib/x86_64-linux-gnu/libibverbs.so.1
loaded library: /usr/lib/x86_64-linux-gnu/libibverbs.so.1
W20220914 13:26:56.028411 38162 rpc_client.cpp:190] LoadServer 127.0.0.1 Failed at 0 times error_code 14 error_message failed to connect to all addresses
[ERROR](GRAPH:PipelineGraph_0:PipelineGraph) building graph got error.
Traceback (most recent call last):
  File "demo02.py", line 87, in <module>
    loss = graph_pipeline(x, y)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 224, in __call__
    self._compile(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 779, in _compile
    _, eager_outputs = self.build_graph(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 798, in build_graph
    outputs = self.__build_graph(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 902, in __build_graph
    outputs = self.build(*lazy_args, **lazy_kwargs)
  File "demo02.py", line 73, in build
    out = self.module_pipeline(x)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/block.py", line 248, in __call__
    result = self.__block_forward(*args, **kwargs)[ERROR](GRAPH:PipelineGraph_0:PipelineGraph) building graph got error.
  File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/block.py", line 280, in __block_forward

    result = self._origin.__class__.forward(self, *args, **kwargs)
  File "demo02.py", line 52, in forward
    out_stage0 = self.m_stage0(x)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/block.py", line 248, in __call__
Traceback (most recent call last):
  File "demo02.py", line 87, in <module>
    result = self.__block_forward(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/block.py", line 280, in __block_forward
    result = self._origin.__class__.forward(self, *args, **kwargs)
  File "demo02.py", line 19, in forward
    x = x + tmp
RuntimeError: (0 vs 1)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 143, in Dispatch<oneflow::one::Tensor>
    Dispatch<TensorTuple>(op_expr, inputs, ctx)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 134, in Dispatch<oneflow::one::TensorTuple>
    Dispatch(op_expr, processor.inputs(), outputs.get(), ctx)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/op_interpreter/op_interpreter.cpp", line 96, in Apply
    internal_->Apply(op_expr, inputs, outputs, ctx)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp", line 778, in ApplyImpl

Error Type: oneflow.ErrorProto.check_failed_error
    loss = graph_pipeline(x, y)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 224, in __call__
    self._compile(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 779, in _compile
    _, eager_outputs = self.build_graph(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 798, in build_graph
    outputs = self.__build_graph(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 902, in __build_graph
    outputs = self.build(*lazy_args, **lazy_kwargs)
  File "demo02.py", line 73, in build
    out = self.module_pipeline(x)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/block.py", line 248, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/block.py", line 280, in __block_forward
    result = self._origin.__class__.forward(self, *args, **kwargs)
  File "demo02.py", line 52, in forward
    out_stage0 = self.m_stage0(x)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/block.py", line 248, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/nn/graph/block.py", line 280, in __block_forward
    result = self._origin.__class__.forward(self, *args, **kwargs)
  File "demo02.py", line 19, in forward
    x = x + tmp
RuntimeError: (0 vs 1)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 143, in Dispatch<oneflow::one::Tensor>
    Dispatch<TensorTuple>(op_expr, inputs, ctx)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 134, in Dispatch<oneflow::one::TensorTuple>
    Dispatch(op_expr, processor.inputs(), outputs.get(), ctx)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/op_interpreter/op_interpreter.cpp", line 96, in Apply
    internal_->Apply(op_expr, inputs, outputs, ctx)
  File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp", line 778, in ApplyImpl

Error Type: oneflow.ErrorProto.check_failed_error
Killing subprocess 38161
Killing subprocess 38162
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/distributed/launch.py", line 237, in <module>
    main()
  File "/opt/conda/lib/python3.8/site-packages/oneflow/distributed/launch.py", line 225, in main
    sigkill_handler(signal.SIGTERM, None)
  File "/opt/conda/lib/python3.8/site-packages/oneflow/distributed/launch.py", line 193, in sigkill_handler
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['/opt/conda/bin/python3', '-u', 'demo02.py']' returned non-zero exit status 1.
```

## System Information

- What is your OneFlow installation (pip, source, dockerhub): dockerhub (oneflowinc/oneflow:nightly-cuda11.2 )
- OS: ubuntu 18.04
- OneFlow version (run `python3 -m oneflow --doctor`):  0.8.1.dev20220906+cu112
- Python version: 3.8.13
- CUDA driver version: 11.2
- GPU models:
- Other info:

**Comment by ShiyuanResearch** [comment]
First of all, the local tensor is designed for the eager mode, which is on the outside of the nn.Graph. The computational graph inside of the nn.Graph will be compiled into an execution graph, which is called lazy mode. You can use the tensor in the lazy mode with placement and sbp like `tmp = flow.ones(BATCH_SIZE//2, 1, 28, 28, placement=P0, sbp=BROADCAST)` instead of `to_global()`.
Secondly, the `self.config.set_gradient_accumulation_steps(2)` slices the data to two micro batch. So the first dimention of the tmp shape is set to `BATCH_SIZE//2`.

**Comment by DarrenYing** [comment]
> First of all, the local tensor is designed for the eager mode, which is on the outside of the nn.Graph. The computational graph in the eager mode will not be compiled. And the computational graph inside of the nn.Graph will be compiled into an execution graph, which is called lazy mode. You can use the tensor in the lazy mode with placement and sbp like `tmp = flow.ones(BATCH_SIZE//2, 1, 28, 28, placement=P0, sbp=BROADCAST)` instead of `to_global()`. Secondly, the `self.config.set_gradient_accumulation_steps(2)` slices the data to two micro batches. So the first dimention of the tmp is set to `BATCH_SIZE//2`.

Thank you so much! Your answer helps me understand the nn.Graph better.
