### ISSUE TITLE
fail to load pretrained model

### ISSUE THREAD

**Issue by jackalcooper** [Oneflow-Inc/oneflow#9163]
## Summary

```
E               While copying the parameter "conv_out.bias", an exception occurred : 
E           
E               Traceback (most recent call last):
E                 File "/home/caishenghang/.local/lib/python3.8/site-packages/oneflow/nn/module.py", line 776, in _load_from_state_dict
E                   param.copy_(input_param)
E                 File "/home/caishenghang/.local/lib/python3.8/site-packages/oneflow/framework/tensor.py", line 328, in _copy
E                   _copy_from_numpy_to_eager_local_tensor(self, other)
E                 File "/home/caishenghang/.local/lib/python3.8/site-packages/oneflow/framework/tensor.py", line 280, in _copy_from_numpy_to_eager_local_tensor
E                   method_name = eager_local_tensor._get_copy_local_tensor_from_numpy_func_name()
E               RuntimeError: Check failed: iter != map.end() 
E                 File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/api/python/utils/tensor_utils.cpp", line 93, in GetCopyLocalTensorFromNumpyFuncName
E                   MapAt(data_type2func_name, static_cast<int64_t>(dtype))
E                 File "/home/ci-user/runners/release/_work/oneflow/oneflow/oneflow/core/common/container_util.h", line 37, in MapAt
E                   
E               Error Type: oneflow.ErrorProto.check_failed_error
```

## Code to reproduce bug

Please post a minimal example to repro the bug. GitHub Gist or repo is highly recommended.

## System Information

- What is your OneFlow installation (pip, source, dockerhub):
- OS:
- OneFlow version (run `python3 -m oneflow --doctor`):
- Python version:
- CUDA driver version:
- GPU models:
- Other info:

**Comment by jackalcooper** [comment]
confirmed by @daquexian , a PR will be made for fix for FP16 in state dict

**Comment by jackalcooper** [comment]
workaround:
in `oneflow/nn/module.py`, change the param copy to:
```
                try:
                    with flow.no_grad():
                        print(key, input_param.shape, param.shape)
                        fake = flow.tensor(input_param)
                        param.copy_(fake)
```
