### ISSUE TITLE
RuntimeError: Check failed: input_tensor->is_eager()

### ISSUE THREAD

**Issue by jackalcooper** [Oneflow-Inc/oneflow#9187]
## Summary

```
[ERROR](GRAPH:GraphToRun_0:GraphToRun) building graph got error.
Traceback (most recent call last):
  File "/home/caishenghang/one_diffuse/pipes/of-t2i.py", line 19, in <module>
    images = pipe(prompt).images
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/python/oneflow/autograd/autograd_mode.py", line 154, in wrapper
    return func(*args, **kwargs)
  File "/home/caishenghang/diffusers/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_oneflow.py", line 297, in __call__
    latents = g(latents, text_embeddings)
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/python/oneflow/nn/graph/graph.py", line 224, in __call__
    self._compile(*args, **kwargs)
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/python/oneflow/nn/graph/graph.py", line 779, in _compile
    _, eager_outputs = self.build_graph(*args, **kwargs)
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/python/oneflow/nn/graph/graph.py", line 798, in build_graph
    outputs = self.__build_graph(*args, **kwargs)
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/python/oneflow/nn/graph/graph.py", line 902, in __build_graph
    outputs = self.build(*lazy_args, **lazy_kwargs)
  File "/home/caishenghang/diffusers/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_oneflow.py", line 42, in build
    noise_pred = self.unet(latent_model_input, t, encoder_hidden_states=text_embeddings).sample
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/python/oneflow/nn/graph/block.py", line 248, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/python/oneflow/nn/graph/block.py", line 280, in __block_forward
    result = self._origin.__class__.forward(self, *args, **kwargs)
  File "/home/caishenghang/diffusers/src/diffusers/models/unet_2d_condition_oneflow.py", line 242, in forward
    emb = self.time_embedding(t_emb)
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/python/oneflow/nn/graph/block.py", line 248, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/python/oneflow/nn/graph/block.py", line 280, in __block_forward
    result = self._origin.__class__.forward(self, *args, **kwargs)
  File "/home/caishenghang/diffusers/src/diffusers/models/embeddings_oneflow.py", line 73, in forward
    sample = self.linear_1(sample)
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/python/oneflow/nn/graph/block.py", line 248, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/python/oneflow/nn/graph/block.py", line 280, in __block_forward
    result = self._origin.__class__.forward(self, *args, **kwargs)
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/python/oneflow/nn/modules/linear.py", line 123, in forward
    res = flow._C.matmul(x, self.weight, transpose_a=False, transpose_b=True)
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/python/oneflow/nn/graph/block.py", line 497, in __getattr__
    p_state = self._get_from_states(name, "_parameters")
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/python/oneflow/nn/graph/block.py", line 535, in _get_from_states
    _s_block.try_build()
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/python/oneflow/nn/graph/block.py", line 695, in try_build
    self._lazy_origin_builder.try_build(self)
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/python/oneflow/nn/graph/block.py", line 643, in try_build
    self.result = self.method()
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/python/oneflow/framework/graph_build_util.py", line 251, in build_graph_state
    lazy_tensor = _C.dispatch_feed_variable(var_op, state_tensor, l2=l2)
RuntimeError: Check failed: input_tensor->is_eager() 
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/oneflow/api/python/functional/dispatch_stateful_ops.cpp", line 55, in operator()
    OpInterpUtil::Dispatch<Tensor>(*op, {input}, attrs)
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 140, in Dispatch<oneflow::one::Tensor>
    Dispatch<TensorTuple>(op_expr, inputs, ctx)
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/oneflow/core/framework/op_interpreter/op_interpreter_util.cpp", line 131, in Dispatch<oneflow::one::TensorTuple>
    Dispatch(op_expr, inputs, outputs.get(), ctx)
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/oneflow/core/framework/op_interpreter/op_interpreter.cpp", line 96, in Apply
    internal_->Apply(op_expr, inputs, outputs, ctx)
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/oneflow/core/framework/op_interpreter/lazy_op_interpreter.cpp", line 443, in ApplyImpl
    
Error Type: oneflow.ErrorProto.check_failed_error
```

## Code to reproduce bug

Please post a minimal example to repro the bug. GitHub Gist or repo is highly recommended.

## System Information

- What is your OneFlow installation (pip, source, dockerhub):
- OS:
- OneFlow version (run `python3 -m oneflow --doctor`):
- Python version:
- CUDA driver version:
- GPU models:
- Other info:

**Comment by jackalcooper** [comment]
confirmed with @hjchen2 
- autocast will cast a fp16 weight (eager tensor) to a lazy tensor
- in graph mode, it requires state_tensor of variable to be eager, so the check fails

**Comment by qsa-fox** [comment]
How to solve these problem?
