### ISSUE TITLE
`nn.graph` raises AttributeError: 'map' object has no attribute 'prefix'

### ISSUE THREAD

**Issue by jackalcooper** [Oneflow-Inc/oneflow#9194]
## Summary

```python
[ERROR](GRAPH:GraphToRun_0:GraphToRun) building graph got error.
Traceback (most recent call last):
  File "/home/caishenghang/one_diffuse/pipes/of-t2i-no-auto-cast.py", line 19, in <module>
    images = pipe(prompt).images
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/python/oneflow/autograd/autograd_mode.py", line 154, in wrapper
    return func(*args, **kwargs)
  File "/home/caishenghang/diffusers/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_oneflow.py", line 297, in __call__
    latents = g(latents, text_embeddings)
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/python/oneflow/nn/graph/graph.py", line 224, in __call__
    self._compile(*args, **kwargs)
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/python/oneflow/nn/graph/graph.py", line 779, in _compile
    _, eager_outputs = self.build_graph(*args, **kwargs)
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/python/oneflow/nn/graph/graph.py", line 798, in build_graph
    outputs = self.__build_graph(*args, **kwargs)
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/python/oneflow/nn/graph/graph.py", line 902, in __build_graph
    outputs = self.build(*lazy_args, **lazy_kwargs)
  File "/home/caishenghang/diffusers/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_oneflow.py", line 42, in build
    noise_pred = self.unet(latent_model_input, t, encoder_hidden_states=text_embeddings).sample
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/python/oneflow/nn/graph/block.py", line 260, in __call__
    for (name, arg) in args_tree.iter_named_nodes():
  File "/mnt/DATA/csh/oneflow-cuda-bare-metal/python/oneflow/nn/graph/util.py", line 439, in iter_named_nodes
    yield (named_node.prefix() + "_" + named_node.name(), named_node)
AttributeError: 'map' object has no attribute 'prefix'
```

## Code to reproduce bug

```python
noise_pred = self.unet(latent_model_input, t, encoder_hidden_states=text_embeddings).sample
```

## System Information

- What is your OneFlow installation (pip, source, dockerhub):
- OS:
- OneFlow version (run `python3 -m oneflow --doctor`):
- Python version:
- CUDA driver version:
- GPU models:
- Other info:

**Comment by strint** [comment]
latent_model_input, t, encoder_hidden_states=text_embeddings

这些类型分别是什么

**Comment by jackalcooper** [comment]
> latent_model_input, t, encoder_hidden_states=text_embeddings
> 
> 这些类型分别是什么

```python
type(latent_model_input) <class 'oneflow.Tensor'>
type(t) <class 'oneflow.Tensor'>
type(text_embeddings) <class 'oneflow.Tensor'>
```

**Comment by jackalcooper** [comment]
https://github.com/Oneflow-Inc/diffusers.git oneflow-unet nn-graph

```
# CUDA_VISIBLE_DEVICES=1
# make sure you're logged in with `huggingface-cli login`
import oneflow as torch
import torch as og_torch
from diffusers import OneFlowStableDiffusionPipeline

pipe = OneFlowStableDiffusionPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4",
    use_auth_token=True,
    # revision="fp16",
    # torch_dtype=torch.float16,
)

pipe = pipe.to("cuda")

prompt = "apple made a toaster that makes toast shaped like an apple"
with og_torch.autocast("cuda"):
    # with torch.autocast("cuda"):
    images = pipe(prompt).images
    for i, image in enumerate(images):
        image.save(f"{prompt}-{i}.png")
```

**Comment by jackalcooper** [comment]
update

`python/oneflow/nn/graph/block.py` 中 `for (name, arg) in args_tree.iter_named_nodes():` 的代码有 bug，如果返回值是用户自己封装的class，就会出错

**Comment by strint** [comment]
这里是 noise_pred_ = self.unet(latent_model_input, t, encoder_hidden_states=text_embeddings) 返回了一种特殊的 DataClass，被 ArgTree 生成 repr 用于 deubg 时，识别这个类型错误。

因为是用于 debug 的，所以可以先注释掉 output debug  repr 的记录。后面 fix 下这种用户自定义类型的处理，按说应该被识别成一个 Opaque 类型。

**Comment by strint** [comment]
Fixed with PR https://github.com/Oneflow-Inc/oneflow/pull/9211
