### ISSUE TITLE
oneflow nn.module doesn't support dtype

### ISSUE THREAD

**Issue by jackalcooper** [Oneflow-Inc/oneflow#9345]
## Summary

```
[ERROR](GRAPH:UNetGraph_0:UNetGraph) building graph got error.
Traceback (most recent call last):
  File "/home/caishenghang/one_diffuse/pipes/of-t2i.py", line 17, in <module>
    images = pipe(prompt).images
  File "/home/caishenghang/.local/lib/python3.8/site-packages/oneflow/autograd/autograd_mode.py", line 154, in wrapper
    return func(*args, **kwargs)
  File "/home/caishenghang/diffusers/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_oneflow.py", line 356, in __call__
    unet_graph._compile(latent_model_input, t, text_embeddings)
  File "/home/caishenghang/.local/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 779, in _compile
    _, eager_outputs = self.build_graph(*args, **kwargs)
  File "/home/caishenghang/.local/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 798, in build_graph
    outputs = self.__build_graph(*args, **kwargs)
  File "/home/caishenghang/.local/lib/python3.8/site-packages/oneflow/nn/graph/graph.py", line 902, in __build_graph
    outputs = self.build(*lazy_args, **lazy_kwargs)
  File "/home/caishenghang/diffusers/src/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion_oneflow.py", line 34, in build
    return self.unet(latent_model_input, t, encoder_hidden_states=text_embeddings).sample
  File "/home/caishenghang/.local/lib/python3.8/site-packages/oneflow/nn/graph/block.py", line 248, in __call__
    result = self.__block_forward(*args, **kwargs)
  File "/home/caishenghang/.local/lib/python3.8/site-packages/oneflow/nn/graph/block.py", line 280, in __block_forward
    result = self._origin.__class__.forward(self, *args, **kwargs)
  File "/home/caishenghang/diffusers/src/diffusers/models/unet_2d_condition_oneflow.py", line 286, in forward
    t_emb = t_emb.to(dtype=self.dtype)
  File "/home/caishenghang/.local/lib/python3.8/site-packages/oneflow/nn/graph/block.py", line 518, in __getattr__
    return partial(getattr(self._origin.__class__, name), self)
TypeError: the first argument must be callable
```

## Code to reproduce bug

Please post a minimal example to repro the bug. GitHub Gist or repo is highly recommended.

## System Information

- What is your OneFlow installation (pip, source, dockerhub):
- OS:
- OneFlow version (run `python3 -m oneflow --doctor`):
- Python version:
- CUDA driver version:
- GPU models:
- Other info:

**Comment by strint** [comment]
这个问题之前没有，今天出现的？

**Comment by strint** [comment]
dtype 的 类型是 flow.dtype ？

**Comment by jackalcooper** [comment]
> 这个问题之前没有，今天出现的？

嗯。在升级代码，好像是因为oneflow的module或者nn graph的block不支持dtype这个函数

**Comment by strint** [comment]
写了一个例子，没有复现这里的错误：https://github.com/Oneflow-Inc/oneflow/pull/9347

**Comment by strint** [comment]
这个代码链接发下看看：
```
File "/home/caishenghang/diffusers/src/diffusers/models/unet_2d_condition_oneflow.py"
```

**Comment by strint** [comment]
```
class ModuleDtype(flow.nn.Module):
            def __init__(self):
                super().__init__()
                self.dtype = flow.float64
                self.linear = flow.nn.Linear(3, 8, False).to("cuda")
                print(self.linear.weight.dtype)
            
            def forward(self, x):
                dt = self.dtype
                print(dt)
                self.linear.to(dtype=self.dtype)
                print(self.linear.weight.dtype)
                return self.linear(x)
```
nn.Module 上默认是没有 dtype 方法和 attr 的，没有这句， dtype 是哪里来的呢

**Comment by jackalcooper** [comment]
> 这个代码链接发下看看：
> 
> ```
> File "/home/caishenghang/diffusers/src/diffusers/models/unet_2d_condition_oneflow.py"
> ```

https://github.com/huggingface/diffusers/blob/7fb4b882b9618005035fdd70d78b312bbcd2a5ef/src/diffusers/models/unet_2d_condition.py#L286

**Comment by strint** [comment]
https://github.com/huggingface/diffusers/blob/7fb4b882b9618005035fdd70d78b312bbcd2a5ef/src/diffusers/modeling_utils.py#L572

这个 dtype 来自继承的基类的自定义函数。

**Comment by strint** [comment]
Fixed in： https://github.com/Oneflow-Inc/oneflow/pull/9351
