### ISSUE TITLE
RuntimeError: This package is a placeholder. Please install oneflow following the instructions

### ISSUE THREAD

**Issue by shileims** [Oneflow-Inc/oneflow#9398]
## Summary

import oneflow as torch

"RuntimeError: This package is a placeholder. Please install oneflow following the instructions"

## Code to reproduce bug

import oneflow as torch

## System Information
Windows10

- What is your OneFlow installation (pip, source, dockerhub):
- OS: windows
- OneFlow version (run `python3 -m oneflow --doctor`): 0.7.0
- Python version: 3.7
- CUDA driver version: 11.6
- GPU models: 
- Other info:

**Comment by shangguanshiyuan** [comment]
Thanks for your feedback. OneFlow does not support compiling, installing, and running on the Windows at this time. Do you want to run OneFlow on Windows for stable diffusion or some other models?

**Comment by dario-github** [comment]
> Thanks for your feedback. OneFlow does not support compiling, installing, and running on the Windows at this time. Do you want to run OneFlow on Windows for stable diffusion or some other models?

请问WSL2上也不支持吗？

**Comment by shangguanshiyuan** [comment]
> 请问WSL2上也不支持吗？

因为windows对linux子系统的支持不全面，缺少一些linux下的库，所以oneflow目前不完全支持wsl。您是希望在windows下运行哪类模型？

**Comment by dario-github** [comment]
你好，希望运行的是SD模型

**Comment by shangguanshiyuan** [comment]
> 你好，希望运行的是SD模型

你好，感谢您的关注，目前oneflow还不支持在windows环境下运行。

**Comment by yao266** [comment]
20230627，现在oneflow还不能在windows环境下运行。

**Comment by Cyame** [comment]
在Kylin Arm64上出现同样问题 看包的大小确实也不对... 应该是暂未提供支持吧

**Comment by bdjimmy** [comment]
arm64 也遇到同样的问题，这个是不支持吗

**Comment by higkoo** [comment]
Debian 11 Linux ，也有同样的问题。进官网，开心的执行官方命令，顺利的安装成功，就喜提异常：
$ python3 -c "import oneflow as flow; print(f'OneFlow版本：{flow.__version__}')"
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/llama-run/app/miniforge/envs/OneFlow/lib/python3.11/site-packages/oneflow/__init__.py", line 21, in <module>
    raise RuntimeError("This package is a placeholder. Please install oneflow following the instructions in https://github.com/Oneflow-Inc/oneflow#install-oneflow")
RuntimeError: This package is a placeholder. Please install oneflow following the instructions in https://github.com/Oneflow-Inc/oneflow#install-oneflow`

**Comment by Buddingpopp** [comment]
> Debian 11 Linux ，也有同样的问题。进官网，开心的执行官方命令，顺利的安装成功，就喜提异常： $ python3 -c "import oneflow as flow; print(f'OneFlow版本：{flow.**version**}')"$python3-c“import oneflow as flow; print（f'OneFlow 版本：{flow. ** 版本 **}” `Traceback (most recent call last): File "<string>", line 1, in <module> File "/mnt/llama-run/app/miniforge/envs/OneFlow/lib/python3.11/site-packages/oneflow/__init__.py", line 21, in <module> raise RuntimeError("This package is a placeholder. Please install oneflow following the instructions in https://github.com/Oneflow-Inc/oneflow#install-oneflow") RuntimeError: This package is a placeholder. Please install oneflow following the instructions in https://github.com/Oneflow-Inc/oneflow#install-oneflow`
请问这个问题你解决了吗？我在Ubuntu 24.04环境上也有同样的错误。raise RuntimeError("This package is a placeholder. Please install oneflow following the instructions in https://github.com/Oneflow-Inc/oneflow#install-oneflow")
RuntimeError: This package is a placeholder. Please install oneflow following the instructions in https://github.com/Oneflow-Inc/oneflow#install-oneflow
