### ISSUE TITLE
[Bug] nn.Graph config error: `ProxyModule' object 'module_pipeline.m_stage0' in nn.Graph has no attribute 'config'

### ISSUE THREAD

**Issue by strint** [Oneflow-Inc/oneflow#9457]
## Summary
When upgrade oneflow version after 0.8.1， there may be error like：`ProxyModule' object  in nn.Graph has no attribute 'config'

```
Traceback (most recent call last):
  File "./pipeline.py", line 70, in <module>
Traceback (most recent call last):
      File "./pipeline.py", line 70, in <module>
graph_pipeline = PipelineGraph()
  File "./pipeline.py", line 58, in __init__
    self.module_pipeline.m_stage0.config.set_stage(stage_id=0, placement=P0)
  File "/home/shiyuan/.local/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py", line 486, in __getattr__
    graph_pipeline = PipelineGraph()
  File "./pipeline.py", line 58, in __init__
    self.module_pipeline.m_stage0.config.set_stage(stage_id=0, placement=P0)
  File "/home/shiyuan/.local/lib/python3.8/site-packages/oneflow/nn/graph/proxy.py", line 486, in __getattr__
    raise AttributeError(
AttributeError: 'MODULE' 'ProxyModule' object 'module_pipeline.m_stage0' in nn.Graph has no attribute 'config'
```

**Comment by strint** [comment]
This is because we have a breaking change in the module config API, `activation_checkpointing` and `set_stage` are affected.

Old style:
```
if isinstance(module_block.origin, BertEmbeddings):
    module_block.config.set_stage(...)
    module_block.config.activation_checkpointing = True

```

New style:
```
if isinstance(module_block.to(nn.Module), BertEmbeddings):
    module_block.to(nn.graph.GraphModule).set_stage(...)
    module_block.to(nn.graph.GraphModule).activation_checkpointing = True

```

We must change this to avoid name collision of GraphModule and Module.

New API Doc: https://oneflow.readthedocs.io/en/master/graph.html#config-options-on-a-graphmodule
Related PR: https://github.com/Oneflow-Inc/oneflow/pull/9351
