### ISSUE TITLE
oneflow._softmax_backward_data is not implemented

### ISSUE THREAD

**Issue by Yaodada12** [Oneflow-Inc/oneflow#9835]
### Description

Traceback (most recent call last):
  File "/home/user/Software/Anaconda/envs/test/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1050, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/user/Software/Anaconda/envs/test/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/Software/Anaconda/envs/test/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 27, in <module>
    from ...modeling_utils import PreTrainedModel
  File "/home/user/Software/Anaconda/envs/test/lib/python3.8/site-packages/transformers/modeling_utils.py", line 41, in <module>
    from .generation_utils import GenerationMixin
  File "/home/user/Software/Anaconda/envs/test/lib/python3.8/site-packages/transformers/generation_utils.py", line 61, in <module>
    from .pytorch_utils import torch_int_div
  File "/home/user/Software/Anaconda/envs/test/lib/python3.8/site-packages/transformers/pytorch_utils.py", line 19, in <module>
    from torch import _softmax_backward_data, nn
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/home/user/Software/Anaconda/envs/test/lib/python3.8/site-packages/oneflow/mock_torch/__init__.py", line 42, in __getattr__
    raise NotImplementedError(self.module.__name__ + "." + name + error_msg)
NotImplementedError: oneflow._softmax_backward_data is not implemented, please submit an issue at  
'https://github.com/Oneflow-Inc/oneflow/issues' including the log information of the error, the 
minimum reproduction code, and the system information.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/Desktop/yao/projects/Text2img/AIdraw/en/utils/scheduling_ddim_oneflow.py", line 9, in <module>
    from diffusers.configuration_utils import ConfigMixin, register_to_config
  File "/home/user/Software/Anaconda/envs/test/lib/python3.8/site-packages/diffusers/__init__.py", line 22, in <module>
    from transformers import CLIPTextModel, CLIPFeatureExtractor
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/home/user/Software/Anaconda/envs/test/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1041, in __getattr__
    value = getattr(module, name)
  File "/home/user/Software/Anaconda/envs/test/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1040, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/user/Software/Anaconda/envs/test/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1052, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):
oneflow._softmax_backward_data is not implemented, please submit an issue at  
'https://github.com/Oneflow-Inc/oneflow/issues' including the log information of the error, the 
minimum reproduction code, and the system information.

**Comment by strint** [comment]
You may need to update the transformers.

Eelete the local oneflow version of transformers, directly use the official

```
python3 -m pip install transformers>=4.26

cd diffusers

python3 -m pip install -e .[oneflow]
```

Reference: https://github.com/Oneflow-Inc/diffusers/pull/83#discussion_r1092913239

**Comment by yuanms2** [comment]
The cause of the error is explained here: 

https://github.com/huggingface/transformers/pull/20796

**Comment by Yaodada12** [comment]
> You may need to update the transformers.
> 
> Delete the local oneflow version of transformers, directly use the official
> 
> ```
> python3 -m pip install transformers>=4.26
> 
> cd diffusers
> 
> python3 -m pip install -e .[oneflow]
> ```
> 
> Reference: [Oneflow-Inc/diffusers#83 (comment)](https://github.com/Oneflow-Inc/diffusers/pull/83#discussion_r1092913239)

好的，多谢大佬。我发现里面谈到编译共享的问题，现在静态图编译是已经动态尺寸推理了吗？

**Comment by Yaodada12** [comment]
> The cause of the error is explained here:
> 
> [huggingface/transformers#20796](https://github.com/huggingface/transformers/pull/20796)

多谢大佬！！

**Comment by strint** [comment]
> 我发现里面谈到编译共享的问题，现在静态图编译是已经支持动态尺寸推理了吗？


## 多尺寸输入遇到的问题
stable diffuison 任务在实际部署时，需要支持多 shape 的推理，当前采用了每种 shape 一个 graph 的方式来实现。一个实际用户那边需要9种输入，对应9个 graph。多个 graph 使用遇到两个问题。

问题1，常量折叠新产生的 tensor，多个 graph 间没有共享，导致多余开销。input 不同但是其它相同的每个 graph，编译都会做常量折叠，常量折叠会把和 input 无关的常量编译时计算好，这样运行时就无需计算。带来的问题是会产生新 tensor，而每个 graph 都产生自己新 tensor的话，多个 graph 之间就冗余了。

问题2, 多个 graph，上线服务时启动编译，时间比较久。用户反馈线上机器 cpu 比较弱，编译慢，希望离线编译好，线上直接加载使用。因为采用预测接口触发编译，stable diffuison unet 编译9个图（每个6.5s，共58.5s）和执行9个输入的推理，总时间约150s（在oneflow 15机器做的测评）。

## 解决办法
对于问题1，多个 graph 共享 pass 优化后的图和常量折叠后的参数。对于stable diffuison  的 9 种 input，打开共享，可以节约近一半显存开销，每个图可以节约28%的编译时间。

对于问题2，支持离线编译，把 graph 编译后的执行计划等运行时状态保存下来，编译一次后所有线上服务加载编译结果就可使用。采用 graph 加载，stable diffuison unet 加载9个图，每个不到1s，共约8s，而之前需要150s。

以上办法**主要适用于在线推理的输入shape 是有限的几种的场景**，可以明显的减少显存和编译时间。适合优化那种限定几种尺寸的在线服务。

## 使用说明
这里是一个测试用例，可以先跑通作来验证功能：https://github.com/Oneflow-Inc/diffusers/blob/oneflow-fork/tests/test_pipelines_oneflow_graph_load.py

- https://github.com/Oneflow-Inc/diffusers/pull/83#issuecomment-1413122072
- https://github.com/Oneflow-Inc/oneflow/issues/9778#issuecomment-1416901434

@Yaodada12

**Comment by Yaodada12** [comment]
> > 我发现里面谈到编译共享的问题，现在静态图编译是已经支持动态尺寸推理了吗？
> 
> 可以参见这里更新的评论：[Oneflow-Inc/diffusers#75 (comment)](https://github.com/Oneflow-Inc/diffusers/issues/75#issuecomment-1418789541)
> 
> @Yaodada12

好的，点赞。

**Comment by terrancewang** [comment]
Hello, I had the same issue as this post. After updating the transformers package, I now have a similar error:

Traceback (most recent call last):
  File "/home/terrance/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1110, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/terrance/.local/lib/python3.10/site-packages/transformers/models/clip/modeling_clip.py", line 27, in <module>
    from ...modeling_utils import PreTrainedModel
  File "/home/terrance/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 83, in <module>
    from accelerate import __version__ as accelerate_version
  File "/home/terrance/.local/lib/python3.10/site-packages/accelerate/__init__.py", line 7, in <module>
    from .accelerator import Accelerator
  File "/home/terrance/.local/lib/python3.10/site-packages/accelerate/accelerator.py", line 27, in <module>
    import torch.utils.hooks as hooks
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "/home/terrance/.local/lib/python3.10/site-packages/oneflow/mock_torch/__init__.py", line 88, in create_module
    raise NotImplementedError(oneflow_mod_fullname + error_msg)
NotImplementedError: oneflow.utils.hooks is not implemented, please submit an issue at  
'https://github.com/Oneflow-Inc/oneflow/issues' including the log information of the error, the 
minimum reproduction code, and the system information.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/terrance/oneflow/test_diffusion.py", line 2, in <module>
    from diffusers import OneFlowStableDiffusionPipeline
  File "/home/terrance/oneflow/diffusers/src/diffusers/__init__.py", line 22, in <module>
    from transformers import CLIPTextModel, CLIPFeatureExtractor
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/home/terrance/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1101, in __getattr__
    value = getattr(module, name)
  File "/home/terrance/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1100, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/terrance/.local/lib/python3.10/site-packages/transformers/utils/import_utils.py", line 1112, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):
oneflow.utils.hooks is not implemented, please submit an issue at  
'https://github.com/Oneflow-Inc/oneflow/issues' including the log information of the error, the 
minimum reproduction code, and the system information.

Anyone seen this before?
