### ISSUE TITLE
[Question]: 可否改进SBP的报错信息？

### ISSUE THREAD

**Issue by PYNing** [Oneflow-Inc/oneflow#9942]
### Description

即使设置了 os.environ["ONEFLOW_DEBUG_MODE"] = "1"、os.environ["GLOG_v"] = "3"，
当SBP设置有误时，仅有一个 **died with <Signals.SIGBUS: 7>** 的报错信息，
此报错信息能否改进？

以下为代码例子

**Code**

```python
import os
os.environ["ONEFLOW_DEBUG_MODE"] = "1"
os.environ["GLOG_v"] = "3"

import oneflow as flow

placement = flow.placement("cuda", [0,1])
x = flow.randn(4,5,placement=placement, sbp=flow.sbp.broadcast)
# w = flow.randn(5,8,placement=placement, sbp=flow.sbp.split(1)) # right
w = flow.randn(5,8,placement=placement, sbp=flow.sbp.split(0)) # error
y = flow.matmul(x,w)
y.sbp
y.shape
```

**Lunch Command**
`python3 -m oneflow.distributed.launch --nproc_per_node 2 ./testExample.py `

**Output**
```
Ignoring PCI device with non-16bit domain.
Pass --enable-32bits-pci-domain to configure to support such devices
(warning: it would break the library ABI, don't enable unless really needed).
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Ignoring PCI device with non-16bit domain.
Pass --enable-32bits-pci-domain to configure to support such devices
(warning: it would break the library ABI, don't enable unless really needed).
Ignoring PCI device with non-16bit domain.
Pass --enable-32bits-pci-domain to configure to support such devices
(warning: it would break the library ABI, don't enable unless really needed).
WARNING: Logging before InitGoogleLogging() is written to STDERR
I20230306 11:16:41.234145 385262 singleton.h:43] DeleteGlobal N7oneflow17ForeignLockHelperE
WARNING: Logging before InitGoogleLogging() is written to STDERR
I20230306 11:16:41.234829 385261 singleton.h:43] DeleteGlobal N7oneflow17ForeignLockHelperE
Killing subprocess 385261
Killing subprocess 385262
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/miniconda3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/oneflow_pyning/python/oneflow/distributed/launch.py", line 240, in <module>
    main()
  File "/data/oneflow_pyning/python/oneflow/distributed/launch.py", line 228, in main
    sigkill_handler(signal.SIGTERM, None)
  File "/data/oneflow_pyning/python/oneflow/distributed/launch.py", line 196, in sigkill_handler
    raise subprocess.CalledProcessError(
subprocess.CalledProcessError: Command '['/root/miniconda3/bin/python3', '-u', './testExample.py']' died with <Signals.SIGBUS: 7>.
```

**Comment by daquexian** [comment]
这份代码在我这里是可以正常结束的，可能是其它原因导致了错误：

```
$ cat temp.py
import os
os.environ["ONEFLOW_DEBUG_MODE"] = "1"
os.environ["GLOG_v"] = "3"

import oneflow as flow

placement = flow.placement("cuda", [0,1])
x = flow.randn(4,5,placement=placement, sbp=flow.sbp.broadcast)
# w = flow.randn(5,8,placement=placement, sbp=flow.sbp.split(1)) # right
w = flow.randn(5,8,placement=placement, sbp=flow.sbp.split(0)) # error
y = flow.matmul(x,w)
y.sbp
y.shape
$ python3 -m oneflow.distributed.launch --nproc_per_node 2 temp.py
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
```

**Comment by PYNing** [comment]
我对SBP还不够熟悉，特别它的自动推导
但按我的理解，w沿着第0维切分，不符合分块矩阵的计算规则，应该要报错的

![image](https://user-images.githubusercontent.com/11667149/223037155-8629452d-b31b-44ee-9604-d0507005ad66.png)

**Comment by daquexian** [comment]
> 但按我的理解，w沿着第0维切分，不符合分块矩阵的计算规则，应该要报错的

虽然不符合矩阵乘法规则，但 oneflow 会自动做 boxing，把 x 或 w 变换为具有符合矩阵乘法的 sbp，所以不会报错，只是多出来了通信

**Comment by PYNing** [comment]
了解了的。之前的崩溃应该有其他原因，我再排查一下。谢谢大老师！
