### ISSUE TITLE
[Performance Issue]: RuntimeError: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):

### ISSUE THREAD

**Issue by Edanaw** [Oneflow-Inc/oneflow#9978]
### Brief Description

RuntimeError: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):

### Device and Context

gpu driver：460
cudua version: 11.2
python: 3.8.10

libibverbs not available, ibv_fork_init skipped
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/import_utils.py", line 1110, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/clip/modeling_clip.py", line 27, in <module>
    from ...modeling_utils import PreTrainedModel
  File "/usr/local/lib/python3.8/dist-packages/transformers/modeling_utils.py", line 83, in <module>
    from accelerate import __version__ as accelerate_version
  File "/usr/local/lib/python3.8/dist-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/usr/local/lib/python3.8/dist-packages/accelerate/accelerator.py", line 28, in <module>
    import torch.utils.hooks as hooks
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "/usr/local/lib/python3.8/dist-packages/oneflow/mock_torch/__init__.py", line 88, in create_module
    raise NotImplementedError(oneflow_mod_fullname + error_msg)
NotImplementedError: oneflow.utils.hooks is not implemented, please submit an issue at
'https://github.com/Oneflow-Inc/oneflow/issues' including the log information of the error, the
minimum reproduction code, and the system information.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "ai_painting.py", line 33, in <module>
    from onediff import OneFlowStableDiffusionPipeline, OneFlowStableDiffusionInpaintPipeline
  File "/usr/local/lib/python3.8/dist-packages/onediff/__init__.py", line 21, in <module>
    from .pipeline_stable_diffusion_oneflow import OneFlowStableDiffusionPipeline
  File "/usr/local/lib/python3.8/dist-packages/onediff/pipeline_stable_diffusion_oneflow.py", line 11, in <module>
    from transformers import CLIPFeatureExtractor, CLIPTextModel, CLIPTokenizer
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/import_utils.py", line 1101, in __getattr__
    value = getattr(module, name)
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/import_utils.py", line 1100, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.8/dist-packages/transformers/utils/import_utils.py", line 1112, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):
oneflow.utils.hooks is not implemented, please submit an issue at
'https://github.com/Oneflow-Inc/oneflow/issues' including the log information of the error, the
minimum reproduction code, and the system information.

**Comment by Edanaw** [comment]
nvidia-smi
Sat Mar 11 08:43:58 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.73.01    Driver Version: 460.73.01    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 208...  Off  | 00000000:1A:00.0 Off |                  N/A |
| 27%   22C    P8     5W / 250W |      0MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce RTX 208...  Off  | 00000000:1B:00.0 Off |                  N/A |
| 27%   21C    P8     1W / 250W |      0MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  GeForce RTX 208...  Off  | 00000000:3D:00.0 Off |                  N/A |
| 27%   21C    P8    20W / 250W |      0MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  GeForce RTX 208...  Off  | 00000000:3E:00.0 Off |                  N/A |
| 27%   22C    P8     1W / 250W |   7962MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  GeForce RTX 208...  Off  | 00000000:88:00.0 Off |                  N/A |
| 27%   20C    P8     1W / 250W |      0MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  GeForce RTX 208...  Off  | 00000000:89:00.0 Off |                  N/A |
| 27%   21C    P8    16W / 250W |      0MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  GeForce RTX 208...  Off  | 00000000:B1:00.0 Off |                  N/A |
| 27%   21C    P8     1W / 250W |  10925MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  GeForce RTX 208...  Off  | 00000000:B2:00.0 Off |                  N/A |
| 27%   21C    P8    19W / 250W |      0MiB / 11019MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

**Comment by daquexian** [comment]
Could you please upgrade both oneflow and onediff to the latest and try once again? Thanks!

**Comment by Edanaw** [comment]
> Could you please upgrade both oneflow and onediff to the latest and try once again? Thanks!


How to update to the latest version？Thanks

This is my current version：

pip show oneflow
Name: oneflow
Version: 0.9.0
Summary: UNKNOWN
Home-page: https://www.oneflow.org/
Author:
Author-email:
License: UNKNOWN
Location: /usr/local/lib/python3.8/dist-packages
Requires: numpy, pillow, protobuf, requests, rich, tqdm
Required-by:

 pip show onediff
Name: onediff
Version: 0.4.0
Summary: OneFlow backend for diffusers
Home-page: https://github.com/Oneflow-Inc/oneflow
Author: OneFlow contributors
Author-email: caishenghang@oneflow.co
License: Apache
Location: /usr/local/lib/python3.8/dist-packages
Requires: diffusers, transformers
Required-by:
